// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FullTextStrategy.
const (
	FetchPage      FullTextStrategy = "fetch_page"
	RssDescription FullTextStrategy = "rss_description"
)

// Defines values for HealthDb.
const (
	HealthDbDown HealthDb = "down"
	HealthDbOk   HealthDb = "ok"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Defines values for Platform.
const (
	Wechat      Platform = "wechat"
	Xiaohongshu Platform = "xiaohongshu"
	Zhihu       Platform = "zhihu"
)

// Defines values for SourceCategory.
const (
	Kol      SourceCategory = "kol"
	News     SourceCategory = "news"
	Research SourceCategory = "research"
	Tutorial SourceCategory = "tutorial"
)

// Defines values for SourceRole.
const (
	Material SourceRole = "material"
	Signal   SourceRole = "signal"
)

// Defines values for SourceType.
const (
	Crawler SourceType = "crawler"
	Manual  SourceType = "manual"
	Rss     SourceType = "rss"
	Rsshub  SourceType = "rsshub"
)

// Defines values for TopicStatus.
const (
	Approved  TopicStatus = "approved"
	Candidate TopicStatus = "candidate"
	InWriting TopicStatus = "in_writing"
	Rejected  TopicStatus = "rejected"
	Scored    TopicStatus = "scored"
	Written   TopicStatus = "written"
)

// CreateTopicRequest defines model for CreateTopicRequest.
type CreateTopicRequest struct {
	Angle           string     `json:"angle"`
	Summary         string     `json:"summary"`
	TargetPlatforms []Platform `json:"targetPlatforms"`
	Title           string     `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FullTextStrategy defines model for FullTextStrategy.
type FullTextStrategy string

// Health defines model for Health.
type Health struct {
	Db     HealthDb     `json:"db"`
	Status HealthStatus `json:"status"`
}

// HealthDb defines model for Health.Db.
type HealthDb string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// IngestUrlRequest defines model for IngestUrlRequest.
type IngestUrlRequest struct {
	// Note 备注（为什么觉得这条值得写）
	Note *string `json:"note,omitempty"`
	Url  string  `json:"url"`
}

// JobAccepted defines model for JobAccepted.
type JobAccepted struct {
	MsgId int64  `json:"msgId"`
	Queue string `json:"queue"`
}

// Platform defines model for Platform.
type Platform string

// RejectTopicRequest defines model for RejectTopicRequest.
type RejectTopicRequest struct {
	// Reason 否决原因（留痕，供后续 rubric 校准参考）
	Reason *string `json:"reason,omitempty"`
}

// SchedulerSettings defines model for SchedulerSettings.
type SchedulerSettings struct {
	SourceFetch   SourceFetchSchedule   `json:"sourceFetch"`
	TopicEvaluate TopicEvaluateSchedule `json:"topicEvaluate"`
	TopicScout    TopicScoutSchedule    `json:"topicScout"`
}

// SchedulerSettingsPatch 仅传需要改的分组
type SchedulerSettingsPatch struct {
	SourceFetch   *SourceFetchSchedule   `json:"sourceFetch,omitempty"`
	TopicEvaluate *TopicEvaluateSchedule `json:"topicEvaluate,omitempty"`
	TopicScout    *TopicScoutSchedule    `json:"topicScout,omitempty"`
}

// Source defines model for Source.
type Source struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// SourceCategory defines model for SourceCategory.
type SourceCategory string

// SourceFetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
type SourceFetchConfig struct {
	FullText        *FullTextStrategy `json:"fullText,omitempty"`
	IntervalMinutes *int              `json:"intervalMinutes"`
	MaxAgeDays      *int              `json:"maxAgeDays,omitempty"`
	MaxItems        *int              `json:"maxItems,omitempty"`
	Role            *SourceRole       `json:"role,omitempty"`
}

// SourceFetchSchedule defines model for SourceFetchSchedule.
type SourceFetchSchedule struct {
	DefaultIntervalMinutes int  `json:"defaultIntervalMinutes"`
	Enabled                bool `json:"enabled"`
}

// SourceHealth defines model for SourceHealth.
type SourceHealth struct {
	ConsecutiveFailures int `json:"consecutiveFailures"`

	// ItemCount 该源累计入库条目数
	ItemCount     *int       `json:"itemCount,omitempty"`
	LastError     *string    `json:"lastError"`
	LastRunAt     *time.Time `json:"lastRunAt"`
	LastSuccessAt *time.Time `json:"lastSuccessAt"`
	NextRunAt     *time.Time `json:"nextRunAt"`
}

// SourceInput defines model for SourceInput.
type SourceInput struct {
	Category SourceCategory `json:"category"`
	Enabled  *bool          `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourcePatch 仅传需要改的字段
type SourcePatch struct {
	Category *SourceCategory `json:"category,omitempty"`
	Enabled  *bool           `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourceRole defines model for SourceRole.
type SourceRole string

// SourceType defines model for SourceType.
type SourceType string

// SourceWithHealth defines model for SourceWithHealth.
type SourceWithHealth struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Health      SourceHealth       `json:"health"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// Topic defines model for Topic.
type Topic struct {
	Angle           string               `json:"angle"`
	Id              openapi_types.UUID   `json:"id"`
	LatestScore     *float32             `json:"latestScore"`
	RawItemIds      []openapi_types.UUID `json:"rawItemIds"`
	Status          TopicStatus          `json:"status"`
	Summary         string               `json:"summary"`
	TargetPlatforms []Platform           `json:"targetPlatforms"`
	Title           string               `json:"title"`
}

// TopicEvaluateSchedule defines model for TopicEvaluateSchedule.
type TopicEvaluateSchedule struct {
	Enabled        bool `json:"enabled"`
	MaxConcurrency int  `json:"maxConcurrency"`
}

// TopicEvaluation defines model for TopicEvaluation.
type TopicEvaluation struct {
	AgentRunId *openapi_types.UUID `json:"agentRunId"`
	CreatedAt  time.Time           `json:"createdAt"`

	// DimensionReasons 逐维度理由
	DimensionReasons *map[string]string `json:"dimensionReasons,omitempty"`
	DimensionScores  map[string]float32 `json:"dimensionScores"`
	Id               openapi_types.UUID `json:"id"`
	JudgeModel       string             `json:"judgeModel"`
	Rationale        string             `json:"rationale"`

	// RubricVersion 如 topic@v1
	RubricVersion string             `json:"rubricVersion"`
	TopicId       openapi_types.UUID `json:"topicId"`
	TotalScore    float32            `json:"totalScore"`

	// VetoedDimension 触发一票否决的维度 key（topic@v1 暂无 veto 维度，但字段就位）
	VetoedDimension *string `json:"vetoedDimension"`

	// WeightVersion 生效权重版本（weight_sets.version），使评分可回放
	WeightVersion *int `json:"weightVersion"`
}

// TopicScoutSchedule defines model for TopicScoutSchedule.
type TopicScoutSchedule struct {
	Enabled     bool     `json:"enabled"`
	MinNewItems int      `json:"minNewItems"`
	Times       []string `json:"times"`
	Timezone    string   `json:"timezone"`
}

// TopicStatus defines model for TopicStatus.
type TopicStatus string

// SourceId defines model for SourceId.
type SourceId = openapi_types.UUID

// TopicId defines model for TopicId.
type TopicId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// ListTopicsParams defines parameters for ListTopics.
type ListTopicsParams struct {
	Status *TopicStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int         `form:"offset,omitempty" json:"offset,omitempty"`
}

// IngestUrlJSONRequestBody defines body for IngestUrl for application/json ContentType.
type IngestUrlJSONRequestBody = IngestUrlRequest

// UpdateSchedulerSettingsJSONRequestBody defines body for UpdateSchedulerSettings for application/json ContentType.
type UpdateSchedulerSettingsJSONRequestBody = SchedulerSettingsPatch

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = SourceInput

// UpdateSourceJSONRequestBody defines body for UpdateSource for application/json ContentType.
type UpdateSourceJSONRequestBody = SourcePatch

// CreateManualTopicJSONRequestBody defines body for CreateManualTopic for application/json ContentType.
type CreateManualTopicJSONRequestBody = CreateTopicRequest

// RejectTopicJSONRequestBody defines body for RejectTopic for application/json ContentType.
type RejectTopicJSONRequestBody = RejectTopicRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 健康检查（含 DB 连通性）
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
	// (POST /v1/ingest/url)
	IngestUrl(w http.ResponseWriter, r *http.Request)
	// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
	// (POST /v1/scout/run)
	TriggerTopicScout(w http.ResponseWriter, r *http.Request)
	// 读调度设置
	// (GET /v1/settings/schedules)
	GetSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
	// (PATCH /v1/settings/schedules)
	UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 信源列表（含采集健康状态）
	// (GET /v1/sources)
	ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams)
	// 新增信源
	// (POST /v1/sources)
	CreateSource(w http.ResponseWriter, r *http.Request)
	// 删除信源（已采集的 raw_items 保留，仅解除订阅）
	// (DELETE /v1/sources/{sourceId})
	DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 信源详情
	// (GET /v1/sources/{sourceId})
	GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 修改信源（含启停与单独采集频率覆盖）
	// (PATCH /v1/sources/{sourceId})
	UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 立即采集该信源（不等调度）
	// (POST /v1/sources/{sourceId}/fetch)
	TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 选题列表（按状态过滤，latestScore 倒序）
	// (GET /v1/topics)
	ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams)
	// 手动创建选题（M0 验收：空管道插入一条手动 topic）
	// (POST /v1/topics)
	CreateManualTopic(w http.ResponseWriter, r *http.Request)
	// 选题详情
	// (GET /v1/topics/{topicId})
	GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工确认选题（scored → approved）
	// (POST /v1/topics/{topicId}/approve)
	ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
	// (GET /v1/topics/{topicId}/evaluations)
	ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工否决选题（candidate/scored → rejected）
	// (POST /v1/topics/{topicId}/reject)
	RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 健康检查（含 DB 连通性）
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
// (POST /v1/ingest/url)
func (_ Unimplemented) IngestUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
// (POST /v1/scout/run)
func (_ Unimplemented) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 读调度设置
// (GET /v1/settings/schedules)
func (_ Unimplemented) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
// (PATCH /v1/settings/schedules)
func (_ Unimplemented) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源列表（含采集健康状态）
// (GET /v1/sources)
func (_ Unimplemented) ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 新增信源
// (POST /v1/sources)
func (_ Unimplemented) CreateSource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 删除信源（已采集的 raw_items 保留，仅解除订阅）
// (DELETE /v1/sources/{sourceId})
func (_ Unimplemented) DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源详情
// (GET /v1/sources/{sourceId})
func (_ Unimplemented) GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 修改信源（含启停与单独采集频率覆盖）
// (PATCH /v1/sources/{sourceId})
func (_ Unimplemented) UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即采集该信源（不等调度）
// (POST /v1/sources/{sourceId}/fetch)
func (_ Unimplemented) TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题列表（按状态过滤，latestScore 倒序）
// (GET /v1/topics)
func (_ Unimplemented) ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动创建选题（M0 验收：空管道插入一条手动 topic）
// (POST /v1/topics)
func (_ Unimplemented) CreateManualTopic(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题详情
// (GET /v1/topics/{topicId})
func (_ Unimplemented) GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工确认选题（scored → approved）
// (POST /v1/topics/{topicId}/approve)
func (_ Unimplemented) ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
// (GET /v1/topics/{topicId}/evaluations)
func (_ Unimplemented) ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工否决选题（candidate/scored → rejected）
// (POST /v1/topics/{topicId}/reject)
func (_ Unimplemented) RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestUrl operation middleware
func (siw *ServerInterfaceWrapper) IngestUrl(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTopicScout operation middleware
func (siw *ServerInterfaceWrapper) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTopicScout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSourcesParams

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", r.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSource operation middleware
func (siw *ServerInterfaceWrapper) CreateSource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSource operation middleware
func (siw *ServerInterfaceWrapper) UpdateSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSourceFetch operation middleware
func (siw *ServerInterfaceWrapper) TriggerSourceFetch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSourceFetch(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopics operation middleware
func (siw *ServerInterfaceWrapper) ListTopics(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTopicsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateManualTopic operation middleware
func (siw *ServerInterfaceWrapper) CreateManualTopic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateManualTopic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopic operation middleware
func (siw *ServerInterfaceWrapper) GetTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveTopic operation middleware
func (siw *ServerInterfaceWrapper) ApproveTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopicEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListTopicEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopicEvaluations(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectTopic operation middleware
func (siw *ServerInterfaceWrapper) RejectTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/ingest/url", wrapper.IngestUrl)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/scout/run", wrapper.TriggerTopicScout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/settings/schedules", wrapper.GetSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/settings/schedules", wrapper.UpdateSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources", wrapper.ListSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources", wrapper.CreateSource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/sources/{sourceId}", wrapper.DeleteSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources/{sourceId}", wrapper.GetSource)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/sources/{sourceId}", wrapper.UpdateSource)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources/{sourceId}/fetch", wrapper.TriggerSourceFetch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics", wrapper.ListTopics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics", wrapper.CreateManualTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}", wrapper.GetTopic)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/approve", wrapper.ApproveTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}/evaluations", wrapper.ListTopicEvaluations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/reject", wrapper.RejectTopic)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbX1cTybb/Kr36zsO9ayIJqLPu8HQd1Hu5Z5xxAXPOg8NxFZ0iae10x+5q0PFkraD8",
	"CQqCIwiCojAEmFGDf2YkhiBrnY/ipLo7T/kKZ1VXp9Od7k6i4Oia82RMqnbtvX/7X+1dXGU5KZGURCgi",
	"he28yiaBDBIQQdn8X6+kyhzsjpLPvMh2skmA4myIFUECsp2sUv05xMrwksrLMMp2IlmFIVbh4jAByL5B",
	"SU4AxHayqsqTlehK0tyLZF6MsalUiO2TkjwXeAiyfj3IGSmyWUlKogJNub4C0R54SYUKIv/jJBFB0fwI",
	"kkmB5wDiJTF8QZFE8l3tmM9kOMh2sv8RruksTH9VwqdkWZLpUVGocDKfJETYTtbY3tGeXys/WNFezrOp",
	"ENsliYMCz/0BJ5fyt/DeHTw5rd94paVH8PgL/ZeRSjGDNyx26PfabyPG3pPf0yPliWk8O13aX9UKs7+n",
	"R/CNh8b1PbzzAo/c1+e2KsVJwv43EjotqWL0D1Dcb6NaYbaUn8ZPF/H9LdNUrE2EZpcMAYKm7TiwTMpS",
	"EsqIpzgDMSZA8qHOIEKsoiYSQL7i+xsCcgyiswJAxK5MQjyC9EMjSao7CI0EL3bTPe22OQJZBlfMA3hE",
	"2Urw4tdQjKG4c5nDM2oWf87aFLJkqkng5bffJiUNXIAcIkdSLXsUxElRf/0koKKAmN9vdWyZFGrr/c4+",
	"rQpCH7yMepEMEIyZSoeimiDbZUU574Q9xA5CxMXPJ93Eaoz9HwQC0Ve9JNEBJ1npIhtio9Kw6EtDQQCp",
	"St36/mYAWLtC5Cg/MbvFGFTQd7IQaI6ihEyNuu0cr09oL7cqxUwpXyjtpkuvM8bmJH6zYOzf0x6s4nQR",
	"v1nA4/eI//nIosqCOwLKPNtMErLHT4L/lwZOcBxMIhj1Mp9QYjRG20fxIvriWO0wXkQwBmVC6JIK1RZs",
	"hy4LWaT9OLJdyoHVZR5IcUmMKXGVDbE/xHnz32HIxQHyhbsHEnKNI4UMgRW16sCZ3cDjL/Gth3j5UaWY",
	"0efv6QvzleJU6c0ynr2l7z5lZHVA5jlGe7SKJ8bxzDUjfd0XqpSPeL1cHEZVAcq9ECFejClexmiOPU2c",
	"oln86a0trRI2ow0R/NQQEFRAza8RjT7nYg+VXk5SUUskzJW1/fWu5BDKRbqe2/5WlHYWWMqpS3+7Y6Xi",
	"o/L9tLExos291pdGcWZc3x1lQ39WFXtVZbLrE/ZJHJZo+msubld1dSrEQhEMCDQ8WKcNSJIAgUh+NEM3",
	"qW/42Dso0tqQCrF8tIVirloYNsme1S9aYaOPrKzFUlEVBCJltc70UB6GfCxugpQAl/kECUvtZsqnnyP2",
	"FlFNDJCIWGf+plimFNZKenSohot9Rk3jbvX2B6Ld5cC2GjJFOKyYBbQCgUx9TkWSzANy6EVJ8A2bXoi8",
	"0XF6XivMlicmysvj5bFpfS9XKS6TPCAPAeEML6oIKkwpX9B/LhirW/p6QXuxr89t4bEt/Dxd3l00cuse",
	"bxy0qoVm0HmqCmJA7qPdCEUi/x1xoHQ8FAS0I5ElwOUTMXgSXHHTOvrFcQel9oCd3dWi0d53PBJptk+W",
	"hBattkdq7PbuKOUtmOAgUAXU/W4q8zLcICLUmX3NkgPODjbqoKqPI1c6TkX8EDwNeEGVLQm8rujgmBTz",
	"XZJKLy71l7WsVpjVf902cqt4LIsLd7QHq/pyTpt/xoaakBWAguwyu2kMIat7VPEEcoW8KEDwCOLNyNAS",
	"iV6V46CiHISMCC8fjBPPjcCLSTCy3WJSRR8oQ1lmVsf2ISasTygT2bJG2o6H3jMvuVOSDUEweK1XXk8X",
	"tNxvnlj/idYhLcL6IcuFAIX3WNmhmtgTAEErjSt8TASNMnmfZYWOqzepCRQlrg6Q4AZE1STEyWBYgHID",
	"Sn/jUbwWkYEgfDvIdp5rRdFsKlTv6XGbUPPt1qH1dmuR8Nppf7W7+C6toRarUAEgqKBeTpJhfdJ0gxtg",
	"H1WwQ6wMhkmp0B11t5qaclDfVqq1NZrfHejST6YR1jijUPED+18O/Xl5DtX6Nk7E/GKa/8XMYzkNQ08C",
	"XO6SRE6VZShyV9xFY0fj2i+wWqqj2Yx1nvYx6sw9BkWS5bt9jbtpCOPMZmu0QY3g2RLlE1BUeEnsMVsr",
	"lItolCf8AeGsizvvZlc+Kadn9d1fcWFDnx3X556zPgqwTzPhbXiYw1MbRmGfU1oMDRfUaAyekaJQ8BVO",
	"BpQt//BD+0l/hbLC+zakNq4xZqPgf4bafYNCbZjSPIBICAgtRDCPYoYgkmD0ZFXnPnX05gaeuV3Kp/Xs",
	"Fm2h6UujFEPmIrxSKWaqMjDa0jVt4RFDSDJ0RaU4VdobpyUDfva8tDdNG2otJtpA1elzD7X5jPbgenli",
	"Wp/MaPefVIoZuue8ApHSNkR3VoqTJgv7xvYozozjmW28vKLNvWGb3xh9A1dtgOWCtp5frxG7EHLajcvE",
	"nN4ZGBvczaJ3jGm8+A0c9t5m2yMBhuK4FJHo4E4cSYAQlAkef//Pc5H2/nORI1/2/6PjXOTI0f7/6jwX",
	"OXKcfvWZn8XWbtUdx5rmlgT8QRLfec5Si7uUdwcltyqCde0ZL3BAjPIkWpJ0RNAk5EEyKUtD5kdePD8s",
	"84iwE2LJJwRFs19D6MKo32zC7HYMSl4rV7i4JABZOQJ4ppRfwjdWtUd5vH+d6TnV28ecONvN4OxtnXhZ",
	"5kyEKf+ypa28qhSnyksz5YkpfeumvnZbm/wZP5+vFCd/T1/7XsS5ldLeHX33jrYySkr56flSPl0q3MS5",
	"Fe0BuS5ri9tMW5ud/asMtNEv2i4oksi8Tc+9Tc8x2v0n2t2J0u6rUv6pvjT6vUjXMNriNh57ZXJnbI7j",
	"5TeV4nIpv26kx0r5tDHxq5be1OeeM13dTDk9qz3NGhvj+vLdSjFjbI6Udu/gwh2m59SJk2dOMbiY1ube",
	"lBdy5bXFqgR29WBr5wgBgRzHkmBmxQs20tbeFiEwSkkogiTPdrJH2yJtR8m9BaC4CWmYFps/kM8xaOZD",
	"4kima5Kwy/4vRFaZWjd07ohEDm1oahfCnlz57V/ooLRa1rF4JIsLO9pPae1htlLM4NnHzMmvGGN/pZxe",
	"0tKb5lg3FWLDQ+1h3pxgha17TVJSfMSzp1zWQB4q6CspeuXQJPNM0VJuByVxN+XRbMehne+cgfmoF++8",
	"wGPZ8uJDYibHKKJ+5Gz+wo63Bm5gtMmb+MaWdmMe373GfNfzNQEns4Mzz3B2r5S/b2T3tYVX+tJoKZ8u",
	"z+XwWBbP/FQpTvWePdV1JBI5yvxzs6OtwwmfQmJ8WFbFYPT6ZD4Wg3Kfc+Lyiajyy+aqtJ9OuBWpP76J",
	"p18aO6Te0J6sltOT5bVFY2QJz2bMqeq0/nTSeHbdrCyW8f6ePp9lHIHcpUJrpGTKQFKl0sjPveO7D+jy",
	"3sNa8X5je5eKbuTe6Hs5oupktWnjlue7ZNRx7XGLdPhuHjDEa8nZP4JOD+zrc6+dMFSKmbeT60w7U8r/",
	"wiCeu8jQ2rRSXDYf4WyX8tPG2mP91jZeu45nFssTM9WM57BVsyUSbKBf8wrqtdaEXA+7zlkPrS6p0LxA",
	"Wy+tapVPTXueln7/AeFoqYHgaTN5uh0tmD59yIQzC8bqFk18dFBFEyJ9+2Q9avIPlvSFkdW4+kBu4OiB",
	"t2T77Yd8tJ8mqdzR97L6g0Vy7e4zvLZCgau38/DV6nPDFC16BUhn7W7QTprf26DVmb0fV7UlYfu9o4+Z",
	"H/OW2t9ITJcFhSn4seaC28/n6oq0zKPyvXUqOLHVnRfUVvWlUUYGw+dNr2FK+w/0+Xvkbro7Zmz+VL63",
	"buTWyotjlhUHpqnDV0bkkM3Q6erBEfj99Us1a2xvaNfHmufAQ9HXhwoWHydRBgaL98yOB4Uzp829rrnL",
	"7GM8u41H7pfyt/D0vH7zifUkYe22fmsiMHM6Ikp4sPr6p2Hd3Ot6t3R47vSxau53QuAwinSKi7GdtbFz",
	"l+c1jMyuWePipo8uaam2sYcAranRNSRJhfxpCnyCRy6S9hD2eMQxg+1o9uoj6ABpcFCBASc06bwdOGa7",
	"+4N21dZS+UZHbj4TKrOd6SgrA/um5inV9d5GWwvVH70F2tWfNjVJKz5jf0LbXa8UpxzTIAanf8SFmRaK",
	"wTPmkJTK92GCvM+z9j+4MLTQO9y60KfzgTPLeLdAcao2I6e0uVeV4pL+c0HPrZZH7mgzP+KxLLnXP1il",
	"u+jwwxspwletPnuq0Y29ity7he7qH6h80EIoUO0Hr36sjohV/QSoLWz1o4OT4Am64N9GhwdLeKVCAe9k",
	"9dWckVu3jZw2/5m34z8y1fZ/I1MOQ3uk20IqPOVY/NHgaT1BOMbVLV7vD8ML9KVRa6x3axzPvKgUM3To",
	"iDPjzOcMHTAzn1uv+sPuYeGUI08EIUZnNsFO5PhjhAOCdPi5x+cPJVLeP577czssnVbbDmtP7sIO163O",
	"5aghECJQHqpiaE5P2DBI8myqP/WvAAAA//8jUL2/YDkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
