// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ArticleFormat.
const (
	Html     ArticleFormat = "html"
	Markdown ArticleFormat = "markdown"
	RichText ArticleFormat = "rich_text"
)

// Defines values for ArticleStatus.
const (
	ArticleStatusApproved      ArticleStatus = "approved"
	ArticleStatusDraft         ArticleStatus = "draft"
	ArticleStatusPendingReview ArticleStatus = "pending_review"
	ArticleStatusPublished     ArticleStatus = "published"
	ArticleStatusRejected      ArticleStatus = "rejected"
	ArticleStatusRewriteQueued ArticleStatus = "rewrite_queued"
	ArticleStatusScored        ArticleStatus = "scored"
)

// Defines values for FullTextStrategy.
const (
	FetchPage      FullTextStrategy = "fetch_page"
	RssDescription FullTextStrategy = "rss_description"
)

// Defines values for HealthDb.
const (
	HealthDbDown HealthDb = "down"
	HealthDbOk   HealthDb = "ok"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Defines values for Platform.
const (
	Wechat      Platform = "wechat"
	Xiaohongshu Platform = "xiaohongshu"
	Zhihu       Platform = "zhihu"
)

// Defines values for SourceCategory.
const (
	Kol      SourceCategory = "kol"
	News     SourceCategory = "news"
	Research SourceCategory = "research"
	Tutorial SourceCategory = "tutorial"
)

// Defines values for SourceRole.
const (
	Material SourceRole = "material"
	Signal   SourceRole = "signal"
)

// Defines values for SourceType.
const (
	Crawler SourceType = "crawler"
	Manual  SourceType = "manual"
	Rss     SourceType = "rss"
	Rsshub  SourceType = "rsshub"
)

// Defines values for TopicStatus.
const (
	TopicStatusApproved  TopicStatus = "approved"
	TopicStatusCandidate TopicStatus = "candidate"
	TopicStatusInWriting TopicStatus = "in_writing"
	TopicStatusRejected  TopicStatus = "rejected"
	TopicStatusScored    TopicStatus = "scored"
	TopicStatusWritten   TopicStatus = "written"
)

// Article defines model for Article.
type Article struct {
	Assets            []map[string]interface{} `json:"assets"`
	ContentMd         string                   `json:"contentMd"`
	CreatedAt         time.Time                `json:"createdAt"`
	Format            ArticleFormat            `json:"format"`
	Id                openapi_types.UUID       `json:"id"`
	LatestScore       *float32                 `json:"latestScore"`
	Platform          Platform                 `json:"platform"`
	PreviousArticleId *openapi_types.UUID      `json:"previousArticleId"`
	Status            ArticleStatus            `json:"status"`
	Title             string                   `json:"title"`
	TopicId           openapi_types.UUID       `json:"topicId"`
	UpdatedAt         time.Time                `json:"updatedAt"`
	Version           int                      `json:"version"`
	WriterAgent       string                   `json:"writerAgent"`
}

// ArticleDetail defines model for ArticleDetail.
type ArticleDetail struct {
	Article      Article             `json:"article"`
	Evaluations  []ArticleEvaluation `json:"evaluations"`
	Publications []Publication       `json:"publications"`
	Topic        Topic               `json:"topic"`
	Versions     []Article           `json:"versions"`
}

// ArticleEvaluation defines model for ArticleEvaluation.
type ArticleEvaluation struct {
	AgentRunId       *openapi_types.UUID `json:"agentRunId"`
	ArticleId        openapi_types.UUID  `json:"articleId"`
	CreatedAt        time.Time           `json:"createdAt"`
	DimensionReasons map[string]string   `json:"dimensionReasons"`
	DimensionScores  map[string]float32  `json:"dimensionScores"`
	Id               openapi_types.UUID  `json:"id"`
	JudgeModel       string              `json:"judgeModel"`
	PassThreshold    float32             `json:"passThreshold"`
	Passed           bool                `json:"passed"`
	Rationale        string              `json:"rationale"`
	RubricVersion    string              `json:"rubricVersion"`
	TotalScore       float32             `json:"totalScore"`
	VetoedDimension  *string             `json:"vetoedDimension"`
	WeightVersion    *int                `json:"weightVersion"`
}

// ArticleFormat defines model for ArticleFormat.
type ArticleFormat string

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []ArticleReview `json:"items"`
	Total int             `json:"total"`
}

// ArticleReview defines model for ArticleReview.
type ArticleReview struct {
	Article          Article            `json:"article"`
	LatestEvaluation *ArticleEvaluation `json:"latestEvaluation,omitempty"`
	PublicationCount int                `json:"publicationCount"`
	TopicTitle       string             `json:"topicTitle"`
}

// ArticleStatus defines model for ArticleStatus.
type ArticleStatus string

// CreatePublicationRequest defines model for CreatePublicationRequest.
type CreatePublicationRequest struct {
	FinalContentMd         string `json:"finalContentMd"`
	FinalTitle             string `json:"finalTitle"`
	FollowerCountAtPublish *int   `json:"followerCountAtPublish"`

	// PlatformPostId 平台侧 ID 或公开链接
	PlatformPostId string `json:"platformPostId"`

	// PublishedAt 未传时由 Core 使用当前时间
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
}

// CreateTopicRequest defines model for CreateTopicRequest.
type CreateTopicRequest struct {
	Angle           string     `json:"angle"`
	Summary         string     `json:"summary"`
	TargetPlatforms []Platform `json:"targetPlatforms"`
	Title           string     `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FullTextStrategy defines model for FullTextStrategy.
type FullTextStrategy string

// Health defines model for Health.
type Health struct {
	Db     HealthDb     `json:"db"`
	Status HealthStatus `json:"status"`
}

// HealthDb defines model for Health.Db.
type HealthDb string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// IngestUrlRequest defines model for IngestUrlRequest.
type IngestUrlRequest struct {
	// Note 备注（为什么觉得这条值得写）
	Note *string `json:"note,omitempty"`
	Url  string  `json:"url"`
}

// JobAccepted defines model for JobAccepted.
type JobAccepted struct {
	MsgId int64  `json:"msgId"`
	Queue string `json:"queue"`
}

// Platform defines model for Platform.
type Platform string

// Publication defines model for Publication.
type Publication struct {
	ArticleId              openapi_types.UUID `json:"articleId"`
	CreatedAt              time.Time          `json:"createdAt"`
	EditRatio              *float32           `json:"editRatio"`
	FinalContentDiff       *string            `json:"finalContentDiff"`
	FollowerCountAtPublish *int               `json:"followerCountAtPublish"`
	Id                     openapi_types.UUID `json:"id"`
	Platform               Platform           `json:"platform"`
	PlatformPostId         *string            `json:"platformPostId"`
	PublishedAt            time.Time          `json:"publishedAt"`
}

// RejectArticleRequest defines model for RejectArticleRequest.
type RejectArticleRequest struct {
	// Reason 终审拒绝原因
	Reason *string `json:"reason,omitempty"`
}

// RejectTopicRequest defines model for RejectTopicRequest.
type RejectTopicRequest struct {
	// Reason 否决原因（留痕，供后续 rubric 校准参考）
	Reason *string `json:"reason,omitempty"`
}

// SchedulerSettings defines model for SchedulerSettings.
type SchedulerSettings struct {
	SourceFetch   SourceFetchSchedule   `json:"sourceFetch"`
	TopicEvaluate TopicEvaluateSchedule `json:"topicEvaluate"`
	TopicScout    TopicScoutSchedule    `json:"topicScout"`
}

// SchedulerSettingsPatch 仅传需要改的分组
type SchedulerSettingsPatch struct {
	SourceFetch   *SourceFetchSchedule   `json:"sourceFetch,omitempty"`
	TopicEvaluate *TopicEvaluateSchedule `json:"topicEvaluate,omitempty"`
	TopicScout    *TopicScoutSchedule    `json:"topicScout,omitempty"`
}

// Source defines model for Source.
type Source struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// SourceCategory defines model for SourceCategory.
type SourceCategory string

// SourceFetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
type SourceFetchConfig struct {
	FullText        *FullTextStrategy `json:"fullText,omitempty"`
	IntervalMinutes *int              `json:"intervalMinutes"`
	MaxAgeDays      *int              `json:"maxAgeDays,omitempty"`
	MaxItems        *int              `json:"maxItems,omitempty"`
	Role            *SourceRole       `json:"role,omitempty"`
}

// SourceFetchSchedule defines model for SourceFetchSchedule.
type SourceFetchSchedule struct {
	DefaultIntervalMinutes int  `json:"defaultIntervalMinutes"`
	Enabled                bool `json:"enabled"`
}

// SourceHealth defines model for SourceHealth.
type SourceHealth struct {
	ConsecutiveFailures int `json:"consecutiveFailures"`

	// ItemCount 该源累计入库条目数
	ItemCount     *int       `json:"itemCount,omitempty"`
	LastError     *string    `json:"lastError"`
	LastRunAt     *time.Time `json:"lastRunAt"`
	LastSuccessAt *time.Time `json:"lastSuccessAt"`
	NextRunAt     *time.Time `json:"nextRunAt"`
}

// SourceInput defines model for SourceInput.
type SourceInput struct {
	Category SourceCategory `json:"category"`
	Enabled  *bool          `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourcePatch 仅传需要改的字段
type SourcePatch struct {
	Category *SourceCategory `json:"category,omitempty"`
	Enabled  *bool           `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourceRole defines model for SourceRole.
type SourceRole string

// SourceType defines model for SourceType.
type SourceType string

// SourceWithHealth defines model for SourceWithHealth.
type SourceWithHealth struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Health      SourceHealth       `json:"health"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// Topic defines model for Topic.
type Topic struct {
	Angle           string               `json:"angle"`
	Id              openapi_types.UUID   `json:"id"`
	LatestScore     *float32             `json:"latestScore"`
	RawItemIds      []openapi_types.UUID `json:"rawItemIds"`
	Status          TopicStatus          `json:"status"`
	Summary         string               `json:"summary"`
	TargetPlatforms []Platform           `json:"targetPlatforms"`
	Title           string               `json:"title"`
}

// TopicEvaluateSchedule defines model for TopicEvaluateSchedule.
type TopicEvaluateSchedule struct {
	Enabled        bool `json:"enabled"`
	MaxConcurrency int  `json:"maxConcurrency"`
}

// TopicEvaluation defines model for TopicEvaluation.
type TopicEvaluation struct {
	AgentRunId *openapi_types.UUID `json:"agentRunId"`
	CreatedAt  time.Time           `json:"createdAt"`

	// DimensionReasons 逐维度理由
	DimensionReasons *map[string]string `json:"dimensionReasons,omitempty"`
	DimensionScores  map[string]float32 `json:"dimensionScores"`
	Id               openapi_types.UUID `json:"id"`
	JudgeModel       string             `json:"judgeModel"`
	Rationale        string             `json:"rationale"`

	// RubricVersion 如 topic@v1
	RubricVersion string             `json:"rubricVersion"`
	TopicId       openapi_types.UUID `json:"topicId"`
	TotalScore    float32            `json:"totalScore"`

	// VetoedDimension 触发一票否决的维度 key（topic@v1 暂无 veto 维度，但字段就位）
	VetoedDimension *string `json:"vetoedDimension"`

	// WeightVersion 生效权重版本（weight_sets.version），使评分可回放
	WeightVersion *int `json:"weightVersion"`
}

// TopicScoutSchedule defines model for TopicScoutSchedule.
type TopicScoutSchedule struct {
	Enabled     bool     `json:"enabled"`
	MinNewItems int      `json:"minNewItems"`
	Times       []string `json:"times"`
	Timezone    string   `json:"timezone"`
}

// TopicStatus defines model for TopicStatus.
type TopicStatus string

// ArticleId defines model for ArticleId.
type ArticleId = openapi_types.UUID

// SourceId defines model for SourceId.
type SourceId = openapi_types.UUID

// TopicId defines model for TopicId.
type TopicId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	Status   *ArticleStatus      `form:"status,omitempty" json:"status,omitempty"`
	Platform *Platform           `form:"platform,omitempty" json:"platform,omitempty"`
	TopicId  *openapi_types.UUID `form:"topicId,omitempty" json:"topicId,omitempty"`
	Limit    *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// ListTopicsParams defines parameters for ListTopics.
type ListTopicsParams struct {
	Status *TopicStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int         `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreatePublicationJSONRequestBody defines body for CreatePublication for application/json ContentType.
type CreatePublicationJSONRequestBody = CreatePublicationRequest

// RejectArticleJSONRequestBody defines body for RejectArticle for application/json ContentType.
type RejectArticleJSONRequestBody = RejectArticleRequest

// IngestUrlJSONRequestBody defines body for IngestUrl for application/json ContentType.
type IngestUrlJSONRequestBody = IngestUrlRequest

// UpdateSchedulerSettingsJSONRequestBody defines body for UpdateSchedulerSettings for application/json ContentType.
type UpdateSchedulerSettingsJSONRequestBody = SchedulerSettingsPatch

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = SourceInput

// UpdateSourceJSONRequestBody defines body for UpdateSource for application/json ContentType.
type UpdateSourceJSONRequestBody = SourcePatch

// CreateManualTopicJSONRequestBody defines body for CreateManualTopic for application/json ContentType.
type CreateManualTopicJSONRequestBody = CreateTopicRequest

// RejectTopicJSONRequestBody defines body for RejectTopic for application/json ContentType.
type RejectTopicJSONRequestBody = RejectTopicRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 健康检查（含 DB 连通性）
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// 文章审阅列表（可按状态、平台、选题过滤）
	// (GET /v1/articles)
	ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams)
	// 文章详情（原稿、版本链、最新评分和发布记录）
	// (GET /v1/articles/{articleId})
	GetArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 人工终审通过（pending_review → approved）
	// (POST /v1/articles/{articleId}/approve)
	ApproveArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 文章评分历史（倒序）
	// (GET /v1/articles/{articleId}/evaluations)
	ListArticleEvaluations(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 登记一次人工发布；首次登记同时执行 approved → published
	// (POST /v1/articles/{articleId}/publications)
	CreatePublication(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 人工终审拒绝（pending_review → rejected）
	// (POST /v1/articles/{articleId}/reject)
	RejectArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
	// (POST /v1/ingest/url)
	IngestUrl(w http.ResponseWriter, r *http.Request)
	// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
	// (POST /v1/scout/run)
	TriggerTopicScout(w http.ResponseWriter, r *http.Request)
	// 读调度设置
	// (GET /v1/settings/schedules)
	GetSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
	// (PATCH /v1/settings/schedules)
	UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 信源列表（含采集健康状态）
	// (GET /v1/sources)
	ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams)
	// 新增信源
	// (POST /v1/sources)
	CreateSource(w http.ResponseWriter, r *http.Request)
	// 删除信源（已采集的 raw_items 保留，仅解除订阅）
	// (DELETE /v1/sources/{sourceId})
	DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 信源详情
	// (GET /v1/sources/{sourceId})
	GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 修改信源（含启停与单独采集频率覆盖）
	// (PATCH /v1/sources/{sourceId})
	UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 立即采集该信源（不等调度）
	// (POST /v1/sources/{sourceId}/fetch)
	TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 选题列表（按状态过滤，latestScore 倒序）
	// (GET /v1/topics)
	ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams)
	// 手动创建选题（M0 验收：空管道插入一条手动 topic）
	// (POST /v1/topics)
	CreateManualTopic(w http.ResponseWriter, r *http.Request)
	// 选题详情
	// (GET /v1/topics/{topicId})
	GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工确认选题（scored → approved）
	// (POST /v1/topics/{topicId}/approve)
	ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
	// (GET /v1/topics/{topicId}/evaluations)
	ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工否决选题（candidate/scored → rejected）
	// (POST /v1/topics/{topicId}/reject)
	RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 健康检查（含 DB 连通性）
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章审阅列表（可按状态、平台、选题过滤）
// (GET /v1/articles)
func (_ Unimplemented) ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章详情（原稿、版本链、最新评分和发布记录）
// (GET /v1/articles/{articleId})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工终审通过（pending_review → approved）
// (POST /v1/articles/{articleId}/approve)
func (_ Unimplemented) ApproveArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章评分历史（倒序）
// (GET /v1/articles/{articleId}/evaluations)
func (_ Unimplemented) ListArticleEvaluations(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 登记一次人工发布；首次登记同时执行 approved → published
// (POST /v1/articles/{articleId}/publications)
func (_ Unimplemented) CreatePublication(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工终审拒绝（pending_review → rejected）
// (POST /v1/articles/{articleId}/reject)
func (_ Unimplemented) RejectArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
// (POST /v1/ingest/url)
func (_ Unimplemented) IngestUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
// (POST /v1/scout/run)
func (_ Unimplemented) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 读调度设置
// (GET /v1/settings/schedules)
func (_ Unimplemented) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
// (PATCH /v1/settings/schedules)
func (_ Unimplemented) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源列表（含采集健康状态）
// (GET /v1/sources)
func (_ Unimplemented) ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 新增信源
// (POST /v1/sources)
func (_ Unimplemented) CreateSource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 删除信源（已采集的 raw_items 保留，仅解除订阅）
// (DELETE /v1/sources/{sourceId})
func (_ Unimplemented) DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源详情
// (GET /v1/sources/{sourceId})
func (_ Unimplemented) GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 修改信源（含启停与单独采集频率覆盖）
// (PATCH /v1/sources/{sourceId})
func (_ Unimplemented) UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即采集该信源（不等调度）
// (POST /v1/sources/{sourceId}/fetch)
func (_ Unimplemented) TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题列表（按状态过滤，latestScore 倒序）
// (GET /v1/topics)
func (_ Unimplemented) ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动创建选题（M0 验收：空管道插入一条手动 topic）
// (POST /v1/topics)
func (_ Unimplemented) CreateManualTopic(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题详情
// (GET /v1/topics/{topicId})
func (_ Unimplemented) GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工确认选题（scored → approved）
// (POST /v1/topics/{topicId}/approve)
func (_ Unimplemented) ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
// (GET /v1/topics/{topicId}/evaluations)
func (_ Unimplemented) ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工否决选题（candidate/scored → rejected）
// (POST /v1/topics/{topicId}/reject)
func (_ Unimplemented) RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameter("form", true, false, "platform", r.URL.Query(), &params.Platform)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "topicId" -------------

	err = runtime.BindQueryParameter("form", true, false, "topicId", r.URL.Query(), &params.TopicId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveArticle operation middleware
func (siw *ServerInterfaceWrapper) ApproveArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticleEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListArticleEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticleEvaluations(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePublication operation middleware
func (siw *ServerInterfaceWrapper) CreatePublication(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePublication(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectArticle operation middleware
func (siw *ServerInterfaceWrapper) RejectArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestUrl operation middleware
func (siw *ServerInterfaceWrapper) IngestUrl(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTopicScout operation middleware
func (siw *ServerInterfaceWrapper) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTopicScout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSourcesParams

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", r.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSource operation middleware
func (siw *ServerInterfaceWrapper) CreateSource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSource operation middleware
func (siw *ServerInterfaceWrapper) UpdateSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSourceFetch operation middleware
func (siw *ServerInterfaceWrapper) TriggerSourceFetch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSourceFetch(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopics operation middleware
func (siw *ServerInterfaceWrapper) ListTopics(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTopicsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateManualTopic operation middleware
func (siw *ServerInterfaceWrapper) CreateManualTopic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateManualTopic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopic operation middleware
func (siw *ServerInterfaceWrapper) GetTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveTopic operation middleware
func (siw *ServerInterfaceWrapper) ApproveTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopicEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListTopicEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopicEvaluations(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectTopic operation middleware
func (siw *ServerInterfaceWrapper) RejectTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles", wrapper.ListArticles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles/{articleId}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/approve", wrapper.ApproveArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles/{articleId}/evaluations", wrapper.ListArticleEvaluations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/publications", wrapper.CreatePublication)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/reject", wrapper.RejectArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/ingest/url", wrapper.IngestUrl)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/scout/run", wrapper.TriggerTopicScout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/settings/schedules", wrapper.GetSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/settings/schedules", wrapper.UpdateSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources", wrapper.ListSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources", wrapper.CreateSource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/sources/{sourceId}", wrapper.DeleteSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources/{sourceId}", wrapper.GetSource)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/sources/{sourceId}", wrapper.UpdateSource)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources/{sourceId}/fetch", wrapper.TriggerSourceFetch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics", wrapper.ListTopics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics", wrapper.CreateManualTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}", wrapper.GetTopic)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/approve", wrapper.ApproveTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}/evaluations", wrapper.ListTopicEvaluations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/reject", wrapper.RejectTopic)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RcW1cT2Z7/KrVqzsPMOpEEL2fN4Wlo1DPMtH1cQM88eBhXkWySaitV6apdoO2wVlAu",
	"QbkpIAh4webWrQbUbowhwFrzUdrsquQpX2HWrl1VqWtSkYCe009Ksq//6+9/2blNR4VkSuABDyW67Tad",
	"YkQmCSAQtb/aRchGOdAZw3+wPN1GpxiYoEM0zyQB3UYz5vchWgTfy6wIYnQbFGUQoqVoAiQZPLFfEJMM",
	"pNtoWWbxSHgrhSdLUGT5OD00FKK7BVmM+m8jGV8fb5ceIcVGfTeB+rfH2WMIT5ZSAi8BjX5fMbEu8L0M",
	"JIj/igo8BLz2XyaV4tgoA1mBD38nCTz+rLrNH0TQT7fR/xSu8iZMvpXCl0RREMlWMSBFRTaFF6Hb6NLO",
	"e+XNnfKTp8q7BXooRHcIfD/HRk9h52JuGh3MoYkp9d6ekh5GY2/Vn4crhQza1I9DPld+HS4dvPqYHi6P",
	"T6HZqeLRmpKf/ZgeRveele4eoPdv0fCqOr9dKUzg438jwMuCzMdOgXC/jij52WJuCr1eQqvbmqjokyw6",
	"oCmHKKSACFnCXEaSAFEaFoIk+SgWY/GqDHfVMpRIkS4rQt93IArxDfUPGFFkbuG/9Vte0a7skKwQHRUB",
	"A0GsHdrkMMZAcAaySeAWxpA5qjZd9PtdJoOHQjQbCyDqIZpjIJBgd1QQNdokmZtsUk7Sba2RSIhOsjz5",
	"KxKieZnjmD5MQRsheDnZB0S8UopjIN6u3kmvGuPwHBEMsIIs2SyU88w+O1fvIEEGylJACnWTwZhzLCQC",
	"4VoQVk1MXQLKqVijHB0AosQSoTcp3GqOY3kI4oSkgyILgdge17XGbQurNu4aTY5nmj+THdX9vOhtypdB",
	"D6sEhwztsB/FpLhdfKzSbaVLr4fW6Ae4CCDDch5KWdXWACzFC4IBhpM1g2LX5QDTL5lTvfQ5JfcZpir4",
	"ylerk7zW1LhUbw3Nz1nEpeF7uXd2SIxBZeNAlq3sBHVQoQZDLbR0MxULT5fMf6KWM7VsRDMMbYxNAh5f",
	"vwswkk5vb1fgZTKcBDFX05Sj5mIWo2u3uS4b69oloJX/To7FwRUhBjjPw6cYSepJiEBKCFysthtwm31s",
	"IqzOrk8QOMBoci8y5LreVlaU+0Q2+l9VY+hhhyHDBfBNrkMNACiA2EWDBXh2XfkaBGw8AS3H8Zlh2mcv",
	"+2uD0rb7OTdwS4iHBNpIYKWnjaXu+zpZarIpZNVCq5bU0OnLJgABPCb4NTrJiDdiwiDeJwGT+AAiG01c",
	"h+CmdaEqafWFvmYJgrabBdOkNWLbusAACwa9bStkOJtrjdRnnbazMbcGKfRtm+CviOO0m8uGfZXFKncI",
	"MgEJta6tG/oeH+BT2z306PDAtWkNenWbyMwQnZjI9GsIAos0CdM0aHH9exnI2gcpwMdYPn5dJLQO4WBB",
	"FAbId3hvKaFPxJuBmKfEdWiCbXHDlgDOzrp+lme4DitoT7L814CPw4QVlVnwOJ5gkrDeYIHjhEEgapRq",
	"h1fJ+Z18qmdpqmjuqiBB4gHt0Q/68A7N7BYPt6jOi5SSeYRGX6FCujx3qExv0KF6pzTJStylfWll9edi",
	"4bmyuKfOv6E6BBFQxYMjdX6bBIvK4l558ZcqjKzpYx0C5riUjbQhJ2O8pIxwWQNKvvxl+LiP/5HkZJIR",
	"b3l7HkaMA2iEKg0AP0twk2T5TjKn1cNMBRIgB8EMhE7uVL2B+7xe1CKhs4tAUSHmTZ8kkCQmHsBQaCtU",
	"x3vtfVnmuB5wE3ZDkYEgfstqEkRJum4VuRDdD2A0cT1lX6x6sH8HDAcT7pvE+qzLCjewR8VeqrdmzGgZ",
	"31uPAWbcE+vzvGYnHwcS/FbkfMWRFyDwUN/1ceXddqWQKebyxf108UOmtDWBDhdLR4+VJ2soXUCHi2js",
	"caUw4RmCipwdBYpsXd3Dc7xu8B9CX3s0ClKQYDr74ZNS3AG/WR7+6TztZbE0e15fdsiwkL6014muWvIK",
	"Bq9usoyQEPi4lJDpEP1DgtX+HQTRBOONQKwBmZ/3PrnIAsRY2IU3t8PYBhMsVoN4ke3vD4Rqm+WAAgYa",
	"n5QEcvm2urdyOKxP8D0utG7Jl7j8knU7Dz5YGexL8Xpgu0uDMybO9DEfohYYuA2Iup9B2TXl/kN1/wma",
	"foZWnntSwGfX2h7Ub080u4nG3pHdKoWMuvBYXVyoFCaLhytodlrdf02RCIhSnq+h8TE0c6eUvutpwrxO",
	"1h1NgJjMAbEbQMjyccl9MFJQuIydRT15664ONRY24bCOqUGghIwx2LVKd1SQYaAltJHV+U4XY7mUbWnn",
	"aXuDEO0qoxPHkevfHy0WnpdX06XNYWX+g7o8gjJj6v6IliL8hySxm1TacT3gEMYnAoGF9a/bYYzGVp7H",
	"NssnFaJBmg6B72fjDRBSnxDc/pIqWN2whHwQ5Bg9eGQVYwTMotTycw6/5mWXtVvoI8nWoSpfzD2qFLeT",
	"t9eX2x0W3hpQggeDkhZNSoARic7JUBBZBm96Q+A84YSbRW7rOLWg5GfL4+PllbHy6JR6kK0UVrBDFQcY",
	"7grLyxBIVDGXV3/Kl9a21fW88laLqka30Zt0eX+plF13aWO/jqLrsc6FtrEA2bd2JtT+1ZpSuxAEESSZ",
	"m+1xcJG5ZV/r3J8uhOqUNZLMzU4jmDLnXbAl9TzniQIXUGq7hNpqb7dS7kAC9DMyBzsbI5n7wDUsgkPs",
	"q5Lss7e/UPtFQ1GBl0BUhuwAuMywnKwnoWvnh3CQa6aSnJXpDSU/q/6yU8quodENlJ9TnqypK1llYZcO",
	"1VmWYyRohp91bQge3SXzNbBdoCW65WgUSNJxluHBzeOdxBUpu3niz9lOPiXDE/JQupg5jt1Eh/UFeSLz",
	"rpGWC6FP9Et2l2SywJ95wZHX60Ul+6vL1n+hOCQgW08SLvgQvEv3DtUiBQS6G5fYOM/U8uQ9uhRaUlIY",
	"E0hSQu7Dxo3hZW2hqMgMckCssdJ/szBRtcgMx/21n267FoTQ9FDIqekJc6H60/VNnXKrL+GW016jlaqR",
	"lOmpN5WIzCCGCp0xewq27gmc6dZgLSIkdjAbRL6MBHGQrg/fvLCFfu4z+/RxeNk078DMJTk1TU+Sudkh",
	"8FFZFAEfvWUHjWdrYz9ftORYs97RT6Iv4bQ7Dez+pJyeVfd/QflNdXZMnX9D/513IjTYMeAIuTbvUFqi",
	"4N8GWj2NQgNtXc1sPXDg6K1NNPOgmEurG9skhaYujxAeUjfArUohY9yBUpbvKIvPKbwkRUZUCpPFgzEC",
	"GdDum+LBFEmoNd7d4Mgfzj9TFjLKk7vl8Sl1IqOsvqoUMmTOdQlAqUXvDKoUJrQjHJV2RlBmDM3soJWn",
	"yvwhHfqkdglLt27DzRLBOiNqJ109kkUN2jSW/wYMuqPZ1oiPoFhr8WzS0QGRYiAEIubH//zztUhr77XI",
	"mT/3/u/Za5Ez53r/pe1a5MwF8tEfvCS2GlWfPV/XtyTBDwLfcP2xanfJ2S0r2UnhT2tX2S3K8DEWW0tr",
	"U4Cl5M/y1wdFFuLjkC5ECPja1f8hLdvRL7ilXIomBI4RpTMMSxVzy+jemvI8h47uUl2Xunuo9qudFNp4",
	"oGIty1yJUOWft5Wne5XCZHl5pjw+qW7fV188UCZ+Qm8WKoWJj+k7f+NR9mnxYE7dn1OejmAoP7VQzKWL",
	"+fso+1R5gsNlZWmHamkxvb9xgBbyQct3ksBTv6Xnf0vPU8rqK+XReHF/r5h7rS6P/I0nYyhlaQeN7mmn",
	"K22NoZXDSmGlmFsvpUeLuXRp/BclvaVV5jupcnpWeb1R2hxTVx5VCpnS1nBxfw7l56iuS+0Xr1yiUCGt",
	"zB+WF7PlF0vGDUz0YFLnDGYC3s7SOdpGR1paWyKYjUIK8EyKpdvocy2RlnNaaxFMaCwNE7D5A/5/HGj+",
	"ECuSpprY7NJ/AVCHqY4O+7ORSNM6xE0g7PKVf/1P0hVuwDoaDW+g/Hvlx7TybKNSyKDZl9TFr6jS0dNy",
	"ellJb2k97EMhOjzQGtZLRZLv3b5mJaN6ozVMWl5gXNNfKnwvAw2UGe8hDPAV7F6O/mUcLXitaqljBVu3",
	"ikj9lqxa6QbeaXgvxbFJFtoWMoPzCxFLbH62XjbQbwOhv18CPjvUschDvScoldYWOB/RDNHnyYZe65gH",
	"C1teo9ilWXk0rr58jrJr5aVRlFksrW1jmZ7ZUSYnyNONj+lh0if0MT1cTk+UXyyVjsaV/XUvOQ/fNouj",
	"Q7X0ud1sEnNIvNclqkPC1Q700yC73mdeg/Dn6xPefMviRfbSzqZydxQTfPqZun30MT1MYFR57vBjelhZ",
	"TSuPdnXM9HASzTxAubul7C46WKhH/LDuCzV8IEgeXGgnA/4+ONE0HuAJf64/wXw/ZWdaMZ9H7zdI1byc",
	"Xi4djVcKGXvnIfXb2EPKACJ1ueR4f1DPRVyyd9d/LoY165nESeqVpjPTY2jmLdau9EOUn6nLDeejDW/F",
	"cTWJHpsVmln+Sojdapra+DayDtnBOY65hlzS0Nq0c9hetLjZTY4Z+yQndsqqrz7eL2V3i7m08mqNmAFi",
	"jiuFlfLmI+XVGhmAZieVxT1lYqu0NmmaAc0mVJuQa8ogiVD8pc/W8PMFSp5nQ9KQ+3Xs78NJkNYqbydh",
	"xKJWs8RqnaBhvQ7iLQFmtyh9Mhx0daMGshlnm7a/tZfUg6Po/Vs0ulFeetYE6DtxH93bVu4toEd3qG+7",
	"vsaeIvMeZXbRxkExt1raOFIW99TlkWIuXZ7PotENNPNjpTDZffVSx5lI5Bz1f1tnW85a2SdFBRmGRZn3",
	"516PyMbjQOyxdmh9IaQ8hnF8eR9NvSu9f0Dsox4lDC+j2YzWnTylvp4o7d7VMpEr6OhAXdigLIkfGwn1",
	"FjTtDjG5Vuz8FwDd7X4naGbcmwXJFpR29snVS9lD9SBLHr/pRV77fb7V3r56X6n5au7T9BdI2T8DTY+t",
	"6/MfrGyoFDK/TaxTrVQx9zMF2egNiuSysTsfn0KzO8XcVOnFS3V6B724i2aWyuMzRobMIqtaCbU2cu/W",
	"xwTK7VQzpVXquVqATgW9u8rSAcG73RNqv/JQTSrMviSNbSSBRrIL+i8+1ILaeqH7hNTA0jNzyuDYKOA3",
	"Hxd/uiVXHu2iF08J45xyHr5t/BbLEEmQcYD05tqZdlH73GRaYwDV/DEYDzE/707NfyNQekv9ceNGlHle",
	"frxOLo5l9f1bIqvq8gglMoPXNa2hikdP1IXHlcJkcX+0tPVj+fF6KfuivDSqS7Gvm2o+MSJNFkOrqp9E",
	"XE4oS/Jd9X1gU+h1Usbi8zhKX2Pxid7xuOzMKvMfquoy+xLN7qDh1WJuGk0tqPdf6S3MLx6o0+O+ntNi",
	"UcL9xmuBmri52/bOoXnq9Lkw92lmMDSQTvhS2tkweWeH51UeafWb2uCmhww5ibqVranqd1kXOs7vHZi/",
	"AuP7OwfH/G2DAOiPRIEm+jPrSUb1aNLSPUZZMrS1weAVramyR//lmZPLndoet50yMNS511xc6JH5QJkV",
	"tJ8nfDKaFyaV+b1KYVn9Ka9m18rDc8rMQzS6geP6J2tkFmmWcluK8G294luz8mdwrjHTbfx634kCIV+y",
	"Hx/96BkRHf34kC1wze53Q8OmJGLXsqXsuinkpFnIt0rn4knQCp2jX1T6fOwJ7iBOuzZHmKAujzjKc6RJ",
	"EWXGqD9SpCGV+qP+Cjhsby6cdFfyXBwLVkFphg6dVPXE6XuGflcKS7pbTYU1O/3CFtW1107wIkAcMHio",
	"VU/oMJNi6aHeof8PAAD//+um7/7lVgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
