// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ArticleFormat.
const (
	Html     ArticleFormat = "html"
	Markdown ArticleFormat = "markdown"
	RichText ArticleFormat = "rich_text"
)

// Defines values for ArticleStatus.
const (
	ArticleStatusApproved      ArticleStatus = "approved"
	ArticleStatusDraft         ArticleStatus = "draft"
	ArticleStatusPendingReview ArticleStatus = "pending_review"
	ArticleStatusPublished     ArticleStatus = "published"
	ArticleStatusRejected      ArticleStatus = "rejected"
	ArticleStatusRewriteQueued ArticleStatus = "rewrite_queued"
	ArticleStatusScored        ArticleStatus = "scored"
)

// Defines values for FullTextStrategy.
const (
	FetchPage      FullTextStrategy = "fetch_page"
	RssDescription FullTextStrategy = "rss_description"
)

// Defines values for HealthDb.
const (
	HealthDbDown HealthDb = "down"
	HealthDbOk   HealthDb = "ok"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Defines values for InsightKind.
const (
	PlatformLesson InsightKind = "platform_lesson"
	SourceLesson   InsightKind = "source_lesson"
	TopicLesson    InsightKind = "topic_lesson"
	WritingLesson  InsightKind = "writing_lesson"
)

// Defines values for InsightStatus.
const (
	InsightStatusActive    InsightStatus = "active"
	InsightStatusCandidate InsightStatus = "candidate"
	InsightStatusRetired   InsightStatus = "retired"
)

// Defines values for MetricSource.
const (
	MetricSourceApi    MetricSource = "api"
	MetricSourceImport MetricSource = "import"
	MetricSourceManual MetricSource = "manual"
)

// Defines values for MetricWindow.
const (
	Custom MetricWindow = "custom"
	D7     MetricWindow = "d7"
	H24    MetricWindow = "h24"
	H72    MetricWindow = "h72"
)

// Defines values for PerformanceCaseBand.
const (
	High   PerformanceCaseBand = "high"
	Low    PerformanceCaseBand = "low"
	Normal PerformanceCaseBand = "normal"
)

// Defines values for Platform.
const (
	Wechat      Platform = "wechat"
	Xiaohongshu Platform = "xiaohongshu"
	Zhihu       Platform = "zhihu"
)

// Defines values for SourceCategory.
const (
	Kol      SourceCategory = "kol"
	News     SourceCategory = "news"
	Research SourceCategory = "research"
	Tutorial SourceCategory = "tutorial"
)

// Defines values for SourceRole.
const (
	Material SourceRole = "material"
	Signal   SourceRole = "signal"
)

// Defines values for SourceType.
const (
	SourceTypeCrawler SourceType = "crawler"
	SourceTypeManual  SourceType = "manual"
	SourceTypeRss     SourceType = "rss"
	SourceTypeRsshub  SourceType = "rsshub"
)

// Defines values for TopicStatus.
const (
	TopicStatusApproved  TopicStatus = "approved"
	TopicStatusCandidate TopicStatus = "candidate"
	TopicStatusInWriting TopicStatus = "in_writing"
	TopicStatusRejected  TopicStatus = "rejected"
	TopicStatusScored    TopicStatus = "scored"
	TopicStatusWritten   TopicStatus = "written"
)

// Defines values for UpdateInsightRequestStatus.
const (
	UpdateInsightRequestStatusActive  UpdateInsightRequestStatus = "active"
	UpdateInsightRequestStatusRetired UpdateInsightRequestStatus = "retired"
)

// Article defines model for Article.
type Article struct {
	Assets            []map[string]interface{} `json:"assets"`
	ContentMd         string                   `json:"contentMd"`
	CreatedAt         time.Time                `json:"createdAt"`
	Format            ArticleFormat            `json:"format"`
	Id                openapi_types.UUID       `json:"id"`
	LatestScore       *float32                 `json:"latestScore"`
	Platform          Platform                 `json:"platform"`
	PreviousArticleId *openapi_types.UUID      `json:"previousArticleId"`
	Status            ArticleStatus            `json:"status"`
	Title             string                   `json:"title"`
	TopicId           openapi_types.UUID       `json:"topicId"`
	UpdatedAt         time.Time                `json:"updatedAt"`
	Version           int                      `json:"version"`
	WriterAgent       string                   `json:"writerAgent"`
}

// ArticleDetail defines model for ArticleDetail.
type ArticleDetail struct {
	Article      Article             `json:"article"`
	Evaluations  []ArticleEvaluation `json:"evaluations"`
	Publications []Publication       `json:"publications"`
	Topic        Topic               `json:"topic"`
	Versions     []Article           `json:"versions"`
}

// ArticleEvaluation defines model for ArticleEvaluation.
type ArticleEvaluation struct {
	AgentRunId       *openapi_types.UUID `json:"agentRunId"`
	ArticleId        openapi_types.UUID  `json:"articleId"`
	CreatedAt        time.Time           `json:"createdAt"`
	DimensionReasons map[string]string   `json:"dimensionReasons"`
	DimensionScores  map[string]float32  `json:"dimensionScores"`
	Id               openapi_types.UUID  `json:"id"`
	JudgeModel       string              `json:"judgeModel"`
	PassThreshold    float32             `json:"passThreshold"`
	Passed           bool                `json:"passed"`
	Rationale        string              `json:"rationale"`
	RubricVersion    string              `json:"rubricVersion"`
	TotalScore       float32             `json:"totalScore"`
	VetoedDimension  *string             `json:"vetoedDimension"`
	WeightVersion    *int                `json:"weightVersion"`
}

// ArticleFormat defines model for ArticleFormat.
type ArticleFormat string

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []ArticleReview `json:"items"`
	Total int             `json:"total"`
}

// ArticleReview defines model for ArticleReview.
type ArticleReview struct {
	Article          Article            `json:"article"`
	LatestEvaluation *ArticleEvaluation `json:"latestEvaluation,omitempty"`
	PublicationCount int                `json:"publicationCount"`
	TopicTitle       string             `json:"topicTitle"`
}

// ArticleStatus defines model for ArticleStatus.
type ArticleStatus string

// CalibrationReport defines model for CalibrationReport.
type CalibrationReport struct {
	ColdStart    bool                `json:"coldStart"`
	Correlations []CorrelationResult `json:"correlations"`
	HighCases    []PerformanceCase   `json:"highCases"`
	LowCases     []PerformanceCase   `json:"lowCases"`
}

// CorrelationResult defines model for CorrelationResult.
type CorrelationResult struct {
	Coefficient *float32 `json:"coefficient"`
	Key         string   `json:"key"`
	SampleSize  int      `json:"sampleSize"`
}

// CreateMetricSnapshotRequest defines model for CreateMetricSnapshotRequest.
type CreateMetricSnapshotRequest struct {
	CapturedAt     time.Time         `json:"capturedAt"`
	Metrics        EngagementMetrics `json:"metrics"`
	SnapshotWindow MetricWindow      `json:"snapshotWindow"`
}

// CreatePublicationRequest defines model for CreatePublicationRequest.
type CreatePublicationRequest struct {
	FinalContentMd         string `json:"finalContentMd"`
	FinalTitle             string `json:"finalTitle"`
	FollowerCountAtPublish *int   `json:"followerCountAtPublish"`

	// PlatformPostId 平台侧 ID 或公开链接
	PlatformPostId string `json:"platformPostId"`

	// PublishedAt 未传时由 Core 使用当前时间
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
}

// CreateTopicRequest defines model for CreateTopicRequest.
type CreateTopicRequest struct {
	Angle           string     `json:"angle"`
	Summary         string     `json:"summary"`
	TargetPlatforms []Platform `json:"targetPlatforms"`
	Title           string     `json:"title"`
}

// EngagementMetrics defines model for EngagementMetrics.
type EngagementMetrics struct {
	Comments  *int `json:"comments"`
	Favorites *int `json:"favorites"`
	Follows   *int `json:"follows"`
	Likes     *int `json:"likes"`
	Shares    *int `json:"shares"`
	Views     *int `json:"views"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FullTextStrategy defines model for FullTextStrategy.
type FullTextStrategy string

// Health defines model for Health.
type Health struct {
	Db     HealthDb     `json:"db"`
	Status HealthStatus `json:"status"`
}

// HealthDb defines model for Health.Db.
type HealthDb string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImportMetricSnapshotsRequest defines model for ImportMetricSnapshotsRequest.
type ImportMetricSnapshotsRequest struct {
	Items []MetricSnapshotImportItem `json:"items"`
}

// ImportMetricSnapshotsResult defines model for ImportMetricSnapshotsResult.
type ImportMetricSnapshotsResult struct {
	Imported  int              `json:"imported"`
	Snapshots []MetricSnapshot `json:"snapshots"`
}

// IngestUrlRequest defines model for IngestUrlRequest.
type IngestUrlRequest struct {
	// Note 备注（为什么觉得这条值得写）
	Note *string `json:"note,omitempty"`
	Url  string  `json:"url"`
}

// Insight defines model for Insight.
type Insight struct {
	Confidence float32            `json:"confidence"`
	Content    string             `json:"content"`
	CreatedAt  time.Time          `json:"createdAt"`
	Evidence   []InsightEvidence  `json:"evidence"`
	Id         openapi_types.UUID `json:"id"`
	Kind       InsightKind        `json:"kind"`
	Platform   *Platform          `json:"platform"`
	Status     InsightStatus      `json:"status"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// InsightEvidence defines model for InsightEvidence.
type InsightEvidence struct {
	ArticleIds     []openapi_types.UUID `json:"articleIds"`
	Note           string               `json:"note"`
	PublicationIds []openapi_types.UUID `json:"publicationIds"`
}

// InsightKind defines model for InsightKind.
type InsightKind string

// InsightStatus defines model for InsightStatus.
type InsightStatus string

// JobAccepted defines model for JobAccepted.
type JobAccepted struct {
	MsgId int64  `json:"msgId"`
	Queue string `json:"queue"`
}

// MemoryReflectSchedule defines model for MemoryReflectSchedule.
type MemoryReflectSchedule struct {
	Enabled      bool   `json:"enabled"`
	LookbackDays int    `json:"lookbackDays"`
	Time         string `json:"time"`
	Timezone     string `json:"timezone"`
	Weekday      int    `json:"weekday"`
}

// MetricReminder defines model for MetricReminder.
type MetricReminder struct {
	DueAt          time.Time    `json:"dueAt"`
	Overdue        bool         `json:"overdue"`
	SnapshotWindow MetricWindow `json:"snapshotWindow"`
}

// MetricSnapshot defines model for MetricSnapshot.
type MetricSnapshot struct {
	CapturedAt               time.Time          `json:"capturedAt"`
	CreatedAt                time.Time          `json:"createdAt"`
	Id                       openapi_types.UUID `json:"id"`
	Metrics                  EngagementMetrics  `json:"metrics"`
	PerformancePercentile    *float32           `json:"performancePercentile"`
	PerformanceRaw           float32            `json:"performanceRaw"`
	PerformanceWeightVersion int                `json:"performanceWeightVersion"`
	PublicationId            openapi_types.UUID `json:"publicationId"`
	SnapshotWindow           MetricWindow       `json:"snapshotWindow"`
	Source                   MetricSource       `json:"source"`
}

// MetricSnapshotImportItem defines model for MetricSnapshotImportItem.
type MetricSnapshotImportItem struct {
	CapturedAt     time.Time          `json:"capturedAt"`
	Metrics        EngagementMetrics  `json:"metrics"`
	PublicationId  openapi_types.UUID `json:"publicationId"`
	SnapshotWindow MetricWindow       `json:"snapshotWindow"`
}

// MetricSource defines model for MetricSource.
type MetricSource string

// MetricWindow defines model for MetricWindow.
type MetricWindow string

// PerformanceCase defines model for PerformanceCase.
type PerformanceCase struct {
	ArticleId      openapi_types.UUID  `json:"articleId"`
	Band           PerformanceCaseBand `json:"band"`
	CapturedAt     time.Time           `json:"capturedAt"`
	Percentile     float32             `json:"percentile"`
	PerformanceRaw float32             `json:"performanceRaw"`
	Platform       Platform            `json:"platform"`
	PublicationId  openapi_types.UUID  `json:"publicationId"`
	SnapshotWindow MetricWindow        `json:"snapshotWindow"`
	Title          string              `json:"title"`
}

// PerformanceCaseBand defines model for PerformanceCase.Band.
type PerformanceCaseBand string

// PerformanceDashboard defines model for PerformanceDashboard.
type PerformanceDashboard struct {
	Cases     []PerformanceCase            `json:"cases"`
	Days      int                          `json:"days"`
	Summaries []PlatformPerformanceSummary `json:"summaries"`
}

// Platform defines model for Platform.
type Platform string

// PlatformPerformanceSummary defines model for PlatformPerformanceSummary.
type PlatformPerformanceSummary struct {
	Complete24h  int      `json:"complete24h"`
	Complete72h  int      `json:"complete72h"`
	Complete7d   int      `json:"complete7d"`
	HighCount    int      `json:"highCount"`
	LowCount     int      `json:"lowCount"`
	Platform     Platform `json:"platform"`
	Publications int      `json:"publications"`
	Snapshots    int      `json:"snapshots"`
}

// Publication defines model for Publication.
type Publication struct {
	ArticleId              openapi_types.UUID `json:"articleId"`
	CreatedAt              time.Time          `json:"createdAt"`
	EditRatio              *float32           `json:"editRatio"`
	FinalContentDiff       *string            `json:"finalContentDiff"`
	FollowerCountAtPublish *int               `json:"followerCountAtPublish"`
	Id                     openapi_types.UUID `json:"id"`
	Platform               Platform           `json:"platform"`
	PlatformPostId         *string            `json:"platformPostId"`
	PublishedAt            time.Time          `json:"publishedAt"`
}

// PublicationPerformance defines model for PublicationPerformance.
type PublicationPerformance struct {
	ArticleTitle string           `json:"articleTitle"`
	Publication  Publication      `json:"publication"`
	Reminders    []MetricReminder `json:"reminders"`
	Snapshots    []MetricSnapshot `json:"snapshots"`
	TopicTitle   string           `json:"topicTitle"`
}

// PublicationPerformanceList defines model for PublicationPerformanceList.
type PublicationPerformanceList struct {
	Items        []PublicationPerformance `json:"items"`
	OverdueCount int                      `json:"overdueCount"`
	Total        int                      `json:"total"`
}

// RejectArticleRequest defines model for RejectArticleRequest.
type RejectArticleRequest struct {
	// Reason 终审拒绝原因
	Reason *string `json:"reason,omitempty"`
}

// RejectTopicRequest defines model for RejectTopicRequest.
type RejectTopicRequest struct {
	// Reason 否决原因（留痕，供后续 rubric 校准参考）
	Reason *string `json:"reason,omitempty"`
}

// SchedulerSettings defines model for SchedulerSettings.
type SchedulerSettings struct {
	MemoryReflect MemoryReflectSchedule `json:"memoryReflect"`
	SourceFetch   SourceFetchSchedule   `json:"sourceFetch"`
	TopicEvaluate TopicEvaluateSchedule `json:"topicEvaluate"`
	TopicScout    TopicScoutSchedule    `json:"topicScout"`
}

// SchedulerSettingsPatch 仅传需要改的分组
type SchedulerSettingsPatch struct {
	MemoryReflect *MemoryReflectSchedule `json:"memoryReflect,omitempty"`
	SourceFetch   *SourceFetchSchedule   `json:"sourceFetch,omitempty"`
	TopicEvaluate *TopicEvaluateSchedule `json:"topicEvaluate,omitempty"`
	TopicScout    *TopicScoutSchedule    `json:"topicScout,omitempty"`
}

// Source defines model for Source.
type Source struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// SourceCategory defines model for SourceCategory.
type SourceCategory string

// SourceFetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
type SourceFetchConfig struct {
	FullText        *FullTextStrategy `json:"fullText,omitempty"`
	IntervalMinutes *int              `json:"intervalMinutes"`
	MaxAgeDays      *int              `json:"maxAgeDays,omitempty"`
	MaxItems        *int              `json:"maxItems,omitempty"`
	Role            *SourceRole       `json:"role,omitempty"`
}

// SourceFetchSchedule defines model for SourceFetchSchedule.
type SourceFetchSchedule struct {
	DefaultIntervalMinutes int  `json:"defaultIntervalMinutes"`
	Enabled                bool `json:"enabled"`
}

// SourceHealth defines model for SourceHealth.
type SourceHealth struct {
	ConsecutiveFailures int `json:"consecutiveFailures"`

	// ItemCount 该源累计入库条目数
	ItemCount     *int       `json:"itemCount,omitempty"`
	LastError     *string    `json:"lastError"`
	LastRunAt     *time.Time `json:"lastRunAt"`
	LastSuccessAt *time.Time `json:"lastSuccessAt"`
	NextRunAt     *time.Time `json:"nextRunAt"`
}

// SourceInput defines model for SourceInput.
type SourceInput struct {
	Category SourceCategory `json:"category"`
	Enabled  *bool          `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourcePatch 仅传需要改的字段
type SourcePatch struct {
	Category *SourceCategory `json:"category,omitempty"`
	Enabled  *bool           `json:"enabled,omitempty"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig *SourceFetchConfig `json:"fetchConfig,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Url         *string            `json:"url"`
	Weight      *float32           `json:"weight,omitempty"`
}

// SourceRole defines model for SourceRole.
type SourceRole string

// SourceType defines model for SourceType.
type SourceType string

// SourceWithHealth defines model for SourceWithHealth.
type SourceWithHealth struct {
	Category SourceCategory `json:"category"`
	Enabled  bool           `json:"enabled"`

	// FetchConfig 单源采集配置；intervalMinutes 为空表示沿用全局默认
	FetchConfig SourceFetchConfig  `json:"fetchConfig"`
	Health      SourceHealth       `json:"health"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         *string            `json:"url"`
	Weight      float32            `json:"weight"`
}

// Topic defines model for Topic.
type Topic struct {
	Angle           string               `json:"angle"`
	Id              openapi_types.UUID   `json:"id"`
	LatestScore     *float32             `json:"latestScore"`
	RawItemIds      []openapi_types.UUID `json:"rawItemIds"`
	Status          TopicStatus          `json:"status"`
	Summary         string               `json:"summary"`
	TargetPlatforms []Platform           `json:"targetPlatforms"`
	Title           string               `json:"title"`
}

// TopicEvaluateSchedule defines model for TopicEvaluateSchedule.
type TopicEvaluateSchedule struct {
	Enabled        bool `json:"enabled"`
	MaxConcurrency int  `json:"maxConcurrency"`
}

// TopicEvaluation defines model for TopicEvaluation.
type TopicEvaluation struct {
	AgentRunId *openapi_types.UUID `json:"agentRunId"`
	CreatedAt  time.Time           `json:"createdAt"`

	// DimensionReasons 逐维度理由
	DimensionReasons *map[string]string `json:"dimensionReasons,omitempty"`
	DimensionScores  map[string]float32 `json:"dimensionScores"`
	Id               openapi_types.UUID `json:"id"`
	JudgeModel       string             `json:"judgeModel"`
	Rationale        string             `json:"rationale"`

	// RubricVersion 如 topic@v1
	RubricVersion string             `json:"rubricVersion"`
	TopicId       openapi_types.UUID `json:"topicId"`
	TotalScore    float32            `json:"totalScore"`

	// VetoedDimension 触发一票否决的维度 key（topic@v1 暂无 veto 维度，但字段就位）
	VetoedDimension *string `json:"vetoedDimension"`

	// WeightVersion 生效权重版本（weight_sets.version），使评分可回放
	WeightVersion *int `json:"weightVersion"`
}

// TopicScoutSchedule defines model for TopicScoutSchedule.
type TopicScoutSchedule struct {
	Enabled     bool     `json:"enabled"`
	MinNewItems int      `json:"minNewItems"`
	Times       []string `json:"times"`
	Timezone    string   `json:"timezone"`
}

// TopicStatus defines model for TopicStatus.
type TopicStatus string

// TriggerMemoryReflectRequest defines model for TriggerMemoryReflectRequest.
type TriggerMemoryReflectRequest struct {
	PeriodEnd   *time.Time `json:"periodEnd,omitempty"`
	PeriodStart *time.Time `json:"periodStart,omitempty"`
}

// UpdateInsightRequest defines model for UpdateInsightRequest.
type UpdateInsightRequest struct {
	Status UpdateInsightRequestStatus `json:"status"`
}

// UpdateInsightRequestStatus defines model for UpdateInsightRequest.Status.
type UpdateInsightRequestStatus string

// WeeklyReport defines model for WeeklyReport.
type WeeklyReport struct {
	AgentRunId      *openapi_types.UUID `json:"agentRunId"`
	Calibration     CalibrationReport   `json:"calibration"`
	CreatedAt       time.Time           `json:"createdAt"`
	Id              openapi_types.UUID  `json:"id"`
	PeriodEnd       time.Time           `json:"periodEnd"`
	PeriodStart     time.Time           `json:"periodStart"`
	SampleCount     int                 `json:"sampleCount"`
	SummaryMarkdown string              `json:"summaryMarkdown"`
}

// ArticleId defines model for ArticleId.
type ArticleId = openapi_types.UUID

// InsightId defines model for InsightId.
type InsightId = openapi_types.UUID

// PublicationId defines model for PublicationId.
type PublicationId = openapi_types.UUID

// SourceId defines model for SourceId.
type SourceId = openapi_types.UUID

// TopicId defines model for TopicId.
type TopicId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	Status   *ArticleStatus      `form:"status,omitempty" json:"status,omitempty"`
	Platform *Platform           `form:"platform,omitempty" json:"platform,omitempty"`
	TopicId  *openapi_types.UUID `form:"topicId,omitempty" json:"topicId,omitempty"`
	Limit    *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListInsightsParams defines parameters for ListInsights.
type ListInsightsParams struct {
	Kind     *InsightKind   `form:"kind,omitempty" json:"kind,omitempty"`
	Status   *InsightStatus `form:"status,omitempty" json:"status,omitempty"`
	Platform *Platform      `form:"platform,omitempty" json:"platform,omitempty"`
	Limit    *int           `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPerformanceDashboardParams defines parameters for GetPerformanceDashboard.
type GetPerformanceDashboardParams struct {
	Platform *Platform `form:"platform,omitempty" json:"platform,omitempty"`
	Days     *int      `form:"days,omitempty" json:"days,omitempty"`
}

// ListPublicationsParams defines parameters for ListPublications.
type ListPublicationsParams struct {
	Platform      *Platform `form:"platform,omitempty" json:"platform,omitempty"`
	RemindersOnly *bool     `form:"remindersOnly,omitempty" json:"remindersOnly,omitempty"`
	Limit         *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int      `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListWeeklyReportsParams defines parameters for ListWeeklyReports.
type ListWeeklyReportsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// ListTopicsParams defines parameters for ListTopics.
type ListTopicsParams struct {
	Status *TopicStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int         `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreatePublicationJSONRequestBody defines body for CreatePublication for application/json ContentType.
type CreatePublicationJSONRequestBody = CreatePublicationRequest

// RejectArticleJSONRequestBody defines body for RejectArticle for application/json ContentType.
type RejectArticleJSONRequestBody = RejectArticleRequest

// IngestUrlJSONRequestBody defines body for IngestUrl for application/json ContentType.
type IngestUrlJSONRequestBody = IngestUrlRequest

// UpdateInsightJSONRequestBody defines body for UpdateInsight for application/json ContentType.
type UpdateInsightJSONRequestBody = UpdateInsightRequest

// ImportMetricSnapshotsJSONRequestBody defines body for ImportMetricSnapshots for application/json ContentType.
type ImportMetricSnapshotsJSONRequestBody = ImportMetricSnapshotsRequest

// CreateMetricSnapshotJSONRequestBody defines body for CreateMetricSnapshot for application/json ContentType.
type CreateMetricSnapshotJSONRequestBody = CreateMetricSnapshotRequest

// TriggerMemoryReflectJSONRequestBody defines body for TriggerMemoryReflect for application/json ContentType.
type TriggerMemoryReflectJSONRequestBody = TriggerMemoryReflectRequest

// UpdateSchedulerSettingsJSONRequestBody defines body for UpdateSchedulerSettings for application/json ContentType.
type UpdateSchedulerSettingsJSONRequestBody = SchedulerSettingsPatch

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody = SourceInput

// UpdateSourceJSONRequestBody defines body for UpdateSource for application/json ContentType.
type UpdateSourceJSONRequestBody = SourcePatch

// CreateManualTopicJSONRequestBody defines body for CreateManualTopic for application/json ContentType.
type CreateManualTopicJSONRequestBody = CreateTopicRequest

// RejectTopicJSONRequestBody defines body for RejectTopic for application/json ContentType.
type RejectTopicJSONRequestBody = RejectTopicRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 健康检查（含 DB 连通性）
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// 文章审阅列表（可按状态、平台、选题过滤）
	// (GET /v1/articles)
	ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams)
	// 文章详情（原稿、版本链、最新评分和发布记录）
	// (GET /v1/articles/{articleId})
	GetArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 人工终审通过（pending_review → approved）
	// (POST /v1/articles/{articleId}/approve)
	ApproveArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 文章评分历史（倒序）
	// (GET /v1/articles/{articleId}/evaluations)
	ListArticleEvaluations(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 登记一次人工发布；首次登记同时执行 approved → published
	// (POST /v1/articles/{articleId}/publications)
	CreatePublication(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 人工终审拒绝（pending_review → rejected）
	// (POST /v1/articles/{articleId}/reject)
	RejectArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId)
	// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
	// (POST /v1/ingest/url)
	IngestUrl(w http.ResponseWriter, r *http.Request)
	// Reflector 经验库
	// (GET /v1/insights)
	ListInsights(w http.ResponseWriter, r *http.Request, params ListInsightsParams)
	// 人工启用或退役一条经验
	// (PATCH /v1/insights/{insightId})
	UpdateInsight(w http.ResponseWriter, r *http.Request, insightId InsightId)
	// 原子批量导入 Client 已解析和预检查的 CSV 指标
	// (POST /v1/metrics/import)
	ImportMetricSnapshots(w http.ResponseWriter, r *http.Request)
	// 平台内表现分分布、快照覆盖和近期 high/low case
	// (GET /v1/performance/dashboard)
	GetPerformanceDashboard(w http.ResponseWriter, r *http.Request, params GetPerformanceDashboardParams)
	// 发布记录、标准快照完成度与待录提醒
	// (GET /v1/publications)
	ListPublications(w http.ResponseWriter, r *http.Request, params ListPublicationsParams)
	// 一次发布的全部累计指标快照
	// (GET /v1/publications/{publicationId}/metrics)
	ListMetricSnapshots(w http.ResponseWriter, r *http.Request, publicationId PublicationId)
	// 录入一条 24h/72h/7d 或自定义累计指标快照
	// (POST /v1/publications/{publicationId}/metrics)
	CreateMetricSnapshot(w http.ResponseWriter, r *http.Request, publicationId PublicationId)
	// 手动触发指定周期或最近七天的反思
	// (POST /v1/reflections/run)
	TriggerMemoryReflect(w http.ResponseWriter, r *http.Request)
	// 周度归因与评分校准报告
	// (GET /v1/reports/weekly)
	ListWeeklyReports(w http.ResponseWriter, r *http.Request, params ListWeeklyReportsParams)
	// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
	// (POST /v1/scout/run)
	TriggerTopicScout(w http.ResponseWriter, r *http.Request)
	// 读调度设置
	// (GET /v1/settings/schedules)
	GetSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
	// (PATCH /v1/settings/schedules)
	UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request)
	// 信源列表（含采集健康状态）
	// (GET /v1/sources)
	ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams)
	// 新增信源
	// (POST /v1/sources)
	CreateSource(w http.ResponseWriter, r *http.Request)
	// 删除信源（已采集的 raw_items 保留，仅解除订阅）
	// (DELETE /v1/sources/{sourceId})
	DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 信源详情
	// (GET /v1/sources/{sourceId})
	GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 修改信源（含启停与单独采集频率覆盖）
	// (PATCH /v1/sources/{sourceId})
	UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 立即采集该信源（不等调度）
	// (POST /v1/sources/{sourceId}/fetch)
	TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId)
	// 选题列表（按状态过滤，latestScore 倒序）
	// (GET /v1/topics)
	ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams)
	// 手动创建选题（M0 验收：空管道插入一条手动 topic）
	// (POST /v1/topics)
	CreateManualTopic(w http.ResponseWriter, r *http.Request)
	// 选题详情
	// (GET /v1/topics/{topicId})
	GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工确认选题（scored → approved）
	// (POST /v1/topics/{topicId}/approve)
	ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
	// (GET /v1/topics/{topicId}/evaluations)
	ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId)
	// 人工否决选题（candidate/scored → rejected）
	// (POST /v1/topics/{topicId}/reject)
	RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 健康检查（含 DB 连通性）
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章审阅列表（可按状态、平台、选题过滤）
// (GET /v1/articles)
func (_ Unimplemented) ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章详情（原稿、版本链、最新评分和发布记录）
// (GET /v1/articles/{articleId})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工终审通过（pending_review → approved）
// (POST /v1/articles/{articleId}/approve)
func (_ Unimplemented) ApproveArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 文章评分历史（倒序）
// (GET /v1/articles/{articleId}/evaluations)
func (_ Unimplemented) ListArticleEvaluations(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 登记一次人工发布；首次登记同时执行 approved → published
// (POST /v1/articles/{articleId}/publications)
func (_ Unimplemented) CreatePublication(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工终审拒绝（pending_review → rejected）
// (POST /v1/articles/{articleId}/reject)
func (_ Unimplemented) RejectArticle(w http.ResponseWriter, r *http.Request, articleId ArticleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动投喂 URL（刷到好东西时的一键入口，SPEC-003 §2.2）
// (POST /v1/ingest/url)
func (_ Unimplemented) IngestUrl(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reflector 经验库
// (GET /v1/insights)
func (_ Unimplemented) ListInsights(w http.ResponseWriter, r *http.Request, params ListInsightsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工启用或退役一条经验
// (PATCH /v1/insights/{insightId})
func (_ Unimplemented) UpdateInsight(w http.ResponseWriter, r *http.Request, insightId InsightId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 原子批量导入 Client 已解析和预检查的 CSV 指标
// (POST /v1/metrics/import)
func (_ Unimplemented) ImportMetricSnapshots(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 平台内表现分分布、快照覆盖和近期 high/low case
// (GET /v1/performance/dashboard)
func (_ Unimplemented) GetPerformanceDashboard(w http.ResponseWriter, r *http.Request, params GetPerformanceDashboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 发布记录、标准快照完成度与待录提醒
// (GET /v1/publications)
func (_ Unimplemented) ListPublications(w http.ResponseWriter, r *http.Request, params ListPublicationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 一次发布的全部累计指标快照
// (GET /v1/publications/{publicationId}/metrics)
func (_ Unimplemented) ListMetricSnapshots(w http.ResponseWriter, r *http.Request, publicationId PublicationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 录入一条 24h/72h/7d 或自定义累计指标快照
// (POST /v1/publications/{publicationId}/metrics)
func (_ Unimplemented) CreateMetricSnapshot(w http.ResponseWriter, r *http.Request, publicationId PublicationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动触发指定周期或最近七天的反思
// (POST /v1/reflections/run)
func (_ Unimplemented) TriggerMemoryReflect(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 周度归因与评分校准报告
// (GET /v1/reports/weekly)
func (_ Unimplemented) ListWeeklyReports(w http.ResponseWriter, r *http.Request, params ListWeeklyReportsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即跑一次选题聚合（不等调度；忽略 minNewItems）
// (POST /v1/scout/run)
func (_ Unimplemented) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 读调度设置
// (GET /v1/settings/schedules)
func (_ Unimplemented) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 改调度设置（≤ 1 个 tick 生效；重启不被环境变量覆盖）
// (PATCH /v1/settings/schedules)
func (_ Unimplemented) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源列表（含采集健康状态）
// (GET /v1/sources)
func (_ Unimplemented) ListSources(w http.ResponseWriter, r *http.Request, params ListSourcesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 新增信源
// (POST /v1/sources)
func (_ Unimplemented) CreateSource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 删除信源（已采集的 raw_items 保留，仅解除订阅）
// (DELETE /v1/sources/{sourceId})
func (_ Unimplemented) DeleteSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 信源详情
// (GET /v1/sources/{sourceId})
func (_ Unimplemented) GetSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 修改信源（含启停与单独采集频率覆盖）
// (PATCH /v1/sources/{sourceId})
func (_ Unimplemented) UpdateSource(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 立即采集该信源（不等调度）
// (POST /v1/sources/{sourceId}/fetch)
func (_ Unimplemented) TriggerSourceFetch(w http.ResponseWriter, r *http.Request, sourceId SourceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题列表（按状态过滤，latestScore 倒序）
// (GET /v1/topics)
func (_ Unimplemented) ListTopics(w http.ResponseWriter, r *http.Request, params ListTopicsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 手动创建选题（M0 验收：空管道插入一条手动 topic）
// (POST /v1/topics)
func (_ Unimplemented) CreateManualTopic(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题详情
// (GET /v1/topics/{topicId})
func (_ Unimplemented) GetTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工确认选题（scored → approved）
// (POST /v1/topics/{topicId}/approve)
func (_ Unimplemented) ApproveTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 选题的评分历史（维度分 + 理由 + rubric/权重版本，倒序）
// (GET /v1/topics/{topicId}/evaluations)
func (_ Unimplemented) ListTopicEvaluations(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人工否决选题（candidate/scored → rejected）
// (POST /v1/topics/{topicId}/reject)
func (_ Unimplemented) RejectTopic(w http.ResponseWriter, r *http.Request, topicId TopicId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameter("form", true, false, "platform", r.URL.Query(), &params.Platform)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "topicId" -------------

	err = runtime.BindQueryParameter("form", true, false, "topicId", r.URL.Query(), &params.TopicId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveArticle operation middleware
func (siw *ServerInterfaceWrapper) ApproveArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticleEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListArticleEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticleEvaluations(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePublication operation middleware
func (siw *ServerInterfaceWrapper) CreatePublication(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePublication(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectArticle operation middleware
func (siw *ServerInterfaceWrapper) RejectArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "articleId" -------------
	var articleId ArticleId

	err = runtime.BindStyledParameterWithOptions("simple", "articleId", chi.URLParam(r, "articleId"), &articleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "articleId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectArticle(w, r, articleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestUrl operation middleware
func (siw *ServerInterfaceWrapper) IngestUrl(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestUrl(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInsights operation middleware
func (siw *ServerInterfaceWrapper) ListInsights(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInsightsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", r.URL.Query(), &params.Kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameter("form", true, false, "platform", r.URL.Query(), &params.Platform)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInsights(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateInsight operation middleware
func (siw *ServerInterfaceWrapper) UpdateInsight(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "insightId" -------------
	var insightId InsightId

	err = runtime.BindStyledParameterWithOptions("simple", "insightId", chi.URLParam(r, "insightId"), &insightId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insightId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateInsight(w, r, insightId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportMetricSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ImportMetricSnapshots(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportMetricSnapshots(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPerformanceDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetPerformanceDashboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPerformanceDashboardParams

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameter("form", true, false, "platform", r.URL.Query(), &params.Platform)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", r.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerformanceDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPublications operation middleware
func (siw *ServerInterfaceWrapper) ListPublications(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicationsParams

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameter("form", true, false, "platform", r.URL.Query(), &params.Platform)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "remindersOnly" -------------

	err = runtime.BindQueryParameter("form", true, false, "remindersOnly", r.URL.Query(), &params.RemindersOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remindersOnly", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPublications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMetricSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListMetricSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "publicationId" -------------
	var publicationId PublicationId

	err = runtime.BindStyledParameterWithOptions("simple", "publicationId", chi.URLParam(r, "publicationId"), &publicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publicationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMetricSnapshots(w, r, publicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMetricSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateMetricSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "publicationId" -------------
	var publicationId PublicationId

	err = runtime.BindStyledParameterWithOptions("simple", "publicationId", chi.URLParam(r, "publicationId"), &publicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publicationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMetricSnapshot(w, r, publicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerMemoryReflect operation middleware
func (siw *ServerInterfaceWrapper) TriggerMemoryReflect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerMemoryReflect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWeeklyReports operation middleware
func (siw *ServerInterfaceWrapper) ListWeeklyReports(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWeeklyReportsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWeeklyReports(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTopicScout operation middleware
func (siw *ServerInterfaceWrapper) TriggerTopicScout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTopicScout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedulerSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedulerSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedulerSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSources operation middleware
func (siw *ServerInterfaceWrapper) ListSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSourcesParams

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", r.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSource operation middleware
func (siw *ServerInterfaceWrapper) CreateSource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSource operation middleware
func (siw *ServerInterfaceWrapper) UpdateSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSource(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSourceFetch operation middleware
func (siw *ServerInterfaceWrapper) TriggerSourceFetch(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceId" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "sourceId", chi.URLParam(r, "sourceId"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSourceFetch(w, r, sourceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopics operation middleware
func (siw *ServerInterfaceWrapper) ListTopics(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTopicsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateManualTopic operation middleware
func (siw *ServerInterfaceWrapper) CreateManualTopic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateManualTopic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopic operation middleware
func (siw *ServerInterfaceWrapper) GetTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveTopic operation middleware
func (siw *ServerInterfaceWrapper) ApproveTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTopicEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListTopicEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTopicEvaluations(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectTopic operation middleware
func (siw *ServerInterfaceWrapper) RejectTopic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "topicId" -------------
	var topicId TopicId

	err = runtime.BindStyledParameterWithOptions("simple", "topicId", chi.URLParam(r, "topicId"), &topicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topicId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectTopic(w, r, topicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles", wrapper.ListArticles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles/{articleId}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/approve", wrapper.ApproveArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/articles/{articleId}/evaluations", wrapper.ListArticleEvaluations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/publications", wrapper.CreatePublication)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/articles/{articleId}/reject", wrapper.RejectArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/ingest/url", wrapper.IngestUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/insights", wrapper.ListInsights)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/insights/{insightId}", wrapper.UpdateInsight)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/metrics/import", wrapper.ImportMetricSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/performance/dashboard", wrapper.GetPerformanceDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/publications", wrapper.ListPublications)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/publications/{publicationId}/metrics", wrapper.ListMetricSnapshots)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/publications/{publicationId}/metrics", wrapper.CreateMetricSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/reflections/run", wrapper.TriggerMemoryReflect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/reports/weekly", wrapper.ListWeeklyReports)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/scout/run", wrapper.TriggerTopicScout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/settings/schedules", wrapper.GetSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/settings/schedules", wrapper.UpdateSchedulerSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources", wrapper.ListSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources", wrapper.CreateSource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/sources/{sourceId}", wrapper.DeleteSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/sources/{sourceId}", wrapper.GetSource)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/sources/{sourceId}", wrapper.UpdateSource)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/sources/{sourceId}/fetch", wrapper.TriggerSourceFetch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics", wrapper.ListTopics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics", wrapper.CreateManualTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}", wrapper.GetTopic)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/approve", wrapper.ApproveTopic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/topics/{topicId}/evaluations", wrapper.ListTopicEvaluations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/topics/{topicId}/reject", wrapper.RejectTopic)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963PT1rb4v6LR73z43TkGhwCH23y6NMC53JaWSdLTD5xcRrF3bDWy5EpyAuVmxoE8",
	"HMgLSAgk4RFKSMrDAdpCSBwyc/+U4i3Zn/wv3JG2HlvS1sOxndLp+QSx93O919prLV+hE0ImK/CAlyW6",
	"4wqdZUQmA2Qg6n+dFGU2wYGzSe0Plqc76Cwjp+kYzTMZQHfQjPV9jBbB9zlWBEm6QxZzIEZLiTTIMNrE",
	"fkHMMDLdQedyrDZSvpzVJkuyyPIpeng4Rp/lJTaVln33Ya3vG9vnfK6PYxOMzAq8715Zx5jG9usWcmLC",
	"H3yS+XVju/QIWTbhu4lsfNvIHsPaZCkr8BLQ6eJzJtkFvs8BSdb+Sgi8DHj9v0w2awIv/p0k8Npn9jZ/",
	"EUE/3UH/v7hNc3H0rRQ/LYqCiLZKAikhslltEbqDrmy+U15frd5/oPy8QA/H6E6B7+fYxAHsXN6agbu3",
	"4eS0ev2tkh+B42/UZyO1UgE+NY6DPld+HansvviYH6lOTMO56fLeqrI99zE/Aq8/rFzbhe/ewJEVdX6j",
	"VprUjv+VIJ8RcnzyAAD366iyPVfemoYv78KVDZ1UjEkYb+tMLwpZIMosQi4jSQAJA1YGGfRRMslqqzLc",
	"eWwooiKDVoS+70BC1m5ofMCIInNZ+9u45Tn9yi7KitEJETAySJ6UHXSYZGRwSGYzwEuMMWtUMFyM+51B",
	"g4djNJuMQOoxmmNkIMndCUHUYZNhLrGZXIbuONLWFqMzLI/+aovRfI7jmD4Ngg5A8LlMHxC1lbIcI2vb",
	"hZ30vDlOmyOCQVbISQ7J6z6zz872HSSZkXNSRAh1o8Ea5lgZEYRnQdkWMaEAzGWT9WJ0EIgSi4jegvAR",
	"axzLyyCFQDoksjIQT6YMrvHKQlvGXaDR8SzxZ6HD3o8Eb4u+THjgFBwzucN5FAviTvLBqRuHSy+Ba4wD",
	"nAIyw3IEprS5NQJKtQXBIMPldIHi5OUI009bU0n8jCnI6Ctjmpe0po6lsDV0PYeRS9338u7sohgTyuaB",
	"sK2cAHVBIQChGCy9SNWIpyvH75PLmSAZ0QxBm2QzgNeu3wUYyYA3WRWQRIYbINZqOnMELoYJXafM9chY",
	"zy4Rpfx3uWQKnBOSgCMePstIUk9aBFJa4JLBasAr9jURgSu7PkHgAKPTvcig65KlrJjrE9nEP2xhSJDD",
	"MsNF0E2eQw0CWQDJUyYKtNmh9DUENKMbO47PDEs+k+Svw0Vw3M+9gZdCCBToAAEOTwdKvfd1o9RCUwzn",
	"QpxLAnj6jGWAAF4D+AU6w4gDSWFI2yctZ7QDiGwifVEGl/CFbNAaC33JIgvaKRYskVaPbOsCgywYIstW",
	"meEcqrUtHHX6zubcAFAY2zZBXyHF6RSXdesqTCp3CjlkJARd2xD0PT6GT7B66DHMA8+mAfDqtiwzk3SS",
	"ItOvWxAaSSM3TTctLn6fAzn9gyzgkyyfuigiWMc0Z0EUBtF32t5S2piobQaSRIrrZDi2D7FLF8gKIoHu",
	"EgKX7JYZUSbLroQgioCrU+932pO6gJTjiB5Cmk2lOxkJ1GFOAFEX8XwCaBNJi3LCUJPXdFGDDS4XbPAL",
	"YecgUYUXPASsgP5+NsEaJq8t8zGJf+hIBHdkAFwm6hSJyWQ50M3+AOoUEtqCjukxx2GJ99XF6zkgi2yi",
	"m2eyUlqQsUiC6+ZMVs6J9ZksGX3pUFyf5lNMCmQ0o96YoAHCONC3LJ8UhsKWQBONsW7QuJaK4XexD+kP",
	"Icxc9gVPP8szXCfuXGdY/kvAp+Q07j1hfrM2wRJ1YYMFjhOGgKhLtJPyeSRn3BQSZhHYXtd5QTLie84o",
	"BXz/M5x9Vf6wTp09RSmFO3DsBSzlq7c/KDNrdCzslJb4QzTiXFpZeVYuPVIW36rzr6lOQQRUeXdPnd9A",
	"QR1l8W118Rfb3QskLBd6XZdygDbmRow/lnWHxhe/DJ/ysROlXCbDiGRulhkxBWQzpFCH9MOCEBmWP4vm",
	"HCGYE5EIyAUw05NGd7Jv4D0vCVpebiVIyUzGjGHXR6D9zKCg6dv9TNV5ZB8TOXZgP/tJaUbczzzNbKh7",
	"mguDaA3z6DjYYjbwrSPasCHiUw9ZEnCYJNN7BkgSk4pgoOkr2ONJe5/JcVwPuCR3yyIjg9Rl3BQTJeki",
	"LkJidD+QE+mLWedi9sH+EzCcnPbeJNmHLysMaJ6M5h30BsbqsPG9YQxlxZuSfcRrns1oNp5T0Uq+oqY+",
	"j8O5KtpJkxc6qphLhug4bvikfpKE6HHUcRWytcTqg0EyPJRoquj93jvUPrSOgu9FvCCfApL8jcj54ocX",
	"ZEBQnU8mlJ83aqVCeWu7vJMvvy9U1ifhh8XK3j3l/irMl+CHRTh+r1aaJIZpRc4ZKRHZUL2nzSHfQH+f",
	"I7E0388mAZ8AvrYrKVqBPYw0I44FBu0zRMK0cZ/T5rwwnRgx6DTAonefCFt/oQ11vSEwHPd1P91xIaoi",
	"73UL+cgvA8Yh7JeBumP6pFCQfn1HHN7EM4aiGE4zWFw9eiTdjTy/2MTZpJP1Q9HnxrrJlVFsVPNBuaEt",
	"yeEIbVHPLsbpAuDzhUGMptbRQxoXOSBJKDYnsjLLp+wPTLTZn6Dna/Nvkm5z0hG2WYLhk6yGRM0mTMjs",
	"oB7MA7J+NdJK/yX0nUwkQNYQ7U6EZqSUKwjO8vLfjtEksa9HVcItCTQsZixNAuM5kBHEy12gnwMJuTuR",
	"Bskc6TUV8Br/+YSDOUEY6GMSA6eYy86492d4PJeovnS20xM2ZBmImjr47/9/oe1I74W2Q5/1/k/7hbZD",
	"R3v/reNC26Hj6KO/EMmLzYAfBD4KFQ8BMJBkLjtOeSL4kC6QmpCw1zJugZ3DBRIy3DUt3AUyLJ8EBCsy",
	"mQP16AZhEIhJB0Vg+GllRACd0z6A/10ti6MpEZJ96M+I6q2R2EvWDr6dB2IC8DLLNfz+bq/ZxQz5BLeI",
	"w791v3wE82LWnVYUCqpGCMsUvBHNVTSWqJDdqU6OIJWHYE30Wvt7IOyHxgDYhr24+Poake2hoJDjcMzN",
	"UfWi0h0Yckz3XqjXvpKFQ/sNic8xHB0zHAc9zs8SlaGDHrAV0u2azkufaNfEywkNtjlJFjLENdzRbn8r",
	"KRJB9zFOayLNpvQcNG0eh6LgxGPsR4JlIwqIhgXCfvJ3DlgUyNFertycjr/KYva4Gabz8H7Wh5kR1zvk",
	"hk4JJFbGKO4UI6X7BEZMklRak9+BkqZtZaL6BDEaoAckWVB/wBQ7QrcR1Qwz3PUj4XvGjGsTwYZRocld",
	"l1hGSAt8Skrn6Bj9Q5rV/x0CiTRDfm8OOCwplJrlgAzaj6XDn0/NwSfa6xmcDB+rP6FFe8LlhKGIIxvk",
	"aCl8B0dUqY63NIwJHRviK8YcqHHC3gFcHHoYeIjUheVlNagC9hOYSbJyl7Z5UHQo1M7D31tOsf39kZJb",
	"mvW+FdE23hfleZ7OQm/leg/bb6TGRz14nr3w7Qh4wBHsC/EwCxCjUEx6+RJrj28Oa9ZJ6nVkK4qGs1lv",
	"qNhyUglqqfnh5/pyWXBoxJzAc6W34ALIhkR0VDUjycmHCAgwMNzpyNk/jeZGuXYkgaVLz8uxEqZ8Yvyi",
	"nuHmjfKrOwVYXFVu3FJ37sOZh3D5EZGHfXYNfmL22xPOPYXjP6PdaqWCunBPXVyolabKH5bh3Iy685JC",
	"qXyU8mgVTozD2auV/DXiOwPpZGawTOwGsszyKcJzbgYProUzBikSZ/nJZ4CcSIet0W0PxVfQGcFIMQOR",
	"8pPNwZ5VuhNCTo60hD7Snu8OJGGXciztPm3MBcXeKKg4zxjAcpXC7IyVS4+qK/nK0xFl/r26NAoL4+rO",
	"qJ5B/y/E+SLOC3DL7Xe7PTJICcgcD79upzlas6GCAsz6+3WnwPezqToAaUyIbt2gUrPQGDL6IMoxerSR",
	"9iNlxFTlOt4YSVaPfgtjJNo6ZuPF2iOGBbJx8Pb6YrsTw63pwfEom0IEEmBExMk5WRBZXaMMCBzRi/Oi",
	"yCu5pxeU7bnqxER1ebw6Nq3uFmulZU2TiYMMd47lczKQqPLWtvrTdmV1Q32yrbzRU6LGNuDrfHXnbqX4",
	"xMPT/UbKRBjqPKkVGgE5t3YHbP4dD9kcj2JvZ5hLJ1PA82By9G/Hw15M7NQEbN7xttCXFlHgIlJtlxDM",
	"9k4p5X25AP1MjpPP1gcy74EDJILvk4zP3v5E7Zf6khB4CSRyMjsIzjAslyMkLBGcKBlkLIvNXf65pmzP",
	"qb9sVoqrcGwNbt9W7q+qy0Vl4RUdCwsMMJJs5RqFyhBtdFeOD/CcIi3RnUskgCQ1sgwPLjV2Ek9alBcn",
	"/pg9y2dzcos0lEFmrmM3UWF9QprIumvb4eOxfeolp0qyUOCPvOj228tFpfirR9Z/onZIRLS20lzwAXiX",
	"oR3sVxwZGGpcYlM8E6TJewwqxPIPNZtAktK5Pk24mQ9CCZEZ4oAYsNK3rJy2JXK0hzHzZdDzBpa2Fgqf",
	"bmzqpltjCfIDWI9Z7Bk13/nAK7dFZkgzFRrOEIqWbYV8ByvX6tPI7o5SWu2b1I3Bz3tmn2JpkkwjO2b1",
	"5dhkmEudAp/IiSLgE878laPt+0xgca0ZdvRWFP8edDmvU59U83Pqzi9w+6k6N67Ov6b/4OW+dZblulyu",
	"p1cpPVDwH4NHiEKhjt4JzazvddnR60/h7M3yVl5d20DhPXVpFOGQGgCXa6WCeQdKWbqqLD6itCUpNKJW",
	"mirvjiOTAb56Xd6dRsG++kuIXbHN+YfKQkG5f606Ma1OFpSVF7VSAc25KAFZOmyU39dKk/oR9iqbo7Aw",
	"Dmc34fIDZf4DHdtXTTLWEqfuiuRo5cfBTxqEYFGdMo3lvwJDXm/2SJsPobgSB52Ko6EUQturbj8Wqlsi",
	"Zhv6yl10dke+IA4Kf1gHJqBalbdYXS3LXzQyYI1cWBnwYSW2PSKbSgHREdX0Db1ngcgKydN8sq68F1aw",
	"K3QjPu55IPKNnj1tpOb6ns9blhIhT5dcpEJCy7cADHCX/SqRG9WNdq1zaH2ypyy6pSmSB4N1syg34iOY",
	"YbedM3sYRLP+8HPhF3Nu7l3diZ462i8M6+HEfsGrRqREWuAYUTrEsFR5awleX1UebcG9a1TX6e4e6uT5",
	"sxRcu6lqaqxwro2qPttQHrytlaaqS7PViSl144b6+KYy+RN8vVArTX7MX/0nD4sPyru31Z3byoNRzVee",
	"Xihv5cvbN2DxgXJ/TdmeU+5uUocPW1RkHuAw+uDwd5LAU7/l53/Lz1PKygvlzkR5521566W6NPpPHo2h",
	"lLubcOytfrrK+jhc/lArLZe3nlTyY+WtfGXiFyW/rtetnqWq+Tnl5Vrl6bi6fKdWKlTWR8o7t+H2barr",
	"9MlT505TsJRX5j9UF4vVx3fNG1jmuQWdQ5qU07bD+h910G2Hjxxu099Ns4BnsizdQR893Hb4qN4gQ07r",
	"3BhH3twP2v9TQCcojVmtJDf670A2/EBXn7j2tram9TmzPE2PMfr1F6i3mek30XBkDW6/U37MKw/XaqUC",
	"nHtOnfqcquw9qOaXlPy63oltOEbHB4/EjYdvyfduX7KS+XSrl1lg/REvGP32vs8B3esxu/qZ3k20e7m6",
	"cGnuOGlVLA0j2rq2y+e3pG0G1dFtkLwUx2ZY2bGQFf063oYFv9rDwu1+Gwj9/RLw2SHE5BnubSFV4o1c",
	"fEgzRh9DG5LWsQ4Wx3oqOqlZuTOhPn8Ei6vVu2OwsFhZ3dBoenZTmZpEDQg/5kdQFf3H/Eg1P1l9fLey",
	"N6HsPCHRefyKldszHMTPJ61WJy6KJ13CHhK3+6gdBNiNbmkBgD8WDnirIyMJ7JXNp8q1MQ3gMw/Vjb2P",
	"+RHkp1Rvf/iYH1FW8sqdV4ZTcmsKzt6EW9cqxVdwdyEM+HHD2NSNH0EiYOEkGvDHwETTcKBN+Cx8gtUF",
	"1Im08vY2fLeGUmaq+aXK3kStVHD2z6F+G79FmZZ+KJZcXfTCVMRpZ4+43wthzWr210q+0nlmZhzOvtG4",
	"K38Lbs+GYsOdi0tmHE8LlYZRoYvlz4Xk5aaxjW+bl2GnsW2U7bqo4UjTzuHIdPSiGx0zuS8ldsCsr97b",
	"qRRflbfyyotVJAaQOK6VlqtP7ygvVtEAODelLL5VJtcrq1OWGNBlgt1KK5AGUQjAn/oc2X6fIOURsxGH",
	"vT2e/xxKAuVVkpWEGezBxRKr92qIGw+NZAqw+jnQrcGgp19EJJnR3rT98VpsAkbhuzdwbK1692ETTN/J",
	"G/D6hnJ9Ad65Sn3T9aWmKQrvYOEVXNstb61U1vaUxbfq0mh5K1+dL8KxNTj7Y6001X3+dOehtraj1P+u",
	"tx9ud6JPj3oF6/Kz5qBI7p7R1SAq6rDuDn6+Tp0OpKtZwwE6kAFeH3qxiO72HYjFY7YpqcPOaYR6jRCw",
	"IFLqzmz12RTcvu0hxPgV67cNho1YPMrfcJKlI2Zbt1Kxf16hVUqFGFOOJJbamigWDey2wmo1LIq5TXV+",
	"QyncqebzcPe9ZmzcX0XItTBrlEnHjSpefy1BamvUKo0R1A3qgC3OoHZOf2wLFM48hC/nlMn31YlZuFmC",
	"Y2tUJ8cCXqbguzeV9R+VB3Pw1lT18SiKTKpLo1Rn9z8oZWpCeTRh0Q9WXRtP4nWyfqEaYl1tJNXVApVg",
	"lrZ6NcJnuEJwpuueOOCgHRFiLVICKDIHx8cqqxvqzCvN6S2Mw61rH/MjcO+5OraO4vrw1lRl76ay8pBK",
	"s6l0nBOGqIRe0GxShcvz9TVezjurR38fKrDKxL7muctkcuhnOImQAfqvAHOkyrdWxpvxKObH/IjyaAJO",
	"jCNahcUppTAHt5+Wt2bghzG4u6DMzlXHbxHJNH7F0XVgOI71h/ElX68+rM/Ucf7C08GYlaF9AVthj+hx",
	"DoQqdWkUjm1Ur22gLHmkTxDC9AfkgCCZ6+jNgHarYmU+HVwO1nhxo/qPba/sLsCxNWTEUu3H0vET7en4",
	"iSSlFO5UJp7B4lL5/SSJpAxeF5F7o7O6mOP9LV1SXkyLDN2gFBxijOuPGxVBCX3K1AQsLsGbG8rKQ6Vw",
	"R1nJV/ZulreuwSc/aWJhdlrJ38cwppneUnxIT74JlMN4fk5EOyIoGtCOqejj7Z9CLMCRgBRRZDu55+YG",
	"3H4Kd2/B5UflrRn0oIHqoZXra/DmdQvsUkLIyZFYpAev5v1EKLWBiPzzG3D658q7m0hZGU/TI0twrqA3",
	"rZ1WX05WXl3T80uX4d6uurBGYel8eNxOMsqT9Tskc0EJG38HsrfAvIUGmnezKNRT2dxBV68UP6i7RfS7",
	"QQGhH/KVmi9AfQrCDziUExmmDYvS+fc4Gmqlwm+TT6gjVHnrGSWziQEKZSjXSsv6jztulremK4+fqzOb",
	"8PE1OHu3OjFrpmVhtKoXxgSbud3GmEiC1c5/taHn8ZsORGh6io32IzjRD2TamSxzz1G5MsraQiktxo9l",
	"Bpmu3WYTwpawAVYJecAmptWwsemm5f4luXLnFXz8ACHOTefxK+bP2A4jnc8B1HHBibRT+ucW0urzM6zf",
	"0SWQ+TFvPuhXAmW0IWrUzYKFR9V7T9DFNVp99wbRqro0SonM0EWda6jy3n114V6tNFXeGaus/1i996RS",
	"fFy9O2ZQsa+aaj4w2ppMhjirt8SN1SGLkqzCdWBT4NUqYfH7KEpfYbFP7dgoOovK/HubXeaew7lNOLJS",
	"3pqB0wvqjRdGY4rHN9WZCV/NiUmUeL/ZAybQbu529MRpHjv9Xjb3QabN6EY6wktlc83CndM8t3GkJw0H",
	"Gzc9aEgrkqUdpbJ/ylhxI13UrB/Q9f2JyAZ/FjKC9Ye8QMv6s5KYzZTlKawmmMLSAkPimHqpfI/xo72t",
	"C0I62qkdsGFoYK+5diEhsAQLy3BnG+HJrJiZUubf1kpL6k/banG1OnJbmb1lhQ7RLFQC65UU8StGmUFg",
	"urmJufpEd49RwNBSQ8gX7I1bP0ZExLB+fMAWOVH8TwPDpmT/rRYrxScWkaMSUN/UcA9OoqaFu7oASL8f",
	"eqIriINOCEdIUJdGXTnhqPQcFsapv1KozQD1V6PvZNxZMj7lTR/3YCxa2m4zeKhVKbtu3TP8p2JY1LPA",
	"YlirfjuOsa4zYVdbBIiDJg71lF06zmRZerh3+P8CAAD//2Ov0v34iAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
