// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
select count(*)
from articles a
where a.status = coalesce($1::article_status, a.status)
  and a.platform = coalesce($2::platform, a.platform)
  and a.topic_id = coalesce($3::uuid, a.topic_id)
`

type CountArticlesParams struct {
	Status   NullArticleStatus `json:"status"`
	Platform NullPlatform      `json:"platform"`
	TopicID  uuid.NullUUID     `json:"topic_id"`
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles, arg.Status, arg.Platform, arg.TopicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublication = `-- name: CreatePublication :one
insert into publications (
    article_id, platform, platform_post_id, published_at,
    final_content_diff, edit_ratio, follower_count_at_publish
) values (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
returning id, article_id, platform, platform_post_id, published_at, final_content_diff, follower_count_at_publish, created_at, edit_ratio
`

type CreatePublicationParams struct {
	ArticleID              uuid.UUID          `json:"article_id"`
	Platform               Platform           `json:"platform"`
	PlatformPostID         pgtype.Text        `json:"platform_post_id"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	FinalContentDiff       pgtype.Text        `json:"final_content_diff"`
	EditRatio              pgtype.Numeric     `json:"edit_ratio"`
	FollowerCountAtPublish pgtype.Int4        `json:"follower_count_at_publish"`
}

func (q *Queries) CreatePublication(ctx context.Context, arg CreatePublicationParams) (Publication, error) {
	row := q.db.QueryRow(ctx, createPublication,
		arg.ArticleID,
		arg.Platform,
		arg.PlatformPostID,
		arg.PublishedAt,
		arg.FinalContentDiff,
		arg.EditRatio,
		arg.FollowerCountAtPublish,
	)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Platform,
		&i.PlatformPostID,
		&i.PublishedAt,
		&i.FinalContentDiff,
		&i.FollowerCountAtPublish,
		&i.CreatedAt,
		&i.EditRatio,
	)
	return i, err
}

const getArticle = `-- name: GetArticle :one
select id, topic_id, platform, version, format, title, content_md, assets, writer_agent, status, latest_score, created_at, updated_at, previous_article_id, correlation_id from articles where id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Platform,
		&i.Version,
		&i.Format,
		&i.Title,
		&i.ContentMd,
		&i.Assets,
		&i.WriterAgent,
		&i.Status,
		&i.LatestScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousArticleID,
		&i.CorrelationID,
	)
	return i, err
}

const getArticleForUpdate = `-- name: GetArticleForUpdate :one
select id, topic_id, platform, version, format, title, content_md, assets, writer_agent, status, latest_score, created_at, updated_at, previous_article_id, correlation_id from articles where id = $1 for update
`

func (q *Queries) GetArticleForUpdate(ctx context.Context, id uuid.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleForUpdate, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Platform,
		&i.Version,
		&i.Format,
		&i.Title,
		&i.ContentMd,
		&i.Assets,
		&i.WriterAgent,
		&i.Status,
		&i.LatestScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousArticleID,
		&i.CorrelationID,
	)
	return i, err
}

const latestArticleEvaluation = `-- name: LatestArticleEvaluation :one
select id, article_id, rubric_version, dimension_scores, dimension_reasons,
       total_score, rationale, judge_model, agent_run_id, weight_version,
       vetoed_dimension, pass_threshold, passed, created_at
from article_evaluations
where article_id = $1
order by created_at desc
limit 1
`

type LatestArticleEvaluationRow struct {
	ID               uuid.UUID          `json:"id"`
	ArticleID        uuid.UUID          `json:"article_id"`
	RubricVersion    string             `json:"rubric_version"`
	DimensionScores  []byte             `json:"dimension_scores"`
	DimensionReasons []byte             `json:"dimension_reasons"`
	TotalScore       pgtype.Numeric     `json:"total_score"`
	Rationale        string             `json:"rationale"`
	JudgeModel       string             `json:"judge_model"`
	AgentRunID       uuid.NullUUID      `json:"agent_run_id"`
	WeightVersion    pgtype.Int4        `json:"weight_version"`
	VetoedDimension  pgtype.Text        `json:"vetoed_dimension"`
	PassThreshold    pgtype.Numeric     `json:"pass_threshold"`
	Passed           bool               `json:"passed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestArticleEvaluation(ctx context.Context, articleID uuid.UUID) (LatestArticleEvaluationRow, error) {
	row := q.db.QueryRow(ctx, latestArticleEvaluation, articleID)
	var i LatestArticleEvaluationRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.RubricVersion,
		&i.DimensionScores,
		&i.DimensionReasons,
		&i.TotalScore,
		&i.Rationale,
		&i.JudgeModel,
		&i.AgentRunID,
		&i.WeightVersion,
		&i.VetoedDimension,
		&i.PassThreshold,
		&i.Passed,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleEvaluations = `-- name: ListArticleEvaluations :many
select id, article_id, rubric_version, dimension_scores, dimension_reasons,
       total_score, rationale, judge_model, agent_run_id, weight_version,
       vetoed_dimension, pass_threshold, passed, created_at
from article_evaluations
where article_id = $1
order by created_at desc
`

type ListArticleEvaluationsRow struct {
	ID               uuid.UUID          `json:"id"`
	ArticleID        uuid.UUID          `json:"article_id"`
	RubricVersion    string             `json:"rubric_version"`
	DimensionScores  []byte             `json:"dimension_scores"`
	DimensionReasons []byte             `json:"dimension_reasons"`
	TotalScore       pgtype.Numeric     `json:"total_score"`
	Rationale        string             `json:"rationale"`
	JudgeModel       string             `json:"judge_model"`
	AgentRunID       uuid.NullUUID      `json:"agent_run_id"`
	WeightVersion    pgtype.Int4        `json:"weight_version"`
	VetoedDimension  pgtype.Text        `json:"vetoed_dimension"`
	PassThreshold    pgtype.Numeric     `json:"pass_threshold"`
	Passed           bool               `json:"passed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListArticleEvaluations(ctx context.Context, articleID uuid.UUID) ([]ListArticleEvaluationsRow, error) {
	rows, err := q.db.Query(ctx, listArticleEvaluations, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleEvaluationsRow
	for rows.Next() {
		var i ListArticleEvaluationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.RubricVersion,
			&i.DimensionScores,
			&i.DimensionReasons,
			&i.TotalScore,
			&i.Rationale,
			&i.JudgeModel,
			&i.AgentRunID,
			&i.WeightVersion,
			&i.VetoedDimension,
			&i.PassThreshold,
			&i.Passed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlePublications = `-- name: ListArticlePublications :many
select id, article_id, platform, platform_post_id, published_at, final_content_diff, follower_count_at_publish, created_at, edit_ratio from publications
where article_id = $1
order by published_at desc, created_at desc
`

func (q *Queries) ListArticlePublications(ctx context.Context, articleID uuid.UUID) ([]Publication, error) {
	rows, err := q.db.Query(ctx, listArticlePublications, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publication
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.PlatformPostID,
			&i.PublishedAt,
			&i.FinalContentDiff,
			&i.FollowerCountAtPublish,
			&i.CreatedAt,
			&i.EditRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleVersions = `-- name: ListArticleVersions :many
select id, topic_id, platform, version, format, title, content_md, assets, writer_agent, status, latest_score, created_at, updated_at, previous_article_id, correlation_id from articles
where topic_id = $1 and platform = $2
order by version desc, created_at desc
`

type ListArticleVersionsParams struct {
	TopicID  uuid.UUID `json:"topic_id"`
	Platform Platform  `json:"platform"`
}

func (q *Queries) ListArticleVersions(ctx context.Context, arg ListArticleVersionsParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticleVersions, arg.TopicID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Platform,
			&i.Version,
			&i.Format,
			&i.Title,
			&i.ContentMd,
			&i.Assets,
			&i.WriterAgent,
			&i.Status,
			&i.LatestScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreviousArticleID,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
select a.id, a.topic_id, a.platform, a.version, a.format, a.title, a.content_md, a.assets, a.writer_agent, a.status, a.latest_score, a.created_at, a.updated_at, a.previous_article_id, a.correlation_id, t.title as topic_title,
       (select count(*) from publications p where p.article_id = a.id) as publication_count
from articles a
join topics t on t.id = a.topic_id
where a.status = coalesce($1::article_status, a.status)
  and a.platform = coalesce($2::platform, a.platform)
  and a.topic_id = coalesce($3::uuid, a.topic_id)
order by a.updated_at desc, a.id
limit $5 offset $4
`

type ListArticlesParams struct {
	Status   NullArticleStatus `json:"status"`
	Platform NullPlatform      `json:"platform"`
	TopicID  uuid.NullUUID     `json:"topic_id"`
	Off      int32             `json:"off"`
	Lim      int32             `json:"lim"`
}

type ListArticlesRow struct {
	ID                uuid.UUID          `json:"id"`
	TopicID           uuid.UUID          `json:"topic_id"`
	Platform          Platform           `json:"platform"`
	Version           int32              `json:"version"`
	Format            ArticleFormat      `json:"format"`
	Title             string             `json:"title"`
	ContentMd         string             `json:"content_md"`
	Assets            []byte             `json:"assets"`
	WriterAgent       string             `json:"writer_agent"`
	Status            ArticleStatus      `json:"status"`
	LatestScore       pgtype.Numeric     `json:"latest_score"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PreviousArticleID uuid.NullUUID      `json:"previous_article_id"`
	CorrelationID     uuid.NullUUID      `json:"correlation_id"`
	TopicTitle        string             `json:"topic_title"`
	PublicationCount  int64              `json:"publication_count"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Status,
		arg.Platform,
		arg.TopicID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesRow
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Platform,
			&i.Version,
			&i.Format,
			&i.Title,
			&i.ContentMd,
			&i.Assets,
			&i.WriterAgent,
			&i.Status,
			&i.LatestScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PreviousArticleID,
			&i.CorrelationID,
			&i.TopicTitle,
			&i.PublicationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
