// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activePerformanceWeights = `-- name: ActivePerformanceWeights :one
select version, weights from performance_weight_sets
where platform = $1
order by version desc limit 1
`

type ActivePerformanceWeightsRow struct {
	Version int32  `json:"version"`
	Weights []byte `json:"weights"`
}

func (q *Queries) ActivePerformanceWeights(ctx context.Context, platform Platform) (ActivePerformanceWeightsRow, error) {
	row := q.db.QueryRow(ctx, activePerformanceWeights, platform)
	var i ActivePerformanceWeightsRow
	err := row.Scan(&i.Version, &i.Weights)
	return i, err
}

const countPublicationsForMetrics = `-- name: CountPublicationsForMetrics :one
select count(*) from publications p
where p.platform = coalesce($1::platform, p.platform)
`

func (q *Queries) CountPublicationsForMetrics(ctx context.Context, platform NullPlatform) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicationsForMetrics, platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMetricSnapshot = `-- name: CreateMetricSnapshot :one
insert into metric_snapshots (
    publication_id, captured_at, metrics, source, snapshot_window,
    performance_raw, performance_percentile, performance_weight_version
) values ($1, $2, $3, $4, $5, $6, null, $7)
returning id, publication_id, captured_at, metrics, source, created_at,
          snapshot_window, performance_raw, performance_percentile, performance_weight_version
`

type CreateMetricSnapshotParams struct {
	PublicationID            uuid.UUID          `json:"publication_id"`
	CapturedAt               pgtype.Timestamptz `json:"captured_at"`
	Metrics                  []byte             `json:"metrics"`
	Source                   MetricSource       `json:"source"`
	SnapshotWindow           MetricWindow       `json:"snapshot_window"`
	PerformanceRaw           pgtype.Numeric     `json:"performance_raw"`
	PerformanceWeightVersion int32              `json:"performance_weight_version"`
}

func (q *Queries) CreateMetricSnapshot(ctx context.Context, arg CreateMetricSnapshotParams) (MetricSnapshot, error) {
	row := q.db.QueryRow(ctx, createMetricSnapshot,
		arg.PublicationID,
		arg.CapturedAt,
		arg.Metrics,
		arg.Source,
		arg.SnapshotWindow,
		arg.PerformanceRaw,
		arg.PerformanceWeightVersion,
	)
	var i MetricSnapshot
	err := row.Scan(
		&i.ID,
		&i.PublicationID,
		&i.CapturedAt,
		&i.Metrics,
		&i.Source,
		&i.CreatedAt,
		&i.SnapshotWindow,
		&i.PerformanceRaw,
		&i.PerformancePercentile,
		&i.PerformanceWeightVersion,
	)
	return i, err
}

const getInsight = `-- name: GetInsight :one
select id, kind, platform, content, evidence, confidence, status, embedding,
       created_at, updated_at, manual_status_override
from insights where id = $1
`

func (q *Queries) GetInsight(ctx context.Context, id uuid.UUID) (Insight, error) {
	row := q.db.QueryRow(ctx, getInsight, id)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Platform,
		&i.Content,
		&i.Evidence,
		&i.Confidence,
		&i.Status,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManualStatusOverride,
	)
	return i, err
}

const getPublicationForMetrics = `-- name: GetPublicationForMetrics :one
select p.id, p.article_id, p.platform, p.platform_post_id, p.published_at,
       p.final_content_diff, p.follower_count_at_publish, p.created_at, p.edit_ratio,
       a.title as article_title, t.title as topic_title
from publications p
join articles a on a.id = p.article_id
join topics t on t.id = a.topic_id
where p.id = $1
`

type GetPublicationForMetricsRow struct {
	ID                     uuid.UUID          `json:"id"`
	ArticleID              uuid.UUID          `json:"article_id"`
	Platform               Platform           `json:"platform"`
	PlatformPostID         pgtype.Text        `json:"platform_post_id"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	FinalContentDiff       pgtype.Text        `json:"final_content_diff"`
	FollowerCountAtPublish pgtype.Int4        `json:"follower_count_at_publish"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	EditRatio              pgtype.Numeric     `json:"edit_ratio"`
	ArticleTitle           string             `json:"article_title"`
	TopicTitle             string             `json:"topic_title"`
}

func (q *Queries) GetPublicationForMetrics(ctx context.Context, id uuid.UUID) (GetPublicationForMetricsRow, error) {
	row := q.db.QueryRow(ctx, getPublicationForMetrics, id)
	var i GetPublicationForMetricsRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Platform,
		&i.PlatformPostID,
		&i.PublishedAt,
		&i.FinalContentDiff,
		&i.FollowerCountAtPublish,
		&i.CreatedAt,
		&i.EditRatio,
		&i.ArticleTitle,
		&i.TopicTitle,
	)
	return i, err
}

const listInsights = `-- name: ListInsights :many
select id, kind, platform, content, evidence, confidence, status, embedding,
       created_at, updated_at, manual_status_override
from insights
where ($1::insight_kind is null or kind = $1::insight_kind)
  and ($2::insight_status is null or status = $2::insight_status)
  and (
    $3::platform is null
    or platform is null
    or platform = $3::platform
  )
order by status = 'active' desc, confidence desc, updated_at desc
limit $4
`

type ListInsightsParams struct {
	Kind     NullInsightKind   `json:"kind"`
	Status   NullInsightStatus `json:"status"`
	Platform NullPlatform      `json:"platform"`
	Lim      int32             `json:"lim"`
}

func (q *Queries) ListInsights(ctx context.Context, arg ListInsightsParams) ([]Insight, error) {
	rows, err := q.db.Query(ctx, listInsights,
		arg.Kind,
		arg.Status,
		arg.Platform,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Insight
	for rows.Next() {
		var i Insight
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Platform,
			&i.Content,
			&i.Evidence,
			&i.Confidence,
			&i.Status,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManualStatusOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricSnapshots = `-- name: ListMetricSnapshots :many
select id, publication_id, captured_at, metrics, source, created_at,
       snapshot_window, performance_raw, performance_percentile, performance_weight_version
from metric_snapshots
where publication_id = $1
order by captured_at asc, created_at asc
`

func (q *Queries) ListMetricSnapshots(ctx context.Context, publicationID uuid.UUID) ([]MetricSnapshot, error) {
	rows, err := q.db.Query(ctx, listMetricSnapshots, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSnapshot
	for rows.Next() {
		var i MetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.CapturedAt,
			&i.Metrics,
			&i.Source,
			&i.CreatedAt,
			&i.SnapshotWindow,
			&i.PerformanceRaw,
			&i.PerformancePercentile,
			&i.PerformanceWeightVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationsForMetrics = `-- name: ListPublicationsForMetrics :many
select p.id, p.article_id, p.platform, p.platform_post_id, p.published_at,
       p.final_content_diff, p.follower_count_at_publish, p.created_at, p.edit_ratio,
       a.title as article_title, t.title as topic_title
from publications p
join articles a on a.id = p.article_id
join topics t on t.id = a.topic_id
where p.platform = coalesce($1::platform, p.platform)
order by p.published_at desc
limit $3 offset $2
`

type ListPublicationsForMetricsParams struct {
	Platform NullPlatform `json:"platform"`
	Off      int32        `json:"off"`
	Lim      int32        `json:"lim"`
}

type ListPublicationsForMetricsRow struct {
	ID                     uuid.UUID          `json:"id"`
	ArticleID              uuid.UUID          `json:"article_id"`
	Platform               Platform           `json:"platform"`
	PlatformPostID         pgtype.Text        `json:"platform_post_id"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	FinalContentDiff       pgtype.Text        `json:"final_content_diff"`
	FollowerCountAtPublish pgtype.Int4        `json:"follower_count_at_publish"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	EditRatio              pgtype.Numeric     `json:"edit_ratio"`
	ArticleTitle           string             `json:"article_title"`
	TopicTitle             string             `json:"topic_title"`
}

func (q *Queries) ListPublicationsForMetrics(ctx context.Context, arg ListPublicationsForMetricsParams) ([]ListPublicationsForMetricsRow, error) {
	rows, err := q.db.Query(ctx, listPublicationsForMetrics, arg.Platform, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationsForMetricsRow
	for rows.Next() {
		var i ListPublicationsForMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.PlatformPostID,
			&i.PublishedAt,
			&i.FinalContentDiff,
			&i.FollowerCountAtPublish,
			&i.CreatedAt,
			&i.EditRatio,
			&i.ArticleTitle,
			&i.TopicTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyReports = `-- name: ListWeeklyReports :many
select id, period_start, period_end, sample_count, summary_markdown,
       calibration, agent_run_id, created_at
from weekly_reports
order by period_end desc
limit $1
`

func (q *Queries) ListWeeklyReports(ctx context.Context, limit int32) ([]WeeklyReport, error) {
	rows, err := q.db.Query(ctx, listWeeklyReports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyReport
	for rows.Next() {
		var i WeeklyReport
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SampleCount,
			&i.SummaryMarkdown,
			&i.Calibration,
			&i.AgentRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputePerformancePercentiles = `-- name: RecomputePerformancePercentiles :exec
with ranked as (
    select ms.id,
           percent_rank() over (order by ms.performance_raw) * 100 as percentile
    from metric_snapshots ms
    join publications p on p.id = ms.publication_id
    where p.platform = $1::platform
      and ms.snapshot_window = $2::metric_window
      and ms.snapshot_window <> 'custom'
      and ms.captured_at >= now() - interval '90 days'
)
update metric_snapshots ms
set performance_percentile = ranked.percentile
from ranked
where ms.id = ranked.id
`

type RecomputePerformancePercentilesParams struct {
	Platform       Platform     `json:"platform"`
	SnapshotWindow MetricWindow `json:"snapshot_window"`
}

func (q *Queries) RecomputePerformancePercentiles(ctx context.Context, arg RecomputePerformancePercentilesParams) error {
	_, err := q.db.Exec(ctx, recomputePerformancePercentiles, arg.Platform, arg.SnapshotWindow)
	return err
}

const updateInsightStatus = `-- name: UpdateInsightStatus :one
update insights
set status = $2, manual_status_override = true, updated_at = now()
where id = $1
returning id, kind, platform, content, evidence, confidence, status, embedding,
          created_at, updated_at, manual_status_override
`

type UpdateInsightStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status InsightStatus `json:"status"`
}

func (q *Queries) UpdateInsightStatus(ctx context.Context, arg UpdateInsightStatusParams) (Insight, error) {
	row := q.db.QueryRow(ctx, updateInsightStatus, arg.ID, arg.Status)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Platform,
		&i.Content,
		&i.Evidence,
		&i.Confidence,
		&i.Status,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManualStatusOverride,
	)
	return i, err
}
