// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AgentRunStatus string

const (
	AgentRunStatusRunning   AgentRunStatus = "running"
	AgentRunStatusSucceeded AgentRunStatus = "succeeded"
	AgentRunStatusFailed    AgentRunStatus = "failed"
)

func (e *AgentRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRunStatus(s)
	case string:
		*e = AgentRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRunStatus: %T", src)
	}
	return nil
}

type NullAgentRunStatus struct {
	AgentRunStatus AgentRunStatus `json:"agent_run_status"`
	Valid          bool           `json:"valid"` // Valid is true if AgentRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRunStatus), nil
}

type ArticleFormat string

const (
	ArticleFormatMarkdown ArticleFormat = "markdown"
)

func (e *ArticleFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticleFormat(s)
	case string:
		*e = ArticleFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticleFormat: %T", src)
	}
	return nil
}

type NullArticleFormat struct {
	ArticleFormat ArticleFormat `json:"article_format"`
	Valid         bool          `json:"valid"` // Valid is true if ArticleFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticleFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ArticleFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticleFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticleFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticleFormat), nil
}

type ArticleStatus string

const (
	ArticleStatusDraft         ArticleStatus = "draft"
	ArticleStatusScored        ArticleStatus = "scored"
	ArticleStatusRewriteQueued ArticleStatus = "rewrite_queued"
	ArticleStatusPendingReview ArticleStatus = "pending_review"
	ArticleStatusApproved      ArticleStatus = "approved"
	ArticleStatusPublished     ArticleStatus = "published"
	ArticleStatusRejected      ArticleStatus = "rejected"
)

func (e *ArticleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticleStatus(s)
	case string:
		*e = ArticleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticleStatus: %T", src)
	}
	return nil
}

type NullArticleStatus struct {
	ArticleStatus ArticleStatus `json:"article_status"`
	Valid         bool          `json:"valid"` // Valid is true if ArticleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArticleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticleStatus), nil
}

type InsightKind string

const (
	InsightKindTopicLesson    InsightKind = "topic_lesson"
	InsightKindWritingLesson  InsightKind = "writing_lesson"
	InsightKindPlatformLesson InsightKind = "platform_lesson"
	InsightKindSourceLesson   InsightKind = "source_lesson"
)

func (e *InsightKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InsightKind(s)
	case string:
		*e = InsightKind(s)
	default:
		return fmt.Errorf("unsupported scan type for InsightKind: %T", src)
	}
	return nil
}

type NullInsightKind struct {
	InsightKind InsightKind `json:"insight_kind"`
	Valid       bool        `json:"valid"` // Valid is true if InsightKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInsightKind) Scan(value interface{}) error {
	if value == nil {
		ns.InsightKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InsightKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInsightKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InsightKind), nil
}

type InsightStatus string

const (
	InsightStatusCandidate InsightStatus = "candidate"
	InsightStatusActive    InsightStatus = "active"
	InsightStatusRetired   InsightStatus = "retired"
)

func (e *InsightStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InsightStatus(s)
	case string:
		*e = InsightStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InsightStatus: %T", src)
	}
	return nil
}

type NullInsightStatus struct {
	InsightStatus InsightStatus `json:"insight_status"`
	Valid         bool          `json:"valid"` // Valid is true if InsightStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInsightStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InsightStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InsightStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInsightStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InsightStatus), nil
}

type MetricSource string

const (
	MetricSourceManual MetricSource = "manual"
	MetricSourceImport MetricSource = "import"
	MetricSourceApi    MetricSource = "api"
)

func (e *MetricSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MetricSource(s)
	case string:
		*e = MetricSource(s)
	default:
		return fmt.Errorf("unsupported scan type for MetricSource: %T", src)
	}
	return nil
}

type NullMetricSource struct {
	MetricSource MetricSource `json:"metric_source"`
	Valid        bool         `json:"valid"` // Valid is true if MetricSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMetricSource) Scan(value interface{}) error {
	if value == nil {
		ns.MetricSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MetricSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMetricSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MetricSource), nil
}

type Platform string

const (
	PlatformXiaohongshu Platform = "xiaohongshu"
	PlatformZhihu       Platform = "zhihu"
	PlatformWechat      Platform = "wechat"
)

func (e *Platform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Platform(s)
	case string:
		*e = Platform(s)
	default:
		return fmt.Errorf("unsupported scan type for Platform: %T", src)
	}
	return nil
}

type NullPlatform struct {
	Platform Platform `json:"platform"`
	Valid    bool     `json:"valid"` // Valid is true if Platform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.Platform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Platform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Platform), nil
}

type RawItemStatus string

const (
	RawItemStatusNew       RawItemStatus = "new"
	RawItemStatusClustered RawItemStatus = "clustered"
	RawItemStatusDiscarded RawItemStatus = "discarded"
)

func (e *RawItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RawItemStatus(s)
	case string:
		*e = RawItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RawItemStatus: %T", src)
	}
	return nil
}

type NullRawItemStatus struct {
	RawItemStatus RawItemStatus `json:"raw_item_status"`
	Valid         bool          `json:"valid"` // Valid is true if RawItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRawItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RawItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RawItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRawItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RawItemStatus), nil
}

type SourceCategory string

const (
	SourceCategoryNews     SourceCategory = "news"
	SourceCategoryResearch SourceCategory = "research"
	SourceCategoryTutorial SourceCategory = "tutorial"
	SourceCategoryKol      SourceCategory = "kol"
)

func (e *SourceCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceCategory(s)
	case string:
		*e = SourceCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceCategory: %T", src)
	}
	return nil
}

type NullSourceCategory struct {
	SourceCategory SourceCategory `json:"source_category"`
	Valid          bool           `json:"valid"` // Valid is true if SourceCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceCategory) Scan(value interface{}) error {
	if value == nil {
		ns.SourceCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceCategory), nil
}

type SourceType string

const (
	SourceTypeRss     SourceType = "rss"
	SourceTypeRsshub  SourceType = "rsshub"
	SourceTypeManual  SourceType = "manual"
	SourceTypeCrawler SourceType = "crawler"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type TopicStatus string

const (
	TopicStatusCandidate TopicStatus = "candidate"
	TopicStatusScored    TopicStatus = "scored"
	TopicStatusApproved  TopicStatus = "approved"
	TopicStatusInWriting TopicStatus = "in_writing"
	TopicStatusWritten   TopicStatus = "written"
	TopicStatusRejected  TopicStatus = "rejected"
)

func (e *TopicStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TopicStatus(s)
	case string:
		*e = TopicStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TopicStatus: %T", src)
	}
	return nil
}

type NullTopicStatus struct {
	TopicStatus TopicStatus `json:"topic_status"`
	Valid       bool        `json:"valid"` // Valid is true if TopicStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTopicStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TopicStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TopicStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTopicStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TopicStatus), nil
}

type AgentRun struct {
	ID              uuid.UUID          `json:"id"`
	JobType         string             `json:"job_type"`
	EntityType      pgtype.Text        `json:"entity_type"`
	EntityID        uuid.NullUUID      `json:"entity_id"`
	LangfuseTraceID pgtype.Text        `json:"langfuse_trace_id"`
	Model           pgtype.Text        `json:"model"`
	PromptVersion   pgtype.Text        `json:"prompt_version"`
	TokensIn        pgtype.Int8        `json:"tokens_in"`
	TokensOut       pgtype.Int8        `json:"tokens_out"`
	CostUsd         pgtype.Numeric     `json:"cost_usd"`
	Status          AgentRunStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Article struct {
	ID          uuid.UUID          `json:"id"`
	TopicID     uuid.UUID          `json:"topic_id"`
	Platform    Platform           `json:"platform"`
	Version     int32              `json:"version"`
	Format      ArticleFormat      `json:"format"`
	Title       string             `json:"title"`
	ContentMd   string             `json:"content_md"`
	Assets      []byte             `json:"assets"`
	WriterAgent string             `json:"writer_agent"`
	Status      ArticleStatus      `json:"status"`
	LatestScore pgtype.Numeric     `json:"latest_score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ArticleEvaluation struct {
	ID              uuid.UUID          `json:"id"`
	ArticleID       uuid.UUID          `json:"article_id"`
	RubricVersion   string             `json:"rubric_version"`
	DimensionScores []byte             `json:"dimension_scores"`
	TotalScore      pgtype.Numeric     `json:"total_score"`
	Rationale       string             `json:"rationale"`
	JudgeModel      string             `json:"judge_model"`
	AgentRunID      uuid.NullUUID      `json:"agent_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Insight struct {
	ID         uuid.UUID           `json:"id"`
	Kind       InsightKind         `json:"kind"`
	Platform   NullPlatform        `json:"platform"`
	Content    string              `json:"content"`
	Evidence   []byte              `json:"evidence"`
	Confidence pgtype.Numeric      `json:"confidence"`
	Status     InsightStatus       `json:"status"`
	Embedding  *pgvector_go.Vector `json:"embedding"`
	CreatedAt  pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz  `json:"updated_at"`
}

type MetricSnapshot struct {
	ID            uuid.UUID          `json:"id"`
	PublicationID uuid.UUID          `json:"publication_id"`
	CapturedAt    pgtype.Timestamptz `json:"captured_at"`
	Metrics       []byte             `json:"metrics"`
	Source        MetricSource       `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Publication struct {
	ID                     uuid.UUID          `json:"id"`
	ArticleID              uuid.UUID          `json:"article_id"`
	Platform               Platform           `json:"platform"`
	PlatformPostID         pgtype.Text        `json:"platform_post_id"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	FinalContentDiff       pgtype.Text        `json:"final_content_diff"`
	FollowerCountAtPublish pgtype.Int4        `json:"follower_count_at_publish"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type RawItem struct {
	ID          uuid.UUID           `json:"id"`
	SourceID    uuid.UUID           `json:"source_id"`
	Title       string              `json:"title"`
	Url         pgtype.Text         `json:"url"`
	Author      pgtype.Text         `json:"author"`
	Content     string              `json:"content"`
	PublishedAt pgtype.Timestamptz  `json:"published_at"`
	ContentHash string              `json:"content_hash"`
	Embedding   *pgvector_go.Vector `json:"embedding"`
	Status      RawItemStatus       `json:"status"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
}

type ScheduleRun struct {
	ID          uuid.UUID          `json:"id"`
	ScheduleKey string             `json:"schedule_key"`
	PlannedAt   pgtype.Timestamptz `json:"planned_at"`
	EnqueuedAt  pgtype.Timestamptz `json:"enqueued_at"`
	Queue       string             `json:"queue"`
	MsgID       pgtype.Int8        `json:"msg_id"`
	Note        pgtype.Text        `json:"note"`
}

type SchedulerSetting struct {
	ID        bool               `json:"id"`
	Settings  []byte             `json:"settings"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Source struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Type        SourceType         `json:"type"`
	Url         pgtype.Text        `json:"url"`
	Category    SourceCategory     `json:"category"`
	Weight      pgtype.Numeric     `json:"weight"`
	Enabled     bool               `json:"enabled"`
	FetchConfig []byte             `json:"fetch_config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SourceHealth struct {
	SourceID            uuid.UUID          `json:"source_id"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	NextRunAt           pgtype.Timestamptz `json:"next_run_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Topic struct {
	ID              uuid.UUID           `json:"id"`
	Title           string              `json:"title"`
	Angle           string              `json:"angle"`
	Summary         string              `json:"summary"`
	RawItemIds      []uuid.UUID         `json:"raw_item_ids"`
	TargetPlatforms []Platform          `json:"target_platforms"`
	Status          TopicStatus         `json:"status"`
	LatestScore     pgtype.Numeric      `json:"latest_score"`
	Embedding       *pgvector_go.Vector `json:"embedding"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz  `json:"updated_at"`
}

type TopicEvaluation struct {
	ID              uuid.UUID          `json:"id"`
	TopicID         uuid.UUID          `json:"topic_id"`
	RubricVersion   string             `json:"rubric_version"`
	DimensionScores []byte             `json:"dimension_scores"`
	TotalScore      pgtype.Numeric     `json:"total_score"`
	Rationale       string             `json:"rationale"`
	JudgeModel      string             `json:"judge_model"`
	AgentRunID      uuid.NullUUID      `json:"agent_run_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WeightSet struct {
	ID        uuid.UUID          `json:"id"`
	RubricID  string             `json:"rubric_id"`
	Version   int32              `json:"version"`
	Weights   []byte             `json:"weights"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
