// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pipeline.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createManualRawItem = `-- name: CreateManualRawItem :one
insert into raw_items (source_id, title, url, content, content_hash, status)
values ($1, $2, $3, $4, $5, 'new')
on conflict (content_hash) do nothing
returning id
`

type CreateManualRawItemParams struct {
	SourceID    uuid.UUID   `json:"source_id"`
	Title       string      `json:"title"`
	Url         pgtype.Text `json:"url"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
}

// 手动投喂：先落一条占位 raw_item（内容抓取由 agents 的 source_fetch 完成后更新）
func (q *Queries) CreateManualRawItem(ctx context.Context, arg CreateManualRawItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createManualRawItem,
		arg.SourceID,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.ContentHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createManualSource = `-- name: CreateManualSource :one
insert into sources (name, type, url, category, weight, enabled, fetch_config)
values ('Manual Feed', 'manual', null, 'news', 0.8, true, '{"role": "material", "full_text": "fetch_page"}')
on conflict (name) do update set updated_at = now()
returning id
`

func (q *Queries) CreateManualSource(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createManualSource)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getManualSource = `-- name: GetManualSource :one
select id from sources where type = 'manual' and name = 'Manual Feed' limit 1
`

// 手动投喂共用的内置 manual 源（seed 于迁移或首次使用时创建）
func (q *Queries) GetManualSource(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getManualSource)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const latestEvaluation = `-- name: LatestEvaluation :one
select id, topic_id, total_score, created_at from topic_evaluations
where topic_id = $1 order by created_at desc limit 1
`

type LatestEvaluationRow struct {
	ID         uuid.UUID          `json:"id"`
	TopicID    uuid.UUID          `json:"topic_id"`
	TotalScore pgtype.Numeric     `json:"total_score"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// harvester：收割某选题最近一次评分
func (q *Queries) LatestEvaluation(ctx context.Context, topicID uuid.UUID) (LatestEvaluationRow, error) {
	row := q.db.QueryRow(ctx, latestEvaluation, topicID)
	var i LatestEvaluationRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.TotalScore,
		&i.CreatedAt,
	)
	return i, err
}

const listTopicEvaluations = `-- name: ListTopicEvaluations :many
select id, topic_id, rubric_version, dimension_scores, total_score, rationale,
       judge_model, agent_run_id, weight_version, vetoed_dimension, created_at
from topic_evaluations
where topic_id = $1
order by created_at desc
`

type ListTopicEvaluationsRow struct {
	ID              uuid.UUID          `json:"id"`
	TopicID         uuid.UUID          `json:"topic_id"`
	RubricVersion   string             `json:"rubric_version"`
	DimensionScores []byte             `json:"dimension_scores"`
	TotalScore      pgtype.Numeric     `json:"total_score"`
	Rationale       string             `json:"rationale"`
	JudgeModel      string             `json:"judge_model"`
	AgentRunID      uuid.NullUUID      `json:"agent_run_id"`
	WeightVersion   pgtype.Int4        `json:"weight_version"`
	VetoedDimension pgtype.Text        `json:"vetoed_dimension"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTopicEvaluations(ctx context.Context, topicID uuid.UUID) ([]ListTopicEvaluationsRow, error) {
	rows, err := q.db.Query(ctx, listTopicEvaluations, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicEvaluationsRow
	for rows.Next() {
		var i ListTopicEvaluationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.RubricVersion,
			&i.DimensionScores,
			&i.TotalScore,
			&i.Rationale,
			&i.JudgeModel,
			&i.AgentRunID,
			&i.WeightVersion,
			&i.VetoedDimension,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingCandidates = `-- name: PendingCandidates :many
select id, title from topics where status = 'candidate' order by created_at limit $1
`

type PendingCandidatesRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

// harvester：等待投递评分的 candidate（事件驱动，SPEC-008 §3.1 纪律 2）。
// 用 schedule_runs 的唯一约束防重投，此处只取状态。
func (q *Queries) PendingCandidates(ctx context.Context, limit int32) ([]PendingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, pendingCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingCandidatesRow
	for rows.Next() {
		var i PendingCandidatesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoredTopicsWithoutTransition = `-- name: ScoredTopicsWithoutTransition :many
select t.id, t.status, e.total_score, e.id as evaluation_id
from topics t
join lateral (
    select id, total_score from topic_evaluations
    where topic_id = t.id order by created_at desc limit 1
) e on true
where t.status = 'candidate'
limit $1
`

type ScoredTopicsWithoutTransitionRow struct {
	ID           uuid.UUID      `json:"id"`
	Status       TopicStatus    `json:"status"`
	TotalScore   pgtype.Numeric `json:"total_score"`
	EvaluationID uuid.UUID      `json:"evaluation_id"`
}

// harvester：已有评分但状态仍是 candidate 的选题（评分完成，待推进状态机）
func (q *Queries) ScoredTopicsWithoutTransition(ctx context.Context, limit int32) ([]ScoredTopicsWithoutTransitionRow, error) {
	rows, err := q.db.Query(ctx, scoredTopicsWithoutTransition, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoredTopicsWithoutTransitionRow
	for rows.Next() {
		var i ScoredTopicsWithoutTransitionRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalScore,
			&i.EvaluationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionTopic = `-- name: TransitionTopic :one
update topics set status = $2, latest_score = coalesce($3, latest_score), updated_at = now()
where id = $1 and status = $4
returning id, title, angle, summary, raw_item_ids, target_platforms, status, latest_score, embedding, created_at, updated_at
`

type TransitionTopicParams struct {
	ID         uuid.UUID      `json:"id"`
	ToStatus   TopicStatus    `json:"to_status"`
	Score      pgtype.Numeric `json:"score"`
	FromStatus TopicStatus    `json:"from_status"`
}

// 状态机唯一写入口：带前置状态条件的 CAS 更新。0 行 = 前置状态不符（并发或非法流转）。
func (q *Queries) TransitionTopic(ctx context.Context, arg TransitionTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, transitionTopic,
		arg.ID,
		arg.ToStatus,
		arg.Score,
		arg.FromStatus,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Angle,
		&i.Summary,
		&i.RawItemIds,
		&i.TargetPlatforms,
		&i.Status,
		&i.LatestScore,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
