// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const articleEvaluationsWithoutTransition = `-- name: ArticleEvaluationsWithoutTransition :many
select a.id, a.topic_id, a.platform, a.version, t.correlation_id,
       e.id as evaluation_id, e.total_score
from articles a
join topics t on t.id = a.topic_id
join lateral (
    select id, total_score
    from article_evaluations
    where article_id = a.id
    order by created_at desc
    limit 1
) e on true
where a.status = 'draft'
order by a.updated_at, a.id
limit $1
`

type ArticleEvaluationsWithoutTransitionRow struct {
	ID            uuid.UUID      `json:"id"`
	TopicID       uuid.UUID      `json:"topic_id"`
	Platform      Platform       `json:"platform"`
	Version       int32          `json:"version"`
	CorrelationID uuid.NullUUID  `json:"correlation_id"`
	EvaluationID  uuid.UUID      `json:"evaluation_id"`
	TotalScore    pgtype.Numeric `json:"total_score"`
}

// ArticleJudge 已写回评分，但 Article 仍是 draft；先推进到 scored。
func (q *Queries) ArticleEvaluationsWithoutTransition(ctx context.Context, limit int32) ([]ArticleEvaluationsWithoutTransitionRow, error) {
	rows, err := q.db.Query(ctx, articleEvaluationsWithoutTransition, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleEvaluationsWithoutTransitionRow
	for rows.Next() {
		var i ArticleEvaluationsWithoutTransitionRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Platform,
			&i.Version,
			&i.CorrelationID,
			&i.EvaluationID,
			&i.TotalScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createManualRawItem = `-- name: CreateManualRawItem :one
insert into raw_items (source_id, title, url, content, content_hash, status)
values ($1, $2, $3, $4, $5, 'new')
on conflict (content_hash) do nothing
returning id
`

type CreateManualRawItemParams struct {
	SourceID    uuid.UUID   `json:"source_id"`
	Title       string      `json:"title"`
	Url         pgtype.Text `json:"url"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
}

// 手动投喂：先落一条占位 raw_item（内容抓取由 agents 的 source_fetch 完成后更新）
func (q *Queries) CreateManualRawItem(ctx context.Context, arg CreateManualRawItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createManualRawItem,
		arg.SourceID,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.ContentHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createManualSource = `-- name: CreateManualSource :one
insert into sources (name, type, url, category, weight, enabled, fetch_config)
values ('Manual Feed', 'manual', null, 'news', 0.8, true, '{"role": "material", "full_text": "fetch_page"}')
on conflict (name) do update set
    enabled = true, archived_at = null, updated_at = now()
returning id
`

func (q *Queries) CreateManualSource(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createManualSource)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const draftArticlesPendingEvaluation = `-- name: DraftArticlesPendingEvaluation :many
select a.id, a.topic_id, a.platform, t.correlation_id
from articles a
join topics t on t.id = a.topic_id
where a.status = 'draft'
order by a.created_at, a.id
limit $1
`

type DraftArticlesPendingEvaluationRow struct {
	ID            uuid.UUID     `json:"id"`
	TopicID       uuid.UUID     `json:"topic_id"`
	Platform      Platform      `json:"platform"`
	CorrelationID uuid.NullUUID `json:"correlation_id"`
}

// M2 harvester：Article 已由 agents 写回，但尚未投递独立评分任务。
// schedule_runs 负责最终防重；这里保持查询简单，便于故障后重新扫描。
func (q *Queries) DraftArticlesPendingEvaluation(ctx context.Context, limit int32) ([]DraftArticlesPendingEvaluationRow, error) {
	rows, err := q.db.Query(ctx, draftArticlesPendingEvaluation, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftArticlesPendingEvaluationRow
	for rows.Next() {
		var i DraftArticlesPendingEvaluationRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Platform,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManualSource = `-- name: GetManualSource :one
select id from sources
where type = 'manual' and name = 'Manual Feed' and archived_at is null
limit 1
`

// 手动投喂共用的内置 manual 源（seed 于迁移或首次使用时创建）
func (q *Queries) GetManualSource(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getManualSource)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const inWritingTopicsReady = `-- name: InWritingTopicsReady :many
select t.id, t.correlation_id
from topics t
where t.status = 'in_writing'
  and not exists (
      select 1
      from unnest(t.target_platforms) as target(platform)
      where not exists (
          select 1
          from articles a
          where a.topic_id = t.id and a.platform = target.platform
      )
  )
order by t.updated_at, t.id
limit $1
`

type InWritingTopicsReadyRow struct {
	ID            uuid.UUID     `json:"id"`
	CorrelationID uuid.NullUUID `json:"correlation_id"`
}

// 只有 target_platforms 中每个平台都至少已有一篇文章，Topic 才算写作完成。
func (q *Queries) InWritingTopicsReady(ctx context.Context, limit int32) ([]InWritingTopicsReadyRow, error) {
	rows, err := q.db.Query(ctx, inWritingTopicsReady, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InWritingTopicsReadyRow
	for rows.Next() {
		var i InWritingTopicsReadyRow
		if err := rows.Scan(&i.ID, &i.CorrelationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestEvaluation = `-- name: LatestEvaluation :one
select id, topic_id, total_score, created_at from topic_evaluations
where topic_id = $1 order by created_at desc limit 1
`

type LatestEvaluationRow struct {
	ID         uuid.UUID          `json:"id"`
	TopicID    uuid.UUID          `json:"topic_id"`
	TotalScore pgtype.Numeric     `json:"total_score"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// harvester：收割某选题最近一次评分
func (q *Queries) LatestEvaluation(ctx context.Context, topicID uuid.UUID) (LatestEvaluationRow, error) {
	row := q.db.QueryRow(ctx, latestEvaluation, topicID)
	var i LatestEvaluationRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.TotalScore,
		&i.CreatedAt,
	)
	return i, err
}

const listTopicEvaluations = `-- name: ListTopicEvaluations :many
select id, topic_id, rubric_version, dimension_scores, dimension_reasons, total_score, rationale,
       judge_model, agent_run_id, weight_version, vetoed_dimension, created_at
from topic_evaluations
where topic_id = $1
order by created_at desc
`

type ListTopicEvaluationsRow struct {
	ID               uuid.UUID          `json:"id"`
	TopicID          uuid.UUID          `json:"topic_id"`
	RubricVersion    string             `json:"rubric_version"`
	DimensionScores  []byte             `json:"dimension_scores"`
	DimensionReasons []byte             `json:"dimension_reasons"`
	TotalScore       pgtype.Numeric     `json:"total_score"`
	Rationale        string             `json:"rationale"`
	JudgeModel       string             `json:"judge_model"`
	AgentRunID       uuid.NullUUID      `json:"agent_run_id"`
	WeightVersion    pgtype.Int4        `json:"weight_version"`
	VetoedDimension  pgtype.Text        `json:"vetoed_dimension"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTopicEvaluations(ctx context.Context, topicID uuid.UUID) ([]ListTopicEvaluationsRow, error) {
	rows, err := q.db.Query(ctx, listTopicEvaluations, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicEvaluationsRow
	for rows.Next() {
		var i ListTopicEvaluationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.RubricVersion,
			&i.DimensionScores,
			&i.DimensionReasons,
			&i.TotalScore,
			&i.Rationale,
			&i.JudgeModel,
			&i.AgentRunID,
			&i.WeightVersion,
			&i.VetoedDimension,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingApprovedTopics = `-- name: PendingApprovedTopics :many
select id, title, target_platforms, correlation_id
from topics
where status = 'approved'
order by updated_at, id
limit $1
`

type PendingApprovedTopicsRow struct {
	ID              uuid.UUID     `json:"id"`
	Title           string        `json:"title"`
	TargetPlatforms []Platform    `json:"target_platforms"`
	CorrelationID   uuid.NullUUID `json:"correlation_id"`
}

// M2 harvester：等待按目标平台分派写作的 approved 选题。
func (q *Queries) PendingApprovedTopics(ctx context.Context, limit int32) ([]PendingApprovedTopicsRow, error) {
	rows, err := q.db.Query(ctx, pendingApprovedTopics, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingApprovedTopicsRow
	for rows.Next() {
		var i PendingApprovedTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TargetPlatforms,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingCandidates = `-- name: PendingCandidates :many
select id, title, correlation_id
from topics where status = 'candidate' order by created_at limit $1
`

type PendingCandidatesRow struct {
	ID            uuid.UUID     `json:"id"`
	Title         string        `json:"title"`
	CorrelationID uuid.NullUUID `json:"correlation_id"`
}

// harvester：等待投递评分的 candidate（事件驱动，SPEC-008 §3.1 纪律 2）。
// 用 schedule_runs 的唯一约束防重投，此处只取状态。
func (q *Queries) PendingCandidates(ctx context.Context, limit int32) ([]PendingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, pendingCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingCandidatesRow
	for rows.Next() {
		var i PendingCandidatesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CorrelationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoredArticlesWithoutDecision = `-- name: ScoredArticlesWithoutDecision :many
select a.id, a.topic_id, a.platform, a.version, t.correlation_id,
       e.id as evaluation_id, e.total_score, e.passed, e.pass_threshold,
       e.rationale, e.dimension_scores, e.dimension_reasons, e.vetoed_dimension
from articles a
join topics t on t.id = a.topic_id
join lateral (
    select id, total_score, passed, pass_threshold, rationale,
           dimension_scores, dimension_reasons, vetoed_dimension
    from article_evaluations
    where article_id = a.id
    order by created_at desc
    limit 1
) e on true
where a.status = 'scored'
order by a.updated_at, a.id
limit $1
`

type ScoredArticlesWithoutDecisionRow struct {
	ID               uuid.UUID      `json:"id"`
	TopicID          uuid.UUID      `json:"topic_id"`
	Platform         Platform       `json:"platform"`
	Version          int32          `json:"version"`
	CorrelationID    uuid.NullUUID  `json:"correlation_id"`
	EvaluationID     uuid.UUID      `json:"evaluation_id"`
	TotalScore       pgtype.Numeric `json:"total_score"`
	Passed           bool           `json:"passed"`
	PassThreshold    pgtype.Numeric `json:"pass_threshold"`
	Rationale        string         `json:"rationale"`
	DimensionScores  []byte         `json:"dimension_scores"`
	DimensionReasons []byte         `json:"dimension_reasons"`
	VetoedDimension  pgtype.Text    `json:"vetoed_dimension"`
}

// scored 是显式审计节点；随后按确定性 passed 判定进入人工终审或回炉。
func (q *Queries) ScoredArticlesWithoutDecision(ctx context.Context, limit int32) ([]ScoredArticlesWithoutDecisionRow, error) {
	rows, err := q.db.Query(ctx, scoredArticlesWithoutDecision, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoredArticlesWithoutDecisionRow
	for rows.Next() {
		var i ScoredArticlesWithoutDecisionRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Platform,
			&i.Version,
			&i.CorrelationID,
			&i.EvaluationID,
			&i.TotalScore,
			&i.Passed,
			&i.PassThreshold,
			&i.Rationale,
			&i.DimensionScores,
			&i.DimensionReasons,
			&i.VetoedDimension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoredTopicsWithoutTransition = `-- name: ScoredTopicsWithoutTransition :many
select t.id, t.status, t.correlation_id, e.total_score, e.id as evaluation_id
from topics t
join lateral (
    select id, total_score from topic_evaluations
    where topic_id = t.id order by created_at desc limit 1
) e on true
where t.status = 'candidate'
limit $1
`

type ScoredTopicsWithoutTransitionRow struct {
	ID            uuid.UUID      `json:"id"`
	Status        TopicStatus    `json:"status"`
	CorrelationID uuid.NullUUID  `json:"correlation_id"`
	TotalScore    pgtype.Numeric `json:"total_score"`
	EvaluationID  uuid.UUID      `json:"evaluation_id"`
}

// harvester：已有评分但状态仍是 candidate 的选题（评分完成，待推进状态机）
func (q *Queries) ScoredTopicsWithoutTransition(ctx context.Context, limit int32) ([]ScoredTopicsWithoutTransitionRow, error) {
	rows, err := q.db.Query(ctx, scoredTopicsWithoutTransition, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoredTopicsWithoutTransitionRow
	for rows.Next() {
		var i ScoredTopicsWithoutTransitionRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CorrelationID,
			&i.TotalScore,
			&i.EvaluationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionArticle = `-- name: TransitionArticle :one
with transitioned as (
    update articles
    set status = $1,
        latest_score = coalesce($2, latest_score),
        updated_at = now()
    where articles.id = $3 and articles.status = $4
    returning articles.id, articles.topic_id, articles.platform, articles.version, articles.format, articles.title, articles.content_md, articles.assets, articles.writer_agent, articles.status, articles.latest_score, articles.created_at, articles.updated_at, articles.previous_article_id
), audited as (
    insert into state_transition_events (
        entity_type, entity_id, from_status, to_status,
        actor_type, actor_id, trigger_type, trigger_id, reason,
        correlation_id, metadata
    )
    select 'article', transitioned.id, $4::text, $1::text,
           $5::text, $6::text,
           $7::text, $8::text,
           $9::text, $10::uuid,
           coalesce($11::jsonb, '{}'::jsonb)
    from transitioned
)
select id, topic_id, platform, version, format, title, content_md, assets, writer_agent, status, latest_score, created_at, updated_at, previous_article_id from transitioned
`

type TransitionArticleParams struct {
	ToStatus      ArticleStatus  `json:"to_status"`
	Score         pgtype.Numeric `json:"score"`
	ArticleID     uuid.UUID      `json:"article_id"`
	FromStatus    ArticleStatus  `json:"from_status"`
	ActorType     string         `json:"actor_type"`
	ActorID       pgtype.Text    `json:"actor_id"`
	TriggerType   string         `json:"trigger_type"`
	TriggerID     pgtype.Text    `json:"trigger_id"`
	Reason        pgtype.Text    `json:"reason"`
	CorrelationID uuid.NullUUID  `json:"correlation_id"`
	Metadata      []byte         `json:"metadata"`
}

type TransitionArticleRow struct {
	ID                uuid.UUID          `json:"id"`
	TopicID           uuid.UUID          `json:"topic_id"`
	Platform          Platform           `json:"platform"`
	Version           int32              `json:"version"`
	Format            ArticleFormat      `json:"format"`
	Title             string             `json:"title"`
	ContentMd         string             `json:"content_md"`
	Assets            []byte             `json:"assets"`
	WriterAgent       string             `json:"writer_agent"`
	Status            ArticleStatus      `json:"status"`
	LatestScore       pgtype.Numeric     `json:"latest_score"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PreviousArticleID uuid.NullUUID      `json:"previous_article_id"`
}

// Article 状态机唯一写入口：CAS 更新与审计事件同一 SQL 完成。
func (q *Queries) TransitionArticle(ctx context.Context, arg TransitionArticleParams) (TransitionArticleRow, error) {
	row := q.db.QueryRow(ctx, transitionArticle,
		arg.ToStatus,
		arg.Score,
		arg.ArticleID,
		arg.FromStatus,
		arg.ActorType,
		arg.ActorID,
		arg.TriggerType,
		arg.TriggerID,
		arg.Reason,
		arg.CorrelationID,
		arg.Metadata,
	)
	var i TransitionArticleRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Platform,
		&i.Version,
		&i.Format,
		&i.Title,
		&i.ContentMd,
		&i.Assets,
		&i.WriterAgent,
		&i.Status,
		&i.LatestScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreviousArticleID,
	)
	return i, err
}

const transitionTopic = `-- name: TransitionTopic :one
with transitioned as (
    update topics
    set status = $1,
        latest_score = coalesce($2, latest_score),
        updated_at = now()
    where topics.id = $3 and topics.status = $4
    returning topics.id, topics.title, topics.angle, topics.summary, topics.raw_item_ids, topics.target_platforms, topics.status, topics.latest_score, topics.embedding, topics.created_at, topics.updated_at, topics.correlation_id
), audited as (
    insert into state_transition_events (
        entity_type, entity_id, from_status, to_status,
        actor_type, actor_id, trigger_type, trigger_id, reason,
        correlation_id, metadata
    )
    select 'topic', transitioned.id, $4::text, $1::text,
           $5::text, $6::text,
           $7::text, $8::text,
           $9::text,
           coalesce($10::uuid, transitioned.correlation_id),
           coalesce($11::jsonb, '{}'::jsonb)
    from transitioned
)
select id, title, angle, summary, raw_item_ids, target_platforms, status, latest_score, embedding, created_at, updated_at, correlation_id from transitioned
`

type TransitionTopicParams struct {
	ToStatus      TopicStatus    `json:"to_status"`
	Score         pgtype.Numeric `json:"score"`
	TopicID       uuid.UUID      `json:"topic_id"`
	FromStatus    TopicStatus    `json:"from_status"`
	ActorType     string         `json:"actor_type"`
	ActorID       pgtype.Text    `json:"actor_id"`
	TriggerType   string         `json:"trigger_type"`
	TriggerID     pgtype.Text    `json:"trigger_id"`
	Reason        pgtype.Text    `json:"reason"`
	CorrelationID uuid.NullUUID  `json:"correlation_id"`
	Metadata      []byte         `json:"metadata"`
}

type TransitionTopicRow struct {
	ID              uuid.UUID           `json:"id"`
	Title           string              `json:"title"`
	Angle           string              `json:"angle"`
	Summary         string              `json:"summary"`
	RawItemIds      []uuid.UUID         `json:"raw_item_ids"`
	TargetPlatforms []Platform          `json:"target_platforms"`
	Status          TopicStatus         `json:"status"`
	LatestScore     pgtype.Numeric      `json:"latest_score"`
	Embedding       *pgvector_go.Vector `json:"embedding"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz  `json:"updated_at"`
	CorrelationID   uuid.NullUUID       `json:"correlation_id"`
}

// 状态机唯一写入口：CAS 更新、审计事件同一 SQL/事务完成。
func (q *Queries) TransitionTopic(ctx context.Context, arg TransitionTopicParams) (TransitionTopicRow, error) {
	row := q.db.QueryRow(ctx, transitionTopic,
		arg.ToStatus,
		arg.Score,
		arg.TopicID,
		arg.FromStatus,
		arg.ActorType,
		arg.ActorID,
		arg.TriggerType,
		arg.TriggerID,
		arg.Reason,
		arg.CorrelationID,
		arg.Metadata,
	)
	var i TransitionTopicRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Angle,
		&i.Summary,
		&i.RawItemIds,
		&i.TargetPlatforms,
		&i.Status,
		&i.LatestScore,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CorrelationID,
	)
	return i, err
}
