// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scheduler.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeWeightSet = `-- name: ActiveWeightSet :one
select version, weights from weight_sets
where rubric_id = $1 order by version desc limit 1
`

type ActiveWeightSetRow struct {
	Version int32  `json:"version"`
	Weights []byte `json:"weights"`
}

// Judge 取当前生效权重：最大 version
func (q *Queries) ActiveWeightSet(ctx context.Context, rubricID string) (ActiveWeightSetRow, error) {
	row := q.db.QueryRow(ctx, activeWeightSet, rubricID)
	var i ActiveWeightSetRow
	err := row.Scan(&i.Version, &i.Weights)
	return i, err
}

const countNewRawItems = `-- name: CountNewRawItems :one
select count(*) from raw_items where status = 'new'
`

// topic_scout 的 min_new_items 闸门用
func (q *Queries) CountNewRawItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNewRawItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSchedulerSettings = `-- name: GetSchedulerSettings :one
select settings, updated_at from scheduler_settings where id = true
`

type GetSchedulerSettingsRow struct {
	Settings  []byte             `json:"settings"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchedulerSettings(ctx context.Context) (GetSchedulerSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSchedulerSettings)
	var i GetSchedulerSettingsRow
	err := row.Scan(&i.Settings, &i.UpdatedAt)
	return i, err
}

const recentScheduleRuns = `-- name: RecentScheduleRuns :many
select id, schedule_key, planned_at, enqueued_at, queue, msg_id, note from schedule_runs order by enqueued_at desc limit $1
`

func (q *Queries) RecentScheduleRuns(ctx context.Context, limit int32) ([]ScheduleRun, error) {
	rows, err := q.db.Query(ctx, recentScheduleRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleRun
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleKey,
			&i.PlannedAt,
			&i.EnqueuedAt,
			&i.Queue,
			&i.MsgID,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleRun = `-- name: RecordScheduleRun :one
insert into schedule_runs (schedule_key, planned_at, queue, msg_id, note)
values ($1, $2, $3, $4, $5)
on conflict (schedule_key, planned_at) do nothing
returning id
`

type RecordScheduleRunParams struct {
	ScheduleKey string             `json:"schedule_key"`
	PlannedAt   pgtype.Timestamptz `json:"planned_at"`
	Queue       string             `json:"queue"`
	MsgID       pgtype.Int8        `json:"msg_id"`
	Note        pgtype.Text        `json:"note"`
}

// 防重投：同一 schedule_key + planned_at 唯一，冲突返回 0 行 = 本窗口已投递过。
func (q *Queries) RecordScheduleRun(ctx context.Context, arg RecordScheduleRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, recordScheduleRun,
		arg.ScheduleKey,
		arg.PlannedAt,
		arg.Queue,
		arg.MsgID,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const seedSchedulerSettings = `-- name: SeedSchedulerSettings :exec
insert into scheduler_settings (id, settings) values (true, $1)
on conflict (id) do nothing
`

// 仅在表为空时写入默认值（SPEC-008 §3.2：环境变量只 seed 首次，不覆盖用户设置）。
func (q *Queries) SeedSchedulerSettings(ctx context.Context, settings []byte) error {
	_, err := q.db.Exec(ctx, seedSchedulerSettings, settings)
	return err
}

const upsertSchedulerSettings = `-- name: UpsertSchedulerSettings :one
insert into scheduler_settings (id, settings) values (true, $1)
on conflict (id) do update set settings = excluded.settings, updated_at = now()
returning settings, updated_at
`

type UpsertSchedulerSettingsRow struct {
	Settings  []byte             `json:"settings"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSchedulerSettings(ctx context.Context, settings []byte) (UpsertSchedulerSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertSchedulerSettings, settings)
	var i UpsertSchedulerSettingsRow
	err := row.Scan(&i.Settings, &i.UpdatedAt)
	return i, err
}
