// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
insert into sources (name, type, url, category, weight, enabled, fetch_config)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, name, type, url, category, weight, enabled, fetch_config, created_at, updated_at, archived_at
`

type CreateSourceParams struct {
	Name        string         `json:"name"`
	Type        SourceType     `json:"type"`
	Url         pgtype.Text    `json:"url"`
	Category    SourceCategory `json:"category"`
	Weight      pgtype.Numeric `json:"weight"`
	Enabled     bool           `json:"enabled"`
	FetchConfig []byte         `json:"fetch_config"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Category,
		arg.Weight,
		arg.Enabled,
		arg.FetchConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Category,
		&i.Weight,
		&i.Enabled,
		&i.FetchConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :execrows
update sources
set enabled = false, archived_at = now(), updated_at = now()
where id = $1 and archived_at is null
`

// 历史素材必须保留其 source 外键和名称，因此 DELETE API 实现为归档。
func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueSources = `-- name: DueSources :many
select s.id, s.name, s.fetch_config
from sources s
left join source_health h on h.source_id = s.id
where s.enabled
  and s.archived_at is null
  and s.type <> 'manual'
  and (h.next_run_at is null or h.next_run_at <= now())
`

type DueSourcesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	FetchConfig []byte    `json:"fetch_config"`
}

// 调度器 tick 用：到期该采集的 enabled 源。
// next_run_at 为空（新源/从未跑过）视为立即到期。
func (q *Queries) DueSources(ctx context.Context) ([]DueSourcesRow, error) {
	rows, err := q.db.Query(ctx, dueSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueSourcesRow
	for rows.Next() {
		var i DueSourcesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.FetchConfig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSource = `-- name: GetSource :one
select s.id, s.name, s.type, s.url, s.category, s.weight, s.enabled, s.fetch_config, s.created_at, s.updated_at, s.archived_at,
       h.last_run_at, h.last_success_at, h.next_run_at,
       coalesce(h.consecutive_failures, 0) as consecutive_failures,
       h.last_error,
       (select count(*) from raw_items r where r.source_id = s.id) as item_count
from sources s
left join source_health h on h.source_id = s.id
where s.id = $1 and s.archived_at is null
`

type GetSourceRow struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Type                SourceType         `json:"type"`
	Url                 pgtype.Text        `json:"url"`
	Category            SourceCategory     `json:"category"`
	Weight              pgtype.Numeric     `json:"weight"`
	Enabled             bool               `json:"enabled"`
	FetchConfig         []byte             `json:"fetch_config"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	NextRunAt           pgtype.Timestamptz `json:"next_run_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	ItemCount           int64              `json:"item_count"`
}

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (GetSourceRow, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i GetSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Category,
		&i.Weight,
		&i.Enabled,
		&i.FetchConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.LastRunAt,
		&i.LastSuccessAt,
		&i.NextRunAt,
		&i.ConsecutiveFailures,
		&i.LastError,
		&i.ItemCount,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
select s.id, s.name, s.type, s.url, s.category, s.weight, s.enabled, s.fetch_config, s.created_at, s.updated_at, s.archived_at,
       h.last_run_at, h.last_success_at, h.next_run_at,
       coalesce(h.consecutive_failures, 0) as consecutive_failures,
       h.last_error,
       (select count(*) from raw_items r where r.source_id = s.id) as item_count
from sources s
left join source_health h on h.source_id = s.id
where s.enabled = coalesce($1::boolean, s.enabled)
  and s.archived_at is null
order by s.name
`

type ListSourcesRow struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Type                SourceType         `json:"type"`
	Url                 pgtype.Text        `json:"url"`
	Category            SourceCategory     `json:"category"`
	Weight              pgtype.Numeric     `json:"weight"`
	Enabled             bool               `json:"enabled"`
	FetchConfig         []byte             `json:"fetch_config"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	NextRunAt           pgtype.Timestamptz `json:"next_run_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	ItemCount           int64              `json:"item_count"`
}

func (q *Queries) ListSources(ctx context.Context, enabled pgtype.Bool) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources, enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourcesRow
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Category,
			&i.Weight,
			&i.Enabled,
			&i.FetchConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.LastRunAt,
			&i.LastSuccessAt,
			&i.NextRunAt,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourceScheduled = `-- name: MarkSourceScheduled :exec
insert into source_health (source_id, last_run_at, next_run_at)
values ($1, now(), $2)
on conflict (source_id) do update set
    last_run_at = now(), next_run_at = excluded.next_run_at, updated_at = now()
`

type MarkSourceScheduledParams struct {
	SourceID  uuid.UUID          `json:"source_id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

// 投递后立刻写 next_run_at，防同一窗口重复投递（与入队同事务）。
func (q *Queries) MarkSourceScheduled(ctx context.Context, arg MarkSourceScheduledParams) error {
	_, err := q.db.Exec(ctx, markSourceScheduled, arg.SourceID, arg.NextRunAt)
	return err
}

const recordSourceResult = `-- name: RecordSourceResult :exec
insert into source_health (source_id, last_success_at, consecutive_failures, last_error)
values (
    $1,
    case when $2::boolean then now() else null end,
    case when $2::boolean then 0 else 1 end,
    $3
)
on conflict (source_id) do update set
    last_success_at = case when $2::boolean then now() else source_health.last_success_at end,
    consecutive_failures = case when $2::boolean then 0 else source_health.consecutive_failures + 1 end,
    last_error = $3,
    updated_at = now()
`

type RecordSourceResultParams struct {
	SourceID uuid.UUID   `json:"source_id"`
	Ok       bool        `json:"ok"`
	Error    pgtype.Text `json:"error"`
}

// agents 采集完成后由 core 收割写入（成功清零连败，失败累加）。
func (q *Queries) RecordSourceResult(ctx context.Context, arg RecordSourceResultParams) error {
	_, err := q.db.Exec(ctx, recordSourceResult, arg.SourceID, arg.Ok, arg.Error)
	return err
}

const updateSource = `-- name: UpdateSource :one
update sources set
    name = coalesce($2, name),
    url = case when $3::boolean then $4 else url end,
    category = coalesce($5::source_category, category),
    weight = coalesce($6, weight),
    enabled = coalesce($7, enabled),
    fetch_config = coalesce($8, fetch_config),
    updated_at = now()
where id = $1
returning id, name, type, url, category, weight, enabled, fetch_config, created_at, updated_at, archived_at
`

type UpdateSourceParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        pgtype.Text        `json:"name"`
	SetUrl      bool               `json:"set_url"`
	Url         pgtype.Text        `json:"url"`
	Category    NullSourceCategory `json:"category"`
	Weight      pgtype.Numeric     `json:"weight"`
	Enabled     pgtype.Bool        `json:"enabled"`
	FetchConfig []byte             `json:"fetch_config"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.ID,
		arg.Name,
		arg.SetUrl,
		arg.Url,
		arg.Category,
		arg.Weight,
		arg.Enabled,
		arg.FetchConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Category,
		&i.Weight,
		&i.Enabled,
		&i.FetchConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
