// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: topics.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countTopics = `-- name: CountTopics :one
select count(*) from topics
where status = coalesce($1::topic_status, status)
`

func (q *Queries) CountTopics(ctx context.Context, status NullTopicStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countTopics, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManualTopic = `-- name: CreateManualTopic :one
insert into topics (title, angle, summary, target_platforms, status)
values ($1, $2, $3, $4, 'candidate')
returning id, title, angle, summary, raw_item_ids, target_platforms, status, latest_score, embedding, created_at, updated_at
`

type CreateManualTopicParams struct {
	Title           string     `json:"title"`
	Angle           string     `json:"angle"`
	Summary         string     `json:"summary"`
	TargetPlatforms []Platform `json:"target_platforms"`
}

func (q *Queries) CreateManualTopic(ctx context.Context, arg CreateManualTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createManualTopic,
		arg.Title,
		arg.Angle,
		arg.Summary,
		arg.TargetPlatforms,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Angle,
		&i.Summary,
		&i.RawItemIds,
		&i.TargetPlatforms,
		&i.Status,
		&i.LatestScore,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
select id, title, angle, summary, raw_item_ids, target_platforms, status, latest_score, embedding, created_at, updated_at from topics where id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Angle,
		&i.Summary,
		&i.RawItemIds,
		&i.TargetPlatforms,
		&i.Status,
		&i.LatestScore,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
select id, title, angle, summary, raw_item_ids, target_platforms, status, latest_score, embedding, created_at, updated_at from topics
where status = coalesce($1::topic_status, status)
order by latest_score desc nulls last, created_at desc
limit $3 offset $2
`

type ListTopicsParams struct {
	Status NullTopicStatus `json:"status"`
	Off    int32           `json:"off"`
	Lim    int32           `json:"lim"`
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Angle,
			&i.Summary,
			&i.RawItemIds,
			&i.TargetPlatforms,
			&i.Status,
			&i.LatestScore,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
