// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowArtifact = `-- name: CreateWorkflowArtifact :one
insert into workflow_artifacts (run_id, node_key, artifact_type, artifact_id, title, metadata)
values ($1, $2, $3, $4, $5, $6)
on conflict (run_id, artifact_type, artifact_id) do update
set title = excluded.title, metadata = excluded.metadata
returning id, run_id, node_key, artifact_type, artifact_id, title, metadata, created_at
`

type CreateWorkflowArtifactParams struct {
	RunID        uuid.UUID `json:"run_id"`
	NodeKey      string    `json:"node_key"`
	ArtifactType string    `json:"artifact_type"`
	ArtifactID   uuid.UUID `json:"artifact_id"`
	Title        string    `json:"title"`
	Metadata     []byte    `json:"metadata"`
}

func (q *Queries) CreateWorkflowArtifact(ctx context.Context, arg CreateWorkflowArtifactParams) (WorkflowArtifact, error) {
	row := q.db.QueryRow(ctx, createWorkflowArtifact,
		arg.RunID,
		arg.NodeKey,
		arg.ArtifactType,
		arg.ArtifactID,
		arg.Title,
		arg.Metadata,
	)
	var i WorkflowArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.ArtifactType,
		&i.ArtifactID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowEvent = `-- name: CreateWorkflowEvent :one
insert into workflow_events (run_id, node_key, event_type, status, message, agent_run_id, payload)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, run_id, sequence, node_key, event_type, status, message, agent_run_id, payload, occurred_at
`

type CreateWorkflowEventParams struct {
	RunID      uuid.UUID     `json:"run_id"`
	NodeKey    string        `json:"node_key"`
	EventType  string        `json:"event_type"`
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	AgentRunID uuid.NullUUID `json:"agent_run_id"`
	Payload    []byte        `json:"payload"`
}

func (q *Queries) CreateWorkflowEvent(ctx context.Context, arg CreateWorkflowEventParams) (WorkflowEvent, error) {
	row := q.db.QueryRow(ctx, createWorkflowEvent,
		arg.RunID,
		arg.NodeKey,
		arg.EventType,
		arg.Status,
		arg.Message,
		arg.AgentRunID,
		arg.Payload,
	)
	var i WorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.NodeKey,
		&i.EventType,
		&i.Status,
		&i.Message,
		&i.AgentRunID,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
insert into workflow_runs (id, correlation_id, mode, start_node, status, metadata)
values ($1, $2, $3, $4, 'queued', $5)
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at
`

type CreateWorkflowRunParams struct {
	ID            uuid.UUID `json:"id"`
	CorrelationID uuid.UUID `json:"correlation_id"`
	Mode          string    `json:"mode"`
	StartNode     string    `json:"start_node"`
	Metadata      []byte    `json:"metadata"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.CorrelationID,
		arg.Mode,
		arg.StartNode,
		arg.Metadata,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const finishWorkflowRun = `-- name: FinishWorkflowRun :one
update workflow_runs
set status = $2, error_message = $3, completed_at = now()
where id = $1 and status not in ('succeeded', 'failed')
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at
`

type FinishWorkflowRunParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FinishWorkflowRun(ctx context.Context, arg FinishWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, finishWorkflowRun, arg.ID, arg.Status, arg.ErrorMessage)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
select id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at from workflow_runs where id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listEnabledSourceIDs = `-- name: ListEnabledSourceIDs :many
select id from sources where enabled = true and archived_at is null order by created_at asc
`

func (q *Queries) ListEnabledSourceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEnabledSourceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowArticles = `-- name: ListWorkflowArticles :many
select a.id, a.title from articles a
join topics t on t.id = a.topic_id
where t.correlation_id = $1
order by a.created_at asc
`

type ListWorkflowArticlesRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowArticles(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowArticlesRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowArticles, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowArticlesRow
	for rows.Next() {
		var i ListWorkflowArticlesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowArtifacts = `-- name: ListWorkflowArtifacts :many
select id, run_id, node_key, artifact_type, artifact_id, title, metadata, created_at from workflow_artifacts
where run_id = $1
order by created_at asc
`

func (q *Queries) ListWorkflowArtifacts(ctx context.Context, runID uuid.UUID) ([]WorkflowArtifact, error) {
	rows, err := q.db.Query(ctx, listWorkflowArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowArtifact
	for rows.Next() {
		var i WorkflowArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeKey,
			&i.ArtifactType,
			&i.ArtifactID,
			&i.Title,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
select id, run_id, sequence, node_key, event_type, status, message, agent_run_id, payload, occurred_at from workflow_events
where run_id = $1 and sequence > $2
order by sequence asc
limit $3
`

type ListWorkflowEventsParams struct {
	RunID    uuid.UUID   `json:"run_id"`
	Sequence pgtype.Int8 `json:"sequence"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListWorkflowEvents(ctx context.Context, arg ListWorkflowEventsParams) ([]WorkflowEvent, error) {
	rows, err := q.db.Query(ctx, listWorkflowEvents, arg.RunID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEvent
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.NodeKey,
			&i.EventType,
			&i.Status,
			&i.Message,
			&i.AgentRunID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRawItems = `-- name: ListWorkflowRawItems :many
select id, title from raw_items where correlation_id = $1 order by created_at asc
`

type ListWorkflowRawItemsRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowRawItems(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowRawItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRawItems, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRawItemsRow
	for rows.Next() {
		var i ListWorkflowRawItemsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
select id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at from workflow_runs order by created_at desc limit $1
`

func (q *Queries) ListWorkflowRuns(ctx context.Context, limit int32) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.Mode,
			&i.StartNode,
			&i.Status,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTopics = `-- name: ListWorkflowTopics :many
select id, title from topics where correlation_id = $1 order by created_at asc
`

type ListWorkflowTopicsRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowTopics(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowTopicsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowTopics, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowTopicsRow
	for rows.Next() {
		var i ListWorkflowTopicsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowRunSucceeded = `-- name: MarkWorkflowRunSucceeded :one
update workflow_runs
set status = 'succeeded', completed_at = now()
where id = $1 and status in ('queued', 'running')
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at
`

func (q *Queries) MarkWorkflowRunSucceeded(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, markWorkflowRunSucceeded, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const startWorkflowRun = `-- name: StartWorkflowRun :one
update workflow_runs
set status = 'running', started_at = coalesce(started_at, now())
where id = $1 and status = 'queued'
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at
`

func (q *Queries) StartWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, startWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const workflowRunHasFailedEvent = `-- name: WorkflowRunHasFailedEvent :one
select exists (
    select 1 from workflow_events
    where run_id = $1 and event_type = 'failed'
)
`

func (q *Queries) WorkflowRunHasFailedEvent(ctx context.Context, runID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workflowRunHasFailedEvent, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workflowRunReadyToFinish = `-- name: WorkflowRunReadyToFinish :one
with latest_articles as (
    select distinct on (a.topic_id, a.platform) a.status
    from articles a
    join topics t on t.id = a.topic_id
    where t.correlation_id = $1
    order by a.topic_id, a.platform, a.version desc
)
select exists (select 1 from latest_articles)
   and not exists (
       select 1 from latest_articles
       where status not in ('pending_review', 'approved', 'published', 'rejected')
   )
`

func (q *Queries) WorkflowRunReadyToFinish(ctx context.Context, correlationID uuid.NullUUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, workflowRunReadyToFinish, correlationID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}
