// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWorkflowSnapshot = `-- name: ArchiveWorkflowSnapshot :one
update workflow_snapshots
set archived_at = coalesce(archived_at, now()),
    storage_ref = coalesce(nullif($3, ''), storage_ref, 'postgres://workflow_snapshots/' || id::text)
where id = $1 and run_id = $2
returning id, run_id, kind, payload, sha256, created_at, archived_at, storage_ref, retention_until
`

type ArchiveWorkflowSnapshotParams struct {
	ID      uuid.UUID   `json:"id"`
	RunID   uuid.UUID   `json:"run_id"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) ArchiveWorkflowSnapshot(ctx context.Context, arg ArchiveWorkflowSnapshotParams) (WorkflowSnapshot, error) {
	row := q.db.QueryRow(ctx, archiveWorkflowSnapshot, arg.ID, arg.RunID, arg.Column3)
	var i WorkflowSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Payload,
		&i.Sha256,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.StorageRef,
		&i.RetentionUntil,
	)
	return i, err
}

const createWorkflowArtifact = `-- name: CreateWorkflowArtifact :one
insert into workflow_artifacts (run_id, node_key, artifact_type, artifact_id, title, metadata)
values ($1, $2, $3, $4, $5, $6)
on conflict (run_id, node_key, artifact_type, artifact_id) do update
set title = excluded.title, metadata = excluded.metadata
returning id, run_id, node_key, artifact_type, artifact_id, title, metadata, created_at, parent_artifact_id, snapshot_id
`

type CreateWorkflowArtifactParams struct {
	RunID        uuid.UUID `json:"run_id"`
	NodeKey      string    `json:"node_key"`
	ArtifactType string    `json:"artifact_type"`
	ArtifactID   uuid.UUID `json:"artifact_id"`
	Title        string    `json:"title"`
	Metadata     []byte    `json:"metadata"`
}

func (q *Queries) CreateWorkflowArtifact(ctx context.Context, arg CreateWorkflowArtifactParams) (WorkflowArtifact, error) {
	row := q.db.QueryRow(ctx, createWorkflowArtifact,
		arg.RunID,
		arg.NodeKey,
		arg.ArtifactType,
		arg.ArtifactID,
		arg.Title,
		arg.Metadata,
	)
	var i WorkflowArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.ArtifactType,
		&i.ArtifactID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.ParentArtifactID,
		&i.SnapshotID,
	)
	return i, err
}

const createWorkflowDecision = `-- name: CreateWorkflowDecision :one
insert into workflow_item_decisions
    (run_id, node_run_id, item_id, item_type, decision, reason_code, reason,
     dimension_scores, total_score, threshold, weight_version, rubric_version,
     input_refs, evidence_refs, agent_run_id, trace_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
returning id, run_id, node_run_id, item_id, item_type, decision, reason_code, reason, dimension_scores, total_score, threshold, weight_version, rubric_version, input_refs, evidence_refs, agent_run_id, trace_id, created_at
`

type CreateWorkflowDecisionParams struct {
	RunID           uuid.UUID      `json:"run_id"`
	NodeRunID       uuid.UUID      `json:"node_run_id"`
	ItemID          uuid.UUID      `json:"item_id"`
	ItemType        string         `json:"item_type"`
	Decision        string         `json:"decision"`
	ReasonCode      string         `json:"reason_code"`
	Reason          string         `json:"reason"`
	DimensionScores []byte         `json:"dimension_scores"`
	TotalScore      pgtype.Numeric `json:"total_score"`
	Threshold       pgtype.Numeric `json:"threshold"`
	WeightVersion   pgtype.Int4    `json:"weight_version"`
	RubricVersion   pgtype.Text    `json:"rubric_version"`
	InputRefs       []byte         `json:"input_refs"`
	EvidenceRefs    []byte         `json:"evidence_refs"`
	AgentRunID      uuid.NullUUID  `json:"agent_run_id"`
	TraceID         pgtype.Text    `json:"trace_id"`
}

func (q *Queries) CreateWorkflowDecision(ctx context.Context, arg CreateWorkflowDecisionParams) (WorkflowItemDecision, error) {
	row := q.db.QueryRow(ctx, createWorkflowDecision,
		arg.RunID,
		arg.NodeRunID,
		arg.ItemID,
		arg.ItemType,
		arg.Decision,
		arg.ReasonCode,
		arg.Reason,
		arg.DimensionScores,
		arg.TotalScore,
		arg.Threshold,
		arg.WeightVersion,
		arg.RubricVersion,
		arg.InputRefs,
		arg.EvidenceRefs,
		arg.AgentRunID,
		arg.TraceID,
	)
	var i WorkflowItemDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeRunID,
		&i.ItemID,
		&i.ItemType,
		&i.Decision,
		&i.ReasonCode,
		&i.Reason,
		&i.DimensionScores,
		&i.TotalScore,
		&i.Threshold,
		&i.WeightVersion,
		&i.RubricVersion,
		&i.InputRefs,
		&i.EvidenceRefs,
		&i.AgentRunID,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowEvent = `-- name: CreateWorkflowEvent :one
insert into workflow_events (run_id, node_key, event_type, status, message, agent_run_id, payload)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, run_id, sequence, node_key, event_type, status, message, agent_run_id, payload, occurred_at
`

type CreateWorkflowEventParams struct {
	RunID      uuid.UUID     `json:"run_id"`
	NodeKey    string        `json:"node_key"`
	EventType  string        `json:"event_type"`
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	AgentRunID uuid.NullUUID `json:"agent_run_id"`
	Payload    []byte        `json:"payload"`
}

func (q *Queries) CreateWorkflowEvent(ctx context.Context, arg CreateWorkflowEventParams) (WorkflowEvent, error) {
	row := q.db.QueryRow(ctx, createWorkflowEvent,
		arg.RunID,
		arg.NodeKey,
		arg.EventType,
		arg.Status,
		arg.Message,
		arg.AgentRunID,
		arg.Payload,
	)
	var i WorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.NodeKey,
		&i.EventType,
		&i.Status,
		&i.Message,
		&i.AgentRunID,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const createWorkflowNodeRun = `-- name: CreateWorkflowNodeRun :one
insert into workflow_node_runs (run_id, node_key, status, config_snapshot)
values ($1, $2, 'queued', $3)
on conflict (run_id, node_key) do update set config_snapshot = excluded.config_snapshot
returning id, run_id, node_key, status, input_snapshot_id, output_snapshot_id, config_snapshot, counts, created_at, started_at, completed_at
`

type CreateWorkflowNodeRunParams struct {
	RunID          uuid.UUID `json:"run_id"`
	NodeKey        string    `json:"node_key"`
	ConfigSnapshot []byte    `json:"config_snapshot"`
}

func (q *Queries) CreateWorkflowNodeRun(ctx context.Context, arg CreateWorkflowNodeRunParams) (WorkflowNodeRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowNodeRun, arg.RunID, arg.NodeKey, arg.ConfigSnapshot)
	var i WorkflowNodeRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.Status,
		&i.InputSnapshotID,
		&i.OutputSnapshotID,
		&i.ConfigSnapshot,
		&i.Counts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
insert into workflow_runs (id, correlation_id, mode, start_node, status, metadata)
values ($1, $2, $3, $4, 'queued', $5)
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key
`

type CreateWorkflowRunParams struct {
	ID            uuid.UUID `json:"id"`
	CorrelationID uuid.UUID `json:"correlation_id"`
	Mode          string    `json:"mode"`
	StartNode     string    `json:"start_node"`
	Metadata      []byte    `json:"metadata"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.CorrelationID,
		arg.Mode,
		arg.StartNode,
		arg.Metadata,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerType,
		&i.ParentRunID,
		&i.ReplayFromNode,
		&i.ReplayScope,
		&i.InputSnapshotID,
		&i.ConfigSnapshotID,
		&i.Summary,
		&i.UpdatedAt,
		&i.ReplayKey,
	)
	return i, err
}

const createWorkflowSnapshot = `-- name: CreateWorkflowSnapshot :one
insert into workflow_snapshots (run_id, kind, payload, sha256)
values ($1, $2, $3, $4)
returning id, run_id, kind, payload, sha256, created_at, archived_at, storage_ref, retention_until
`

type CreateWorkflowSnapshotParams struct {
	RunID   uuid.UUID `json:"run_id"`
	Kind    string    `json:"kind"`
	Payload []byte    `json:"payload"`
	Sha256  string    `json:"sha256"`
}

func (q *Queries) CreateWorkflowSnapshot(ctx context.Context, arg CreateWorkflowSnapshotParams) (WorkflowSnapshot, error) {
	row := q.db.QueryRow(ctx, createWorkflowSnapshot,
		arg.RunID,
		arg.Kind,
		arg.Payload,
		arg.Sha256,
	)
	var i WorkflowSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Payload,
		&i.Sha256,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.StorageRef,
		&i.RetentionUntil,
	)
	return i, err
}

const finishWorkflowRun = `-- name: FinishWorkflowRun :one
update workflow_runs
set status = $2, error_message = $3, completed_at = now(), updated_at = now()
where id = $1 and status not in ('completed', 'completed_empty', 'partial_failed', 'failed', 'cancelled')
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key
`

type FinishWorkflowRunParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FinishWorkflowRun(ctx context.Context, arg FinishWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, finishWorkflowRun, arg.ID, arg.Status, arg.ErrorMessage)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerType,
		&i.ParentRunID,
		&i.ReplayFromNode,
		&i.ReplayScope,
		&i.InputSnapshotID,
		&i.ConfigSnapshotID,
		&i.Summary,
		&i.UpdatedAt,
		&i.ReplayKey,
	)
	return i, err
}

const getWorkflowNodeRun = `-- name: GetWorkflowNodeRun :one
select id, run_id, node_key, status, input_snapshot_id, output_snapshot_id, config_snapshot, counts, created_at, started_at, completed_at from workflow_node_runs where id = $1
`

func (q *Queries) GetWorkflowNodeRun(ctx context.Context, id uuid.UUID) (WorkflowNodeRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowNodeRun, id)
	var i WorkflowNodeRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.Status,
		&i.InputSnapshotID,
		&i.OutputSnapshotID,
		&i.ConfigSnapshot,
		&i.Counts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
select id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key from workflow_runs where id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerType,
		&i.ParentRunID,
		&i.ReplayFromNode,
		&i.ReplayScope,
		&i.InputSnapshotID,
		&i.ConfigSnapshotID,
		&i.Summary,
		&i.UpdatedAt,
		&i.ReplayKey,
	)
	return i, err
}

const getWorkflowSnapshotForRun = `-- name: GetWorkflowSnapshotForRun :one
select id, run_id, kind, payload, sha256, created_at, archived_at, storage_ref, retention_until from workflow_snapshots
where id = $1 and run_id = $2
`

type GetWorkflowSnapshotForRunParams struct {
	ID    uuid.UUID `json:"id"`
	RunID uuid.UUID `json:"run_id"`
}

func (q *Queries) GetWorkflowSnapshotForRun(ctx context.Context, arg GetWorkflowSnapshotForRunParams) (WorkflowSnapshot, error) {
	row := q.db.QueryRow(ctx, getWorkflowSnapshotForRun, arg.ID, arg.RunID)
	var i WorkflowSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Payload,
		&i.Sha256,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.StorageRef,
		&i.RetentionUntil,
	)
	return i, err
}

const listEnabledSourceIDs = `-- name: ListEnabledSourceIDs :many
select id from sources where enabled = true and archived_at is null order by created_at asc
`

func (q *Queries) ListEnabledSourceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEnabledSourceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowArticles = `-- name: ListWorkflowArticles :many
select a.id, a.title from articles a
join topics t on t.id = a.topic_id
where t.correlation_id = $1
order by a.created_at asc
`

type ListWorkflowArticlesRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowArticles(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowArticlesRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowArticles, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowArticlesRow
	for rows.Next() {
		var i ListWorkflowArticlesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowArtifacts = `-- name: ListWorkflowArtifacts :many
select id, run_id, node_key, artifact_type, artifact_id, title, metadata, created_at, parent_artifact_id, snapshot_id from workflow_artifacts
where run_id = $1
order by created_at asc
`

func (q *Queries) ListWorkflowArtifacts(ctx context.Context, runID uuid.UUID) ([]WorkflowArtifact, error) {
	rows, err := q.db.Query(ctx, listWorkflowArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowArtifact
	for rows.Next() {
		var i WorkflowArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeKey,
			&i.ArtifactType,
			&i.ArtifactID,
			&i.Title,
			&i.Metadata,
			&i.CreatedAt,
			&i.ParentArtifactID,
			&i.SnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDecisions = `-- name: ListWorkflowDecisions :many
select id, run_id, node_run_id, item_id, item_type, decision, reason_code, reason, dimension_scores, total_score, threshold, weight_version, rubric_version, input_refs, evidence_refs, agent_run_id, trace_id, created_at from workflow_item_decisions
where run_id = $1 and ($2 = '' or node_run_id = $2::uuid) and ($3 = '' or decision = $3)
order by created_at asc
`

type ListWorkflowDecisionsParams struct {
	RunID   uuid.UUID   `json:"run_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) ListWorkflowDecisions(ctx context.Context, arg ListWorkflowDecisionsParams) ([]WorkflowItemDecision, error) {
	rows, err := q.db.Query(ctx, listWorkflowDecisions, arg.RunID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowItemDecision
	for rows.Next() {
		var i WorkflowItemDecision
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeRunID,
			&i.ItemID,
			&i.ItemType,
			&i.Decision,
			&i.ReasonCode,
			&i.Reason,
			&i.DimensionScores,
			&i.TotalScore,
			&i.Threshold,
			&i.WeightVersion,
			&i.RubricVersion,
			&i.InputRefs,
			&i.EvidenceRefs,
			&i.AgentRunID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
select id, run_id, sequence, node_key, event_type, status, message, agent_run_id, payload, occurred_at from workflow_events
where run_id = $1 and sequence > $2
order by sequence asc
limit $3
`

type ListWorkflowEventsParams struct {
	RunID    uuid.UUID   `json:"run_id"`
	Sequence pgtype.Int8 `json:"sequence"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListWorkflowEvents(ctx context.Context, arg ListWorkflowEventsParams) ([]WorkflowEvent, error) {
	rows, err := q.db.Query(ctx, listWorkflowEvents, arg.RunID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEvent
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.NodeKey,
			&i.EventType,
			&i.Status,
			&i.Message,
			&i.AgentRunID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowNodeRuns = `-- name: ListWorkflowNodeRuns :many
select id, run_id, node_key, status, input_snapshot_id, output_snapshot_id, config_snapshot, counts, created_at, started_at, completed_at from workflow_node_runs where run_id = $1 order by created_at asc
`

func (q *Queries) ListWorkflowNodeRuns(ctx context.Context, runID uuid.UUID) ([]WorkflowNodeRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowNodeRuns, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowNodeRun
	for rows.Next() {
		var i WorkflowNodeRun
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NodeKey,
			&i.Status,
			&i.InputSnapshotID,
			&i.OutputSnapshotID,
			&i.ConfigSnapshot,
			&i.Counts,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRawItems = `-- name: ListWorkflowRawItems :many
select id, title from raw_items where correlation_id = $1 order by created_at asc
`

type ListWorkflowRawItemsRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowRawItems(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowRawItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRawItems, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowRawItemsRow
	for rows.Next() {
		var i ListWorkflowRawItemsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
select id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key from workflow_runs order by created_at desc limit $1
`

func (q *Queries) ListWorkflowRuns(ctx context.Context, limit int32) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.Mode,
			&i.StartNode,
			&i.Status,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TriggerType,
			&i.ParentRunID,
			&i.ReplayFromNode,
			&i.ReplayScope,
			&i.InputSnapshotID,
			&i.ConfigSnapshotID,
			&i.Summary,
			&i.UpdatedAt,
			&i.ReplayKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTopics = `-- name: ListWorkflowTopics :many
select id, title from topics where correlation_id = $1 order by created_at asc
`

type ListWorkflowTopicsRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) ListWorkflowTopics(ctx context.Context, correlationID uuid.NullUUID) ([]ListWorkflowTopicsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowTopics, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowTopicsRow
	for rows.Next() {
		var i ListWorkflowTopicsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowRunSucceeded = `-- name: MarkWorkflowRunSucceeded :one
update workflow_runs
set status = 'completed', completed_at = now(), updated_at = now()
where id = $1 and status in ('queued', 'running')
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key
`

func (q *Queries) MarkWorkflowRunSucceeded(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, markWorkflowRunSucceeded, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerType,
		&i.ParentRunID,
		&i.ReplayFromNode,
		&i.ReplayScope,
		&i.InputSnapshotID,
		&i.ConfigSnapshotID,
		&i.Summary,
		&i.UpdatedAt,
		&i.ReplayKey,
	)
	return i, err
}

const restoreWorkflowSnapshot = `-- name: RestoreWorkflowSnapshot :one
update workflow_snapshots
set archived_at = null
where id = $1 and run_id = $2
returning id, run_id, kind, payload, sha256, created_at, archived_at, storage_ref, retention_until
`

type RestoreWorkflowSnapshotParams struct {
	ID    uuid.UUID `json:"id"`
	RunID uuid.UUID `json:"run_id"`
}

func (q *Queries) RestoreWorkflowSnapshot(ctx context.Context, arg RestoreWorkflowSnapshotParams) (WorkflowSnapshot, error) {
	row := q.db.QueryRow(ctx, restoreWorkflowSnapshot, arg.ID, arg.RunID)
	var i WorkflowSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Payload,
		&i.Sha256,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.StorageRef,
		&i.RetentionUntil,
	)
	return i, err
}

const startWorkflowRun = `-- name: StartWorkflowRun :one
update workflow_runs
set status = 'running', started_at = coalesce(started_at, now())
where id = $1 and status = 'queued'
returning id, correlation_id, mode, start_node, status, error_message, metadata, created_at, started_at, completed_at, trigger_type, parent_run_id, replay_from_node, replay_scope, input_snapshot_id, config_snapshot_id, summary, updated_at, replay_key
`

func (q *Queries) StartWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, startWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.Mode,
		&i.StartNode,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerType,
		&i.ParentRunID,
		&i.ReplayFromNode,
		&i.ReplayScope,
		&i.InputSnapshotID,
		&i.ConfigSnapshotID,
		&i.Summary,
		&i.UpdatedAt,
		&i.ReplayKey,
	)
	return i, err
}

const updateWorkflowNodeRun = `-- name: UpdateWorkflowNodeRun :one
update workflow_node_runs
set status = $2,
    input_snapshot_id = coalesce($3, input_snapshot_id),
    output_snapshot_id = coalesce($4, output_snapshot_id),
    counts = coalesce($5, counts),
    started_at = case when $2 = 'running' then coalesce(started_at, now()) else started_at end,
    completed_at = case when $2 in ('succeeded', 'partial_failed', 'failed', 'skipped', 'cancelled') then now() else completed_at end
where id = $1
returning id, run_id, node_key, status, input_snapshot_id, output_snapshot_id, config_snapshot, counts, created_at, started_at, completed_at
`

type UpdateWorkflowNodeRunParams struct {
	ID               uuid.UUID     `json:"id"`
	Status           string        `json:"status"`
	InputSnapshotID  uuid.NullUUID `json:"input_snapshot_id"`
	OutputSnapshotID uuid.NullUUID `json:"output_snapshot_id"`
	Counts           []byte        `json:"counts"`
}

func (q *Queries) UpdateWorkflowNodeRun(ctx context.Context, arg UpdateWorkflowNodeRunParams) (WorkflowNodeRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowNodeRun,
		arg.ID,
		arg.Status,
		arg.InputSnapshotID,
		arg.OutputSnapshotID,
		arg.Counts,
	)
	var i WorkflowNodeRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NodeKey,
		&i.Status,
		&i.InputSnapshotID,
		&i.OutputSnapshotID,
		&i.ConfigSnapshot,
		&i.Counts,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const workflowRunHasFailedEvent = `-- name: WorkflowRunHasFailedEvent :one
select exists (
    select 1 from workflow_events
    where run_id = $1 and event_type = 'failed'
)
`

func (q *Queries) WorkflowRunHasFailedEvent(ctx context.Context, runID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workflowRunHasFailedEvent, runID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workflowRunReadyToFinish = `-- name: WorkflowRunReadyToFinish :one
with latest_articles as (
    select distinct on (a.topic_id, a.platform) a.status
    from articles a
    join topics t on t.id = a.topic_id
    where t.correlation_id = $1
    order by a.topic_id, a.platform, a.version desc
)
select exists (select 1 from latest_articles)
   and not exists (
       select 1 from latest_articles
       where status not in ('pending_review', 'approved', 'published', 'rejected')
   )
`

func (q *Queries) WorkflowRunReadyToFinish(ctx context.Context, correlationID uuid.NullUUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, workflowRunReadyToFinish, correlationID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}
